import assert from 'node:assert';
import test from 'node:test';
import { db } from '../server/db/database.js';
import { CMDBError, CMDBService } from '../server/services/cmdb.service.js';
import { CMDBSyncService } from '../server/services/cmdb-sync.service.js';
import { CMDBController } from '../server/controllers/cmdb.controller.js';
import { initialSeedData } from '../server/db/seed.js';
import type { BankUser } from '../shared/types/auth.js';

const response = () => {
  let payload: any;
  const value: any = { status: () => value, json: (body: any) => { payload = body; return value; }, payload: () => payload };
  return value;
};

test('CMDB canonical CI lifecycle, duplicate controls, relationships and impact', () => {
  const original = structuredClone(db.data); db.reset(structuredClone(initialSeedData));
  try {
    const actor: BankUser = { id: 'usr-cmdb-ciso', username: 'cmdb.ciso', email: 'cmdb.ciso@bank.test', fullName: 'CMDB CISO', title: 'CISO', divisionId: '', departmentId: '', teamIds: [], roles: ['CISO', 'PLATFORM_ADMIN'], securityClearance: 'HIGHLY_RESTRICTED_HR_LEGAL', ownedApplicationIds: [], ownedAssetIds: [], ownedRiskIds: [], isActive: true };
    db.data.users.push(actor);
    db.data.departments.push({ id: 'dept-cmdb-a', divisionId: '', name: 'CMDB Operations', code: 'CMDB_OPS', isActive: true, directorySource: 'ACTIVE_DIRECTORY', settings: {} } as any, { id: 'dept-cmdb-b', divisionId: '', name: 'CMDB Other', code: 'CMDB_OTHER', isActive: true, directorySource: 'ACTIVE_DIRECTORY', settings: {} } as any);
    const departmentManager: BankUser = { ...actor, id: 'usr-cmdb-manager', username: 'cmdb.manager', email: 'cmdb.manager@bank.test', roles: ['DEPARTMENT_MANAGER'], departmentId: 'dept-cmdb-a' };
    db.data.users.push(departmentManager);
    CMDBService.ensureReferenceData();
    const customType = CMDBService.createType({ id: 'saas_service', name: 'SaaS Service', parentTypeId: 'software' }, actor);
    assert.strictEqual(CMDBService.updateType(customType.id, { isActive: false }, actor).isActive, false);
    const customRelationship = CMDBService.createRelationshipType({ id: 'routes_to', name: 'ROUTES_TO', inverseName: 'ROUTED_FROM' }, actor);
    assert.strictEqual(customRelationship.inverseName, 'ROUTED_FROM');
    const savedView = CMDBService.saveView({ name: 'Production applications', filters: { typeId: 'application', environment: 'PRODUCTION' } }, actor);
    assert.strictEqual(CMDBService.savedViews(actor)[0].id, savedView.id);
    const restrictedType = CMDBService.createType({ id: 'restricted_service', name: 'Restricted Service', parentTypeId: 'software', allowedRelationshipTypeIds: ['uses'] }, actor);
    const discovered = CMDBSyncService.sync('SCCM', { sourceRecordId: 'sccm-01', name: 'SCCM endpoint', typeId: 'laptop', hostname: 'laptop-01', serialNumber: 'SN-01' }, actor);
    const synced = CMDBSyncService.sync('SCCM', { sourceRecordId: 'sccm-01', name: 'SCCM endpoint renamed', typeId: 'laptop', hostname: 'laptop-01', serialNumber: 'SN-01' }, actor);
    assert.strictEqual(discovered.action, 'CREATED');
    assert.strictEqual(synced.action, 'UPDATED');
    const server = CMDBService.create({ name: 'DB-PROD-01', typeId: 'database', environment: 'PRODUCTION', criticality: 'CRITICAL', hostname: 'db-prod-01', source: 'MANUAL' }, actor);
    const app = CMDBService.create({ name: 'Core Banking API', typeId: 'application', environment: 'PRODUCTION', criticality: 'CRITICAL', source: 'MANUAL' }, actor);
    const service = CMDBService.create({ name: 'Internet Banking', typeId: 'business_service', environment: 'PRODUCTION', criticality: 'CRITICAL', source: 'MANUAL' }, actor);
    const restricted = CMDBService.create({ name: 'Restricted integration', typeId: restrictedType.id, environment: 'PRODUCTION', criticality: 'HIGH', source: 'MANUAL' }, actor);
    const legacyAssetResponse = response(); CMDBController.legacyAssets({ user: actor, query: {} } as any, legacyAssetResponse);
    assert.strictEqual(legacyAssetResponse.payload().assets[0].hostname, 'laptop-01');
    const legacyApplicationResponse = response(); CMDBController.legacyApplications({ user: actor, query: {} } as any, legacyApplicationResponse);
    assert.strictEqual(legacyApplicationResponse.payload().applications[0].id, app.id);
    assert.throws(() => CMDBService.create({ name: 'Duplicate host', typeId: 'database', hostname: 'db-prod-01', source: 'MANUAL' }, actor), (error: any) => error instanceof CMDBError && error.statusCode === 409);
    assert.throws(() => CMDBService.create({ name: 'Invalid initial lifecycle', typeId: 'laptop', lifecycleStatus: 'DISPOSED', source: 'MANUAL' }, actor), /approved intake lifecycle state/);
    assert.throws(() => CMDBService.create({ name: 'Invalid application metadata', typeId: 'application', source: 'MANUAL', details: { arbitraryClientField: true } }, actor), /Invalid application metadata/);
    const scopedCi = CMDBService.create({ name: 'Department-owned VM', typeId: 'virtual_machine', departmentId: 'dept-cmdb-a', source: 'MANUAL' }, actor);
    assert.throws(() => CMDBService.update(scopedCi.id, { version: scopedCi.version, departmentId: 'dept-cmdb-b' }, departmentManager), /move a CI between departments/);
    assert.throws(() => CMDBService.relationship(restricted.id, { targetCiId: app.id, relationshipTypeId: 'depends_on' }, actor), /cannot use/);
    CMDBService.relationship(restricted.id, { targetCiId: app.id, relationshipTypeId: 'uses' }, actor);
    CMDBService.relationship(app.id, { targetCiId: server.id, relationshipTypeId: 'depends_on' }, actor);
    CMDBService.relationship(service.id, { targetCiId: app.id, relationshipTypeId: 'depends_on' }, actor);
    assert.throws(() => CMDBService.relationship(server.id, { targetCiId: app.id, relationshipTypeId: 'depends_on' }, actor), (error: any) => error instanceof CMDBError && error.statusCode === 409);
    const impact: any = CMDBService.impact(server.id);
    assert.strictEqual(impact.affectedBusinessServices[0].ci.id, service.id);
    const graph = CMDBService.graph(server.id, { depth: '3', direction: 'downstream' });
    assert.ok(graph.nodes.some((node) => node.id === service.id));
    assert.ok(graph.edges.every((edge) => edge.source !== edge.target));
    const applicationGraph = CMDBService.graph(server.id, { depth: '3', direction: 'downstream', ciTypes: 'application' });
    assert.ok(applicationGraph.nodes.every((node) => node.id === server.id || node.typeId === 'application'));
    const ticketLink = CMDBService.linkTicketOnCreate(server.id, 'ticket-cmdb-test', actor);
    assert.strictEqual(ticketLink.recordType, 'TICKET');
    assert.strictEqual(CMDBService.linkRecord(server.id, { recordType: 'VULNERABILITY', recordId: 'vuln-cmdb-test' }, actor).recordType, 'VULNERABILITY');
    assert.ok(CMDBService.relatedRecords(server.id).some((link) => link.recordId === 'ticket-cmdb-test'));
    assert.strictEqual(CMDBService.ticketContext('ticket-cmdb-test')[0].ci.id, server.id);
    const duplicate = CMDBService.create({ name: 'Merge candidate', typeId: 'database', environment: 'PRODUCTION', criticality: 'HIGH', source: 'MANUAL' }, actor);
    const softDuplicate = CMDBService.create({ name: 'Merge candidate', typeId: 'database', environment: 'TEST', criticality: 'LOW', source: 'MANUAL' }, actor);
    assert.strictEqual(CMDBService.duplicateCandidates(duplicate.id)[0].ci.id, softDuplicate.id);
    CMDBService.relationship(duplicate.id, { targetCiId: app.id, relationshipTypeId: 'uses' }, actor);
    CMDBService.linkTicketOnCreate(duplicate.id, 'ticket-merge-test', actor);
    const merged = CMDBService.merge(duplicate.id, server.id, actor);
    assert.ok((merged.details as any).mergedCiNumbers.includes(duplicate.ciNumber));
    assert.ok(CMDBService.relatedRecords(server.id).some((link) => link.recordId === 'ticket-merge-test'));
    assert.throws(() => CMDBService.update(server.id, { version: merged.version, lifecycleStatus: 'DISPOSED' }, actor), /Invalid lifecycle transition/);
    const assigned = CMDBService.update(server.id, { version: merged.version, lifecycleStatus: 'ASSIGNED' }, actor);
    const inUse = CMDBService.update(server.id, { version: assigned.version, lifecycleStatus: 'IN_USE' }, actor);
    assert.strictEqual(inUse.lifecycleStatus, 'IN_USE');
    assert.ok(CMDBService.history(server.id).some((event) => event.action === 'CMDB_CI_UPDATED'));
  } finally { db.reset(original); }
});
