import test, { after, before } from 'node:test';
import assert from 'node:assert/strict';
import { createHash, randomUUID, generateKeyPairSync, sign } from 'node:crypto';
import { ThreatDeploymentService as delivery, GitLabSecurityDeploymentProvider } from '../server/services/threat-deployment.service.js';
import { pgClient } from '../server/db/postgres/client.js';
import { ThreatModelRepository } from '../server/db/postgres/threat-model-repository.js';
import { db } from '../server/db/database.js';
import { config } from '../server/config/index.js';
import { ThreatModelService as service } from '../server/services/threat-model.service.js';
import { ThreatControlCatalogService as catalog } from '../server/services/threat-control-catalog.service.js';
import { ThreatAnalysisService as analysis, attackCaseSchema } from '../server/services/threat-analysis.service.js';
import { ThreatGovernanceAdminService as governanceAdmin } from '../server/services/threat-governance-admin.service.js';
import { storageService } from '../server/services/storage.service.js';
import { screeningRules } from '../server/services/threat-model-policy.js';
import { canonicalJson } from '../shared/canonical-json.js';
import { ThreatReadinessService as coverage } from '../server/services/threat-readiness.service.js';
import { ThreatComplianceApplicabilityService as complianceProfiles } from '../server/services/threat-compliance-applicability.service.js';
import { assertDisposableDatabase } from './fixtures/disposable-database.js';
import type { BankUser } from '../shared/types/auth.js';

const enabled = process.env.RUN_CMDB_DISCOVERY_INTEGRATION === '1' && /(?:^|_)integration(?:_|$)/.test(config.DB_NAME);
before(async () => { if (enabled) await assertDisposableDatabase(pgClient, config.DB_NAME); });
after(() => pgClient.close());

test('persistent governance lifecycle, RBAC, review cycles, copies and immutable approval package', { skip: !enabled }, async t => {
  const suffix = randomUUID().slice(0,8);
  const user = async (name: string, roles: BankUser['roles']) => {
    const id = `tmtest-${name}-${suffix}`;
    await pgClient.query(`INSERT INTO bank_users(id,username,email,first_name,last_name,title,roles,security_clearance) VALUES($1,$1,$2,$1,'Fixture','TEST',$3::jsonb,'CONFIDENTIAL_SECURITY_ONLY')`, [id, `${id}@example.invalid`,JSON.stringify(roles)]);
    const actor = { id, username:id, fullName:id, roles, isActive:true, securityClearance:'CONFIDENTIAL_SECURITY_ONLY', ownedApplicationIds:[], ownedAssetIds:[], teamIds:[] } as unknown as BankUser;
    db.data.users.push(actor); return actor;
  };
  const owner = await user('owner',['APPLICATION_OWNER']);
  const reviewer = await user('reviewer',['APPSEC_ANALYST','RELEASE_AUTHORITY']);
  const architect = await user('architect',['INFOSEC_MANAGER','SECURITY_ARCHITECT']);
  const postReviewer = await user('post-reviewer',['APPSEC_ANALYST']);
  const ciso = await user('ciso',['CISO']);
  const admin = await user('admin',['PLATFORM_ADMIN']);
  const outsider = await user('outsider',['REQUESTER']);
  const coverageReviewer = await user('coverage-reviewer',['APPSEC_ANALYST']);
  const grcAuthor=await user('grc-author',['GRC_ANALYST']),grcReviewer=await user('grc-reviewer',['GRC_ANALYST']);
  const definition=await service.addComplianceRequirement({framework:'Fixture-only standard',frameworkVersion:'1',code:`OUTSIDE-SCOPE-${suffix}`,title:'Obligation for another organization',requirementKind:'BANK_POLICY',sourceUrl:'https://example.invalid/fixture-policy'},grcAuthor);
  await governanceAdmin.decideCompliance(definition.id,{decision:'VALIDATED',reason:'Fixture-only independently validated definition'},grcReviewer);
  const profile=await complianceProfiles.profile({code:`SCOPE-${suffix}`,effectiveAt:new Date(Date.now()-1000).toISOString(),predicates:{organizationId:'outside-fixture-organization'},complianceIds:[definition.id],humanReview:false,reason:'Fixture policy applies only to a different organization'},grcAuthor);
  await complianceProfiles.reviewProfile({profileId:profile.id,decision:'APPROVED',reason:'Independent review confirms this fixture applicability predicate'},grcReviewer);
  const completeCoverage=async(mid:string)=>{
    for(const unit of (await coverage.get(mid,owner)).units.filter(u=>!u.completed)){
      const decision=await coverage.dispose(mid,{unitId:unit.id,fingerprint:unit.fingerprint,disposition:'REVIEWED_NO_THREAT',reason:`Fixture analysis of ${unit.label}: ${unit.category}; no additional scenario identified.`},owner);
      await coverage.review(mid,{dispositionId:decision.id,decision:'APPROVED',reason:'Independent fixture review confirms the documented target analysis'},coverageReviewer);
    }
  };
  const appId = `tmtest-app-${suffix}`;
  await pgClient.query(`INSERT INTO bank_applications(id,code,name,tier,architecture_type,technical_owner_id,business_owner_id) VALUES($1,$1,'Fixture application','LOW','MONOLITH',$2,$2)`, [appId,owner.id]);
  db.data.applications.push({ id:appId, name:'Fixture application',technicalOwnerId:owner.id,businessOwnerId:owner.id } as any);
  const created = await service.create({ title:'Governance fixture',serviceId:appId,criticality:'LOW',dataClassification:'INTERNAL',businessOwnerId:owner.id,technicalOwnerId:owner.id,scopeSummary:'Fixture scope',architectureSummary:'Fixture architecture',assumptions:'Fixture assumptions',securityObjectives:'Test objectives' },owner);
  const modelId = String(created.model!.id); const revisionId = String(created.revision.id);
  const answers = Object.fromEntries(screeningRules.map(rule => [rule.signal, rule.signal === 'internalChange']));
  await t.test('unscreened model blocks submission; tier cannot be overridden', async () => {
    await assert.rejects(service.submit(modelId,owner),/screening is required/);
    await assert.rejects(service.assessApplicability({ threatModelId:modelId, answers, justification:'Fixture',tier:0 },owner),/tier override/);
    const assessment = await service.assessApplicability({ threatModelId:modelId, answers, justification:'Fixture' },owner);
    assert.equal(assessment.tier,1);
  });
  await t.test('object access and admin approval are rejected by backend', async () => {
    await assert.rejects(service.detail(modelId,outsider),/restricted/);
    await assert.rejects(service.detail(modelId,admin),/restricted/);
    await assert.rejects(service.decideApproval(modelId,{stage:'APPSEC',decision:'APPROVED'},admin),/authority/);
  });
  const component = await service.addComponent(modelId,{name:'API',type:'API',securityZone:'INTERNAL'},owner);
  const threat = await service.addThreat(modelId,{title:'Unauthorized access',description:'Test scenario',attackScenario:'Fixture actor accesses forbidden data',categories:['SPOOFING'],inherentLikelihood:2,inherentImpact:2,affectedComponentId:component.id},owner);
  const control = await service.addControl(threat.id,{title:'Authorization',description:'Server authorization',controlType:'PREVENTIVE',implementationOwnerId:owner.id},owner);
  await service.createRequirement(modelId,{title:'Server authorization',description:'Authorize all reads',ownerId:owner.id,verificationMethod:'API_SECURITY_TEST',threatIds:[threat.id],controlIds:[control.id]},owner);
  await t.test('duplicate requirement is rejected without a partial insert',async () => {
    await assert.rejects(service.createRequirement(modelId,{title:'Server authorization',description:'Duplicate',ownerId:owner.id,verificationMethod:'API_SECURITY_TEST',threatIds:[threat.id]},owner));
    assert.equal((await pgClient.query('SELECT count(*)::int AS n FROM threat_security_requirements WHERE revision_id=$1',[revisionId])).rows[0].n,1);
    await assert.rejects(service.transitionThreat(threat.id,{status:'CLOSED',reason:'Attempt bypass'},owner),/Invalid/);
    await assert.rejects(service.recordVerification(control.id,{result:'PASS',verificationType:'API_SECURITY_TEST',testCase:'test',expectedResult:'deny',evidenceIds:[]},reviewer),/evidence/);
  });
  const ticketId = `tmtest-ticket-${suffix}`;
  await pgClient.query(`INSERT INTO tickets(id,key,project_code,ticket_type_id,ticket_type_name,category,security_domain,title,description,status_id,status_name,status_category,workflow_id,technical_severity,business_priority,business_impact,inherent_risk,residual_risk,reporter_id,due_date,remediation_deadline) VALUES($1,$1,'TEST','TEST','Fixture','SECURITY_REVIEW','APPSEC','Fixture evidence','Fixture','test-open','Open','TODO','test-workflow','LOW','P3_MEDIUM','MODERATE','LOW','LOW',$2,NOW()+INTERVAL '1 day',NOW()+INTERVAL '1 day')`,[ticketId,owner.id]);
  const attachmentId = `tmtest-attachment-${suffix}`;
  await pgClient.query('UPDATE threat_models SET release_id=$1 WHERE id=$2',[ticketId,modelId]);
  await pgClient.query(`INSERT INTO ticket_attachments(id,ticket_id,file_name,file_size_bytes,mime_type,storage_key,sha256_hash,uploaded_by_user_id,source_payload) VALUES($1,$2,'fixture.txt',4,'text/plain','test-only',$3,$4,'{"virusScanStatus":"CLEAN"}'::jsonb)`,[attachmentId,ticketId,createHash('sha256').update('test').digest('hex'),owner.id]);
  db.data.tickets.push({id:ticketId,reporterId:owner.id,requesterId:owner.id,ownerId:owner.id,confidentiality:'INTERNAL',securityDomain:'APPSEC',watcherIds:[],participantIds:[]} as any);
  db.data.attachments.push({id:attachmentId,ticketId,virusScanStatus:'CLEAN'} as any);
  const evidence = await service.linkEvidence(modelId,{attachmentId,controlId:control.id},owner);
  await service.recordVerification(control.id,{result:'PASS',verificationType:'API_SECURITY_TEST',testCase:'Unauthorized read',expectedResult:'403',evidenceIds:[evidence.id]},reviewer);
  await service.calculateResidualRisk(threat.id,{residualLikelihood:1,residualImpact:1,residualRiskRationale:'Fixture test proves authorization'},reviewer);
  await service.transitionThreat(threat.id,{status:'MITIGATING',reason:'Implemented'},owner);
  await service.transitionThreat(threat.id,{status:'MITIGATED',reason:'Verified'},reviewer);
  await t.test('approval from earlier review cycle does not survive requested changes',async () => {
    await service.assessApplicability({threatModelId:modelId,answers,justification:'Re-screen completed architecture'},owner);
    await service.submit(modelId,owner);
    await service.decideApproval(modelId,{stage:'APPSEC',decision:'APPROVED'},reviewer);
    await service.decideApproval(modelId,{stage:'SECURITY_ARCHITECTURE',decision:'CHANGES_REQUESTED'},architect);
    await service.submit(modelId,owner);
    await service.decideApproval(modelId,{stage:'SECURITY_ARCHITECTURE',decision:'APPROVED'},architect);
    assert.equal((await service.detail(modelId,owner)).model && ((await service.detail(modelId,owner)).model as any).status,'IN_REVIEW');
    await service.decideApproval(modelId,{stage:'APPSEC',decision:'APPROVED'},reviewer);
    assert.equal((await service.releaseGate(modelId,owner)).securityGate,'PASS');
  });
  await t.test('approved content and approval snapshot resist direct SQL writes',async () => {
    await assert.rejects(pgClient.query("UPDATE threats SET title='tamper' WHERE id=$1",[threat.id]),/immutable/);
    await assert.rejects(service.calculateResidualRisk(threat.id,{residualLikelihood:1,residualImpact:1,residualRiskRationale:'tamper'},reviewer),/immutable/);
    await assert.rejects(pgClient.query('DELETE FROM threat_model_approval_snapshots WHERE revision_id=$1',[revisionId]),/append-only/);
    const report = await service.exportSnapshot(modelId,revisionId,owner);
    assert.equal(report.sha256,createHash('sha256').update(canonicalJson(report.snapshot)).digest('hex'));
    assert.equal(report.snapshot.revision[0].status,'APPROVED');
    const audit = (await pgClient.query('SELECT * FROM threat_model_audit_events WHERE threat_model_id=$1 ORDER BY event_sequence DESC LIMIT 1',[modelId])).rows[0];
    assert.match(audit.event_hash,/^[a-f0-9]{64}$/);
    assert.equal(audit.event_hash,ThreatModelRepository.auditDigest(audit));
    assert.notEqual(audit.event_hash,ThreatModelRepository.auditDigest({...audit,action:'TAMPERED'}));
  });
  const authorization = await service.authorizeRelease(modelId,ticketId,reviewer);
  await t.test('signed GitLab identity binds canonical application, commit and environment; consumption and provider receipt are one-time',async t=>{
    const releaseAdmin=await user('release-admin',['INFOSEC_ADMIN','RELEASE_AUTHORITY']);
    const mapping=await delivery.configure({issuer:'https://gitlab.example.invalid',audience:'https://security.example.invalid',projectId:'17',environment:'production',ref:'main',applicationId:appId,modelId,releaseId:ticketId,apiCredential:'fixture-scoped-project-credential'},releaseAdmin);
    const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048});
    const sha='a'.repeat(40),now=Math.floor(Date.now()/1000);
    const claims={iss:'https://gitlab.example.invalid',aud:'https://security.example.invalid',iat:now,exp:now+300,project_id:'17',job_project_id:'17',job_id:'101',pipeline_id:'51',ref:'main',environment:'production',ref_protected:true,environment_protected:true,jti:randomUUID(),sha};
    const header=Buffer.from(JSON.stringify({alg:'RS256',kid:'fixture-key'})).toString('base64url');
    const tokenFor=(value:unknown)=>{const payload=`${header}.${Buffer.from(JSON.stringify(value)).toString('base64url')}`;return `${payload}.${sign('RSA-SHA256',Buffer.from(payload),privateKey).toString('base64url')}`;};
    const receipt={id:701,sha,status:'success',environment:{name:'production'},deployable:{id:101,pipeline:{id:51}}};
    const adapter=new GitLabSecurityDeploymentProvider(async url=>url.includes('/oauth/')?{keys:[{...publicKey.export({format:'jwk'}),kid:'fixture-key'}]}:url.includes('/jobs/')?{id:101,ref:'main',status:'running',commit:{id:sha},pipeline:{id:51},user:{id:9}}:receipt);
    t.mock.method(delivery.provider,'verifyIdentity',(m,token)=>adapter.verifyIdentity(m,token));
    t.mock.method(delivery.provider,'verifyDeployment',(m,a,id)=>adapter.verifyDeployment(m,a,id));
    const binding={applicationId:appId,releaseId:ticketId,commitSha:sha,environment:'production'};
    const jwt=tokenFor(claims);
    await assert.rejects(delivery.authorize(mapping.id,tokenFor({...claims,environment:'staging'}),binding),/mismatch/);
    await assert.rejects(delivery.authorize(mapping.id,tokenFor({...claims,exp:now-1}),binding),/Expired/);
    await assert.rejects(delivery.authorize(mapping.id,jwt,{...binding,commitSha:'b'.repeat(40)}),/mismatch/);
    const grant=await delivery.authorize(mapping.id,jwt,binding);
    for(const wrong of [{...binding,commitSha:'b'.repeat(40)},{...binding,applicationId:'another-application'},{...binding,environment:'staging'}])await assert.rejects(delivery.consume(mapping.id,jwt,{authorizationId:grant.authorizationId,token:grant.token,binding:wrong}),/mismatch/);
    const consume=()=>delivery.consume(mapping.id,jwt,{authorizationId:grant.authorizationId,token:grant.token,binding});
    const results=await Promise.allSettled([consume(),consume()]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);
    const success=results.find(r=>r.status==='fulfilled') as PromiseFulfilledResult<any>;assert.equal(success.value.deploymentExecuted,false);
    await assert.rejects(consume(),/already consumed/);
    assert.equal((await delivery.callback(mapping.id,jwt,{authorizationId:grant.authorizationId,deploymentId:'701'}))?.state,'SUCCEEDED');
    assert.equal((await delivery.callback(mapping.id,jwt,{authorizationId:grant.authorizationId,deploymentId:'701'}))?.state,'SUCCEEDED');
    assert.equal((await pgClient.query("SELECT count(*)::int AS n FROM threat_deployment_events WHERE authorization_id=$1 AND state='SUCCEEDED'",[grant.authorizationId])).rows[0].n,1);
    await assert.rejects(delivery.receipts(modelId,outsider),/restricted/);
    await assert.rejects(pgClient.query("DELETE FROM threat_deployment_events WHERE authorization_id=$1",[grant.authorizationId]),/append-only/);
  });
  await t.test('release authorization is persisted, freshly evaluated and consumed idempotently',async () => {
    await assert.rejects(service.authorizeRelease(modelId,ticketId,admin),/authority/);
    const request = {releaseId:ticketId,authorization:authorization.authorization,idempotencyKey:'fixture-job-1'};
    assert.equal((await service.consumeReleaseAuthorization(modelId,request,reviewer)).deploymentExecuted,false);
    assert.equal((await service.consumeReleaseAuthorization(modelId,request,reviewer)).gate.securityGate,'PASS');
    await assert.rejects(service.consumeReleaseAuthorization(modelId,{...request,idempotencyKey:'fixture-job-2'},reviewer),/already consumed/);
  });
  await t.test('concurrent new revisions copy architecture and requirements exactly once without carrying verification',async () => {
    const results = await Promise.allSettled([service.createRevision(modelId,{changeReason:'Material API change'},owner),service.createRevision(modelId,{changeReason:'Concurrent change'},owner)]);
    assert.equal(results.filter(result=>result.status==='fulfilled').length,1);
    const detail = await service.detail(modelId,owner) as any;
    assert.equal(detail.components.length,1); assert.equal(detail.controls.length,1); assert.equal(detail.verifications.length,0);
    assert.equal(detail.model.revisionNumber,2);
    assert.equal(detail.threats[0].lineageId,threat.lineageId);
    assert.equal(detail.threats[0].previousThreatId,threat.id);
    const lineage=await service.threatLineage(detail.threats[0].id,{limit:1},owner);
    assert.equal(lineage.hasMore,true);assert.equal(lineage.versions[0].revisionNumber,2);
    const older=await service.threatLineage(detail.threats[0].id,{limit:1,offset:1},owner);
    assert.equal(older.versions[0].id,threat.id);assert.equal(older.versions[0].revisionStatus,'APPROVED');
    assert.equal((await service.exportSnapshot(modelId,revisionId,owner)).snapshot.threats[0].lineage_id,threat.lineageId);
    await assert.rejects(service.threatLineage(detail.threats[0].id,{},outsider),/restricted/);
    await assert.rejects(service.updateThreat(threat.id,{...threat,reason:'Historical edit'},owner),/no longer current/);
    assert.equal((await service.governanceDetail(modelId,owner)).requirements.length,1);
    assert.equal((await service.releaseGate(modelId,owner)).securityGate,'BLOCK');
    assert.equal((await service.exportSnapshot(modelId,revisionId,owner)).snapshot.revision[0].status,'APPROVED');
    await assert.rejects(service.consumeReleaseAuthorization(modelId,{releaseId:ticketId,authorization:authorization.authorization,idempotencyKey:'fixture-job-1'},reviewer),/no longer current/);
  });
  await t.test('high-risk exception uses calculated severity, bounded lifetime and independent CISO approval',async () => {
    const high = await service.addThreat(modelId,{title:'High scenario',description:'Fixture',attackScenario:'High scenario',categories:['BUSINESS_ABUSE'],inherentLikelihood:3,inherentImpact:4},owner);
    const request = {reason:'Remediation needs change window',businessJustification:'Bounded test exposure',compensatingControls:'Manual approvals',remediationOwnerId:owner.id,remediationPlan:'Remediate before expiry',remediationDeadline:new Date(Date.now()+86400000).toISOString(),expiresAt:new Date(Date.now()+2*86400000).toISOString()};
    await assert.rejects(service.requestRiskAcceptance(high.id,{...request,riskLevel:'LOW'},owner),/risk level override/);
    await assert.rejects(service.requestRiskAcceptance(high.id,{...request,expiresAt:new Date(Date.now()+31*86400000).toISOString()},owner),/maximum/);
    const exception = await service.requestRiskAcceptance(high.id,request,owner);
    await assert.rejects(service.decideRiskAcceptance(exception.id,{decision:'APPROVED'},reviewer),/CISO/);
    await service.decideRiskAcceptance(exception.id,{decision:'APPROVED'},ciso);
    await assert.rejects(service.decideRiskAcceptance(exception.id,{decision:'APPROVED'},ciso),/renewal/);
    await service.decideRiskAcceptance(exception.id,{decision:'REVOKED'},ciso);
    await assert.rejects(service.transitionThreat(high.id,{status:'ACCEPTED',reason:'Revoked'},reviewer),/current approved risk acceptance/);
    await assert.rejects(service.requestRiskAcceptance(high.id,request,owner),/Renewal requires a fresh assessment/);
    const renewalEvidence=await service.linkEvidence(modelId,{attachmentId,threatId:high.id},owner);
    const renewed=await service.requestRiskAcceptance(high.id,{...request,renewalAssessment:{rationale:'Fresh assessment retains unreduced inherent risk',remediationStatus:'Remediation not complete; new bounded change window',evidenceId:renewalEvidence.id}},owner);
    assert.equal(renewed.renewalOf,exception.id);assert.equal(renewed.escalationRequired,true);
    await assert.rejects(service.decideRiskAcceptance(renewed.id,{decision:'APPROVED'},ciso),/escalation review/);
    await assert.rejects(governanceAdmin.escalateException(modelId,renewed.id,{reason:'Requester self-review'},owner),/authority/);
    await governanceAdmin.escalateException(modelId,renewed.id,{reason:'Independent escalation: exposure and remediation evidence reviewed'},architect);
    await service.decideRiskAcceptance(renewed.id,{decision:'APPROVED'},ciso);
    await assert.rejects(pgClient.query("UPDATE threat_model_exceptions SET renewal_rationale='tamper' WHERE id=$1",[renewed.id]),/immutable/);
  });
  await t.test('periodic review maintenance creates one revalidation draft and is replay safe',async () => {
    const created = await service.create({title:'Periodic screening fixture',serviceId:appId,criticality:'LOW',dataClassification:'INTERNAL'},owner);
    const periodicId = String(created.model!.id);
    await service.assessApplicability({threatModelId:periodicId,answers:Object.fromEntries(screeningRules.map(rule=>[rule.signal,false])),justification:'No security impact'},owner);
    await service.submit(periodicId,owner);
    await service.decideApproval(periodicId,{stage:'APPSEC',decision:'APPROVED'},reviewer);
    await service.decideApproval(periodicId,{stage:'SECURITY_ARCHITECTURE',decision:'APPROVED'},architect);
    await pgClient.query("UPDATE threat_models SET next_review_at=NOW()-INTERVAL '1 day' WHERE id=$1",[periodicId]);
    assert.equal((await service.releaseGate(periodicId,owner)).securityGate,'BLOCK');
    const first = await service.maintainGovernance(ciso);
    assert.ok(first.overdue>=1);
    const detail = await service.detail(periodicId,owner) as any;
    assert.equal(detail.model.status,'REVIEW_REQUIRED'); assert.equal(detail.revisions.length,2);
    assert.equal((await service.maintainGovernance(ciso)).overdue,0);
  });
  await t.test('authored threat changes preserve lineage and invalidate shared verification and stale risk acceptance',async()=>{
    const created=await service.create({title:'Content editing fixture',serviceId:appId,criticality:'LOW',dataClassification:'INTERNAL'},owner);
    const editModel=String(created.model!.id);
    await service.assessApplicability({threatModelId:editModel,answers:Object.fromEntries(screeningRules.map(rule=>[rule.signal,false])),justification:'Fixture'},owner);
    const a=await service.addThreat(editModel,{title:'Edit A',description:'Original',attackScenario:'Original scenario',categories:['SPOOFING'],inherentLikelihood:2,inherentImpact:2},owner);
    const b=await service.addThreat(editModel,{title:'Edit B',description:'Shared scope',attackScenario:'Other scenario',categories:['TAMPERING'],inherentLikelihood:2,inherentImpact:2},owner);
    assert.equal(a.lineageId,a.id);assert.equal(a.lineageOrigin,'NATIVE');assert.equal(a.contentVersion,1);
    const shared=await service.addControl(a.id,{title:'Shared authorization',description:'Both scenarios',controlType:'PREVENTIVE'},owner);
    await service.mapControlThreat(editModel,{controlId:shared.id,threatId:b.id,scopeVersion:1,action:'LINK',reason:'Shared enforcement'},owner);
    const companion=await service.addControl(a.id,{title:'Companion monitoring',description:'Monitor both assumptions',controlType:'DETECTIVE',requiredBeforeRelease:false},owner);
    const ev=await service.linkEvidence(editModel,{attachmentId,controlId:shared.id},owner);
    const pass=await service.recordVerification(shared.id,{controlScopeVersion:2,result:'PASS',verificationType:'API_SECURITY_TEST',testCase:'Both scenarios',expectedResult:'Denied',evidenceIds:[ev.id]},reviewer);
    for(const item of [a,b]){
      await service.calculateResidualRisk(item.id,{residualLikelihood:1,residualImpact:1,residualRiskRationale:'Test covers both'},reviewer);
      await service.transitionThreat(item.id,{status:'MITIGATING',reason:'Implemented'},owner);
      await service.transitionThreat(item.id,{status:'MITIGATED',reason:'Verified'},reviewer);
    }
    const request={reason:'Bounded fixture',businessJustification:'Business impact',compensatingControls:'Manual dual approval',remediationOwnerId:owner.id,remediationPlan:'Fix',remediationDeadline:new Date(Date.now()+86400000).toISOString(),expiresAt:new Date(Date.now()+2*86400000).toISOString()};
    const exception=await service.requestRiskAcceptance(a.id,request,owner);
    await service.decideRiskAcceptance(exception.id,{decision:'APPROVED'},reviewer);
    const pending=await service.requestRiskAcceptance(a.id,{...request,renewalAssessment:{rationale:'Fresh verified residual review',remediationStatus:'Remediation in progress',evidenceId:ev.id}},owner);
    const edit={...a,attackScenario:'Changed authorization assumptions',inherentLikelihood:3,inherentImpact:4,reason:'Expanded attacker capability'};
    await assert.rejects(service.updateThreat(a.id,edit,outsider),/restricted/);
    await assert.rejects(service.updateThreat(a.id,{...edit,affectedAssetId:'unknown-asset'},owner),/does not exist/);
    await assert.rejects(service.updateThreat(a.id,{...edit,affectedComponentId:component.id},owner),/threat revision/);
    await assert.rejects(service.updateThreat(a.id,{...edit,ownerId:'unknown-user'},owner),/active threat owner/);
    const edited=await service.updateThreat(a.id,edit,reviewer,{correlationId:'threat-edit-fixture'});
    assert.equal(edited.contentVersion,2);assert.equal(edited.lineageId,a.id);assert.equal(edited.status,'OPEN');assert.equal(edited.residualScore,undefined);
    const detail=await service.detail(editModel,owner) as any;
    assert.equal(detail.controls[0].scopeVersion,3);assert.equal(detail.controls[0].status,'VERIFICATION_REQUIRED');
    assert.equal(detail.controls.find((item:any)=>item.id===companion.id).status,'VERIFICATION_REQUIRED');
    const events=(await pgClient.query("SELECT correlation_id,payload FROM outbox_events WHERE topic='threat-control.verification.required' AND payload->>'threatModelId'=$1 AND payload->>'requestCorrelationId'='threat-edit-fixture'",[editModel])).rows;
    assert.equal(events.length,2);assert.equal(new Set(events.map(row=>row.correlation_id)).size,2);
    assert.equal(detail.threats.find((item:any)=>item.id===b.id).residualScore,undefined);
    assert.equal(detail.threats.find((item:any)=>item.id===b.id).status,'OPEN');
    assert.equal(detail.verifications.find((item:any)=>item.id===pass.id).result,'PASS');
    assert.equal(detail.exceptions.find((item:any)=>item.id===exception.id).status,'APPROVED');
    assert.equal(detail.exceptions.find((item:any)=>item.id===exception.id).threatContentVersion,1);
    assert.ok((await service.governanceReport(reviewer)).exceptions.stale>=1);
    await assert.rejects(service.transitionThreat(a.id,{status:'ACCEPTED',reason:'Old assessment'},reviewer),/current approved/);
    await assert.rejects(service.decideRiskAcceptance(pending.id,{decision:'APPROVED'},ciso),/fresh threat assessment/);
    await assert.rejects(pgClient.query("UPDATE threat_model_exceptions SET status='APPROVED' WHERE id=$1",[pending.id]),/fresh threat assessment/);
    await assert.rejects(pgClient.query('UPDATE threat_model_exceptions SET threat_content_version=2 WHERE id=$1',[exception.id]),/immutable/);
    await assert.rejects(service.recordVerification(shared.id,{controlScopeVersion:2,result:'PASS',verificationType:'API_SECURITY_TEST',testCase:'Stale',expectedResult:'Denied',evidenceIds:[ev.id]},reviewer),/changed|scope/);
    await assert.rejects(service.updateThreat(a.id,edit,reviewer),/changed by another/);
    const noop=await service.updateThreat(a.id,{...edited,reason:'No change'},reviewer);
    assert.equal(noop.contentVersion,2);
    assert.equal((await pgClient.query("SELECT count(*)::int AS n FROM threat_model_audit_events WHERE entity_id=$1 AND action='THREAT_UPDATED'",[a.id])).rows[0].n,1);
    const audit=(await pgClient.query("SELECT * FROM threat_model_audit_events WHERE entity_id=$1 AND action='THREAT_UPDATED'",[a.id])).rows[0];
    assert.equal(audit.old_value.content_version,1);assert.equal(audit.new_value.threat.content_version,2);assert.equal(audit.correlation_id,'threat-edit-fixture');
    assert.ok(audit.new_value.staleExceptions.includes(exception.id));
    const concurrent=await Promise.allSettled([service.updateThreat(a.id,{...edited,title:'Parallel A',reason:'Concurrent A'},reviewer),service.updateThreat(a.id,{...edited,title:'Parallel B',reason:'Concurrent B'},reviewer)]);
    assert.equal(concurrent.filter(result=>result.status==='fulfilled').length,1);
    await pgClient.query("UPDATE threats SET attack_scenario='Direct SQL content change' WHERE id=$1",[a.id]);
    const sqlState=(await pgClient.query('SELECT content_version FROM threats WHERE id=$1',[a.id])).rows[0];assert.equal(sqlState.content_version,4);
    assert.equal((await pgClient.query('SELECT scope_version FROM threat_controls WHERE id=$1',[shared.id])).rows[0].scope_version,5);
    await assert.rejects(pgClient.query('UPDATE threats SET previous_threat_id=$1 WHERE id=$2',[b.id,a.id]),/server-managed/);
    await assert.rejects(pgClient.query('UPDATE threat_lineage_members SET lineage_id=$1 WHERE threat_id=$2',[b.id,a.id]),/append-only/);
    await assert.rejects(pgClient.query(`INSERT INTO threats(id,revision_id,key,title,description,categories,attack_scenario,inherent_likelihood,inherent_impact,inherent_score,status,created_by_user_id,previous_threat_id)
      VALUES($1,$2,$1,'Invalid cross-model copy','Invalid','["SPOOFING"]','Invalid',1,1,1,'OPEN',$3,$4)`,[`cross-lineage-${suffix}`,created.revision.id,owner.id,threat.id]),/same model predecessor/);
    const raceThreat=(await service.detail(editModel,owner) as any).threats.find((item:any)=>item.id===a.id);
    const race=await Promise.allSettled([
      service.updateThreat(a.id,{...raceThreat,title:'Concurrent verification and edit',reason:'Reassess scope'},reviewer),
      service.recordVerification(shared.id,{controlScopeVersion:5,result:'PASS',verificationType:'API_SECURITY_TEST',testCase:'Concurrent scope',expectedResult:'Denied',evidenceIds:[ev.id]},postReviewer),
    ]);
    assert.equal(race[0].status,'fulfilled');
    if(race[1].status==='rejected')assert.match(String(race[1].reason),/scope|changed/);
    const afterRace=await service.detail(editModel,owner) as any;
    assert.equal(afterRace.controls[0].scopeVersion,6);assert.equal(afterRace.controls[0].status,'VERIFICATION_REQUIRED');
    assert.equal(afterRace.verifications.some((item:any)=>item.controlScopeVersion===6&&item.result==='PASS'),false);
    const fresh=await service.requestRiskAcceptance(a.id,{...request,renewalAssessment:{rationale:'Fresh expanded attacker assessment; no unverified reduction claimed',remediationStatus:'Expanded remediation pending',evidenceId:ev.id}},owner);assert.equal(fresh.threatContentVersion,5);
    await governanceAdmin.escalateException(editModel,fresh.id,{reason:'Independent expanded exposure review'},postReviewer);
    await service.decideRiskAcceptance(fresh.id,{decision:'APPROVED'},ciso);
    await service.transitionThreat(a.id,{status:'ACCEPTED',reason:'Fresh assessment'},reviewer);
    await service.submit(editModel,owner);
    const latest=(await service.detail(editModel,owner) as any).threats.find((item:any)=>item.id===a.id);
    await assert.rejects(service.updateThreat(a.id,{...latest,title:'Review mutation',reason:'Blocked'},owner),/immutable/);
    await assert.rejects(service.decideApproval(editModel,{stage:'APPSEC',decision:'APPROVED'},reviewer),/contributing author/);
  });
  await t.test('architecture edits enforce graph integrity, fresh evidence and immutable snapshots',async()=>{
    const created=await service.create({title:'Architecture fixture',serviceId:appId,releaseId:ticketId,criticality:'LOW',dataClassification:'INTERNAL'},owner);
    const mid=String(created.model!.id);const rid=String(created.revision.id);
    const nodeContext={exposure:'INTERNAL',authenticationMethod:'OIDC',privileges:'STANDARD',hosting:'ON_PREMISES',environment:'PRODUCTION'};
    const a=await service.addComponent(mid,{name:'Client',type:'MOBILE_APP',securityZone:'INTERNAL',...nodeContext},owner);
    const b=await service.addComponent(mid,{name:'API',type:'API',securityZone:'INTERNAL'},owner);
    const boundary=await service.addTrustBoundary(mid,{name:'External boundary',boundaryType:'NETWORK'},owner);
    const flowContext={authorizationContext:'Server-side object ownership',encryptionMechanism:'TLS',encryptionVersion:'1.3',integrityProtection:'BOTH',internetExposure:false,thirdPartyInvolvement:false,logging:'SECURITY_EVENTS',purpose:'Authorized request processing'};
    const flow=await service.addDataFlow(mid,{name:'Requests',sourceComponentId:a.id,destinationComponentId:b.id,protocol:'HTTPS',port:443,dataClassification:'INTERNAL',encryptionInTransit:true,...flowContext},owner);
    for(const [key,value] of Object.entries(flowContext))assert.equal(flow[key],value);
    for(const [key,value] of Object.entries(nodeContext))assert.equal(a[key],value);
    assert.equal(flow.crossesTrustBoundary,false);
    await service.addDataObject(mid,{name:'Request IDs',classification:'INTERNAL',ownerId:owner.id,retention:'Bank policy',allowedLocations:'Bank',encryptionRequirements:'TLS',flowId:flow.id},owner);
    const threatContext={methodology:'ABUSE_CASE',source:'MANUAL',assumptions:'Identity token validated upstream',confidentialityImpact:4,integrityImpact:3,availabilityImpact:2,securityProperties:['CONFIDENTIALITY','INTEGRITY']};
    const th=await service.addThreat(mid,{title:'Object access',description:'Unauthorized read',attackScenario:'Actor accesses another object',categories:['SPOOFING'],inherentLikelihood:2,inherentImpact:2,affectedComponentId:b.id,affectedDataFlowId:flow.id,...threatContext},owner);
    await analysis.addCase(mid,{threatId:th.id,contentVersion:th.contentVersion,title:'Ownership bypass',objective:'Read another customer object',assumptions:'Authenticated identity',methodology:'ABUSE_CASE',nodes:[{key:'root',parentKey:null,kind:'STEP',label:'Alter object identifier'}]},owner);
    const ctl=await service.addControl(th.id,{title:'Object authorization',description:'Authorize every read',controlType:'PREVENTIVE'},owner);
    await service.createRequirement(mid,{title:'Access enforcement',description:'Deny unauthorized access',ownerId:owner.id,verificationMethod:'API_SECURITY_TEST',threatIds:[th.id],controlIds:[ctl.id]},owner);
    const ev=await service.linkEvidence(mid,{attachmentId,controlId:ctl.id},owner);
    const verify=async()=>{const detail=await service.detail(mid,owner) as any;await service.recordVerification(ctl.id,{controlScopeVersion:detail.controls[0].scopeVersion,result:'PASS',verificationType:'API_SECURITY_TEST',testCase:'Current architecture',expectedResult:'403',evidenceIds:[ev.id]},postReviewer);await service.calculateResidualRisk(th.id,{residualLikelihood:1,residualImpact:1,residualRiskRationale:'Current evidence'},postReviewer);await service.transitionThreat(th.id,{status:'MITIGATING',reason:'Implemented'},owner);await service.transitionThreat(th.id,{status:'MITIGATED',reason:'Verified'},postReviewer);};
    await verify();await service.assessApplicability({threatModelId:mid,answers,justification:'Initial architecture'},owner);
    const baseline=(await service.governanceDetail(mid,owner)).revision.architecture_version;
    const request={reason:'Bounded risk',businessJustification:'Fixture impact',compensatingControls:'Manual review',remediationOwnerId:owner.id,remediationPlan:'Fix',remediationDeadline:new Date(Date.now()+86400000).toISOString(),expiresAt:new Date(Date.now()+2*86400000).toISOString()};
    const exception=await service.requestRiskAcceptance(th.id,request,owner);assert.equal(exception.architectureVersion,baseline);await service.decideRiskAcceptance(exception.id,{decision:'APPROVED'},postReviewer);
    const pending=await service.requestRiskAcceptance(th.id,{...request,renewalAssessment:{rationale:'Fresh verified architecture review',remediationStatus:'Remediation in progress',evidenceId:ev.id}},owner);
    const doc=await service.editArchitecture(mid,a.id,{...a,kind:'component',action:'UPDATE',name:'Documented client',reason:'Clarify name'},reviewer);
    assert.equal(doc.entity!.contentVersion,2);assert.equal((await service.governanceDetail(mid,owner)).revision.architecture_version,baseline);
    let detail=await service.detail(mid,owner) as any;assert.equal(detail.controls[0].status,'VERIFIED');assert.equal(detail.threats[0].status,'MITIGATED');
    assert.equal((await service.editArchitecture(mid,a.id,{...doc.entity,kind:'component',action:'UPDATE',reason:'No-op'},reviewer)).changed,false);
    await assert.rejects(service.editArchitecture(mid,a.id,{...a,kind:'component',action:'UPDATE',reason:'Stale'},owner),/changed by another/);
    const edit={...doc.entity,kind:'component',action:'UPDATE',securityZone:'INTERNET',reason:'External exposure'};
    await assert.rejects(service.editArchitecture(mid,a.id,edit,outsider),/restricted/);
    await assert.rejects(service.editArchitecture(mid,component.id,edit,owner),/not found/);
    await assert.rejects(service.editArchitecture(mid,a.id,edit,owner),/requires a trust boundary/);
    assert.equal((await service.governanceDetail(mid,owner)).revision.architecture_version,baseline);
    await assert.rejects(service.editArchitecture(mid,a.id,{kind:'component',action:'DELETE',contentVersion:2,reason:'Referenced'},owner),/Referenced architecture/);
    const linked=await service.editArchitecture(mid,flow.id,{...flow,kind:'flow',action:'UPDATE',trustBoundaryId:boundary.id,crossesTrustBoundary:false,reason:'Boundary'},reviewer,{correlationId:'architecture-fixture'});
    assert.equal(linked.entity!.crossesTrustBoundary,true);await service.editArchitecture(mid,a.id,edit,reviewer);
    detail=await service.detail(mid,owner) as any;assert.equal(detail.controls[0].status,'VERIFICATION_REQUIRED');assert.equal(detail.threats[0].status,'OPEN');assert.equal(detail.threats[0].residualScore,undefined);assert.equal(detail.verifications[0].result,'PASS');
    assert.equal(detail.exceptions.find((item:any)=>item.id===exception.id).status,'APPROVED');assert.equal((await service.governanceDetail(mid,owner)).revision.tier,null);
    await assert.rejects(service.submit(mid,owner),/screening is required/);await assert.rejects(service.decideRiskAcceptance(pending.id,{decision:'APPROVED'},ciso),/fresh architecture/);
    await assert.rejects(service.transitionThreat(th.id,{status:'ACCEPTED',reason:'Old architecture'},reviewer),/current approved/);
    await assert.rejects(pgClient.query('UPDATE threat_model_exceptions SET architecture_version=999 WHERE id=$1',[pending.id]),/immutable/);
    await assert.rejects(pgClient.query('UPDATE threat_model_revisions SET architecture_version=1 WHERE id=$1',[rid]),/server-managed/);
    await assert.rejects(pgClient.query('DELETE FROM threat_model_trust_boundaries WHERE id=$1',[boundary.id]),/Referenced architecture/);
    await assert.rejects(service.editArchitecture(mid,flow.id,{...linked.entity,kind:'flow',action:'UPDATE',destinationComponentId:component.id,reason:'Cross-model'},owner),/current revision/);
    await assert.rejects(service.editArchitecture(mid,flow.id,{...linked.entity,kind:'flow',action:'UPDATE',dataClassification:'HIGHLY_RESTRICTED_HR_LEGAL',reason:'Insufficient clearance'},owner),/restricted/);
    const edits=await Promise.allSettled([service.editArchitecture(mid,flow.id,{...linked.entity,kind:'flow',action:'UPDATE',protocol:'TLS',reason:'A'},reviewer),service.editArchitecture(mid,flow.id,{...linked.entity,kind:'flow',action:'UPDATE',protocol:'HTTP/2',reason:'B'},reviewer)]);assert.equal(edits.filter(result=>result.status==='fulfilled').length,1);
    const currentFlow=(await service.detail(mid,owner) as any).dataFlows[0];
    const raised=await service.editArchitecture(mid,flow.id,{...currentFlow,kind:'flow',action:'UPDATE',dataClassification:'CONFIDENTIAL_SECURITY_ONLY',reason:'Sensitive exchange'},owner);
    assert.equal(((await service.detail(mid,owner) as any).model).dataClassification,'CONFIDENTIAL_SECURITY_ONLY');
    await service.editArchitecture(mid,flow.id,{...raised.entity,kind:'flow',action:'UPDATE',dataClassification:'INTERNAL',reason:'Remove sensitive exchange'},owner);
    assert.equal(((await service.detail(mid,owner) as any).model).dataClassification,'CONFIDENTIAL_SECURITY_ONLY');
    const unused=await service.addComponent(mid,{name:'Unused draft node',type:'OTHER',securityZone:'INTERNAL'},owner);
    assert.equal((await service.editArchitecture(mid,unused.id,{kind:'component',action:'DELETE',contentVersion:unused.contentVersion,reason:'Draft mistake'},owner)).deleted,true);
    const deletion=(await pgClient.query("SELECT old_value,new_value FROM threat_model_audit_events WHERE entity_id=$1 AND action='COMPONENT_REMOVED'",[unused.id])).rows[0];assert.equal(deletion.old_value.name,'Unused draft node');assert.equal(deletion.new_value.entity,null);
    const dataContext=await service.governanceDetail(mid,owner);const priorVersion=dataContext.revision.architecture_version;
    await service.addDataObject(mid,{dataObjectId:dataContext.dataObjects[0].id,componentId:a.id},owner);
    assert.equal((await service.governanceDetail(mid,owner)).revision.architecture_version,priorVersion+1);
    assert.ok((await pgClient.query("SELECT 1 FROM outbox_events WHERE topic='threat-control.verification.required' AND payload->>'threatModelId'=$1 AND payload->>'architectureVersion'=$2",[mid,String(priorVersion+1)])).rowCount);
    const screening=await service.assessApplicability({threatModelId:mid,answers:Object.fromEntries(screeningRules.map(rule=>[rule.signal,false])),justification:'Persisted boundary must win'},owner);assert.ok(screening.tier>=2);
    await verify();await completeCoverage(mid);await service.submit(mid,owner);await assert.rejects(service.decideApproval(mid,{stage:'APPSEC',decision:'APPROVED'},reviewer),/contributing author/);
    await service.decideApproval(mid,{stage:'APPSEC',decision:'APPROVED'},postReviewer);await service.decideApproval(mid,{stage:'SECURITY_ARCHITECTURE',decision:'APPROVED'},architect);
    assert.equal((await service.releaseGate(mid,owner)).securityGate,'PASS');const report=await service.exportSnapshot(mid,rid,owner);assert.ok(report.snapshot.revision[0].architecture_version>baseline);
    await assert.rejects(service.editArchitecture(mid,b.id,{...b,kind:'component',action:'UPDATE',reason:'Approved edit'},owner),/immutable/);await assert.rejects(pgClient.query("UPDATE threat_model_data_flows SET protocol='HTTP' WHERE id=$1",[flow.id]),/immutable/);
    await service.createRevision(mid,{changeReason:'Next revision'},owner);const copied=await service.detail(mid,owner) as any;assert.equal(copied.dataFlows[0].crossesTrustBoundary,true);assert.equal(copied.dataFlows[0].encryptionInTransit,true);assert.equal(copied.verifications.length,0);assert.equal((await service.exportSnapshot(mid,rid,owner)).sha256,report.sha256);
    for(const [key,value] of Object.entries(flowContext))assert.equal(copied.dataFlows[0][key],value,`Copied flow ${key}`);
    const copiedClient=copied.components.find((node:any)=>node.type==='MOBILE_APP');
    for(const [key,value] of Object.entries(nodeContext))assert.equal(copiedClient[key],value,`Copied node ${key}`);
    for(const [key,value] of Object.entries(threatContext))assert.deepEqual(copied.threats[0][key],value,`Copied threat context ${key}`);
    const copiedAnalysis=await analysis.list(mid,{},owner);assert.equal(copiedAnalysis.cases.length,1);assert.equal(copiedAnalysis.cases[0].nodes[0].label,'Alter object identifier');assert.equal(copiedAnalysis.cases[0].threat_id,copied.threats[0].id);
    assert.equal(report.snapshot.attackCases.length,1);assert.equal(report.snapshot.attackNodes.length,1);
    await assert.rejects(pgClient.query("UPDATE threat_model_data_flows SET logging='NONE' WHERE id=$1",[flow.id]),/immutable/);
    await assert.rejects(pgClient.query("UPDATE threat_model_components SET exposure='INTERNET' WHERE id=$1",[a.id]),/immutable/);
  });
  await t.test('suggestions require persisted analyst disposition and attack analysis invalidates scoped verification',async()=>{
    const created=await service.create({title:'Analysis fixture',serviceId:appId,criticality:'LOW',dataClassification:'INTERNAL'},owner);const mid=String(created.model!.id);const rid=String(created.revision.id);
    const node=await service.addComponent(mid,{name:'API',type:'API',securityZone:'INTERNAL'},owner);
    const generated=await analysis.suggest(mid,{componentId:node.id},owner);assert.equal(generated.created,6);assert.equal((await analysis.suggest(mid,{componentId:node.id},owner)).created,0);
    assert.equal((await service.detail(mid,owner) as any).threats.length,0);
    await assert.rejects(analysis.list(mid,{},outsider),/restricted/);
    await assert.rejects(analysis.decide(mid,generated.suggestionIds[0],{decision:'ACCEPTED',reason:'Owner override'},owner),/authority/);
    await service.assessApplicability({threatModelId:mid,answers,justification:'Review candidates'},owner);
    await assert.rejects(service.submit(mid,owner),/Analyst disposition/);
    const accepted=await analysis.decide(mid,generated.suggestionIds[0],{decision:'ACCEPTED',reason:'Applicable identity threat'},reviewer);
    await assert.rejects(analysis.decide(mid,generated.suggestionIds[0],{decision:'ACCEPTED',reason:'Replay'},reviewer),/immutable analyst disposition/);
    await analysis.decide(mid,generated.suggestionIds[1],{decision:'DUPLICATE',reason:'Same attack scope',threatId:accepted.threatId},reviewer);
    await assert.rejects(analysis.decide(mid,generated.suggestionIds[2],{decision:'DUPLICATE',reason:'Foreign',threatId:threat.id},reviewer),/this revision/);
    const aiInput={source:'AI_ASSISTED',provider:'Fixture supplied provider',modelVersion:'fixture-v1',provenanceReference:'external-run-fixture',content:{title:'AI candidate',description:'Unverified hypothesis',attackScenario:'Attempt object access',categories:['INFORMATION_DISCLOSURE'],inherentLikelihood:2,inherentImpact:2}};
    const imported=await analysis.importSuggestion(mid,aiInput,owner);
    const modified=await analysis.decide(mid,imported.id,{decision:'MODIFIED',reason:'Human assessed severity',content:{...aiInput.content,title:'Assessed access scenario',inherentImpact:3}},reviewer);
    const inspected=await analysis.list(mid,{},owner);assert.equal(inspected.suggestions.find(item=>item.id===imported.id).provenance_kind,'USER_SUPPLIED');
    const current=(await service.detail(mid,owner) as any).threats.find((item:any)=>item.id===modified.threatId);assert.equal(current.source,'AI_ASSISTED');assert.equal(current.status,'OPEN');assert.equal(current.inherentScore,6);
    const control=await service.addControl(current.id,{title:'Ownership check',description:'Verify ownership',controlType:'PREVENTIVE'},owner);const ev=await service.linkEvidence(mid,{attachmentId,controlId:control.id},owner);
    await service.recordVerification(control.id,{controlScopeVersion:control.scopeVersion,result:'PASS',verificationType:'API_SECURITY_TEST',testCase:'Ownership',expectedResult:'403',evidenceIds:[ev.id]},postReviewer);
    const attackCase={threatId:current.id,contentVersion:current.contentVersion,title:'Read another object',objective:'Exfiltrate records',assumptions:'Authenticated attacker',methodology:'ATTACK_TREE',nodes:[{key:'root',parentKey:null,kind:'OR',label:'Access object'},{key:'guess',parentKey:'root',kind:'STEP',label:'Guess identifier'},{key:'leak',parentKey:'root',kind:'STEP',label:'Obtain identifier from logs'}]};
    assert.equal(attackCaseSchema.safeParse({...attackCase,nodes:[{key:'root',parentKey:'root',kind:'STEP',label:'cycle'}]}).success,false);
    const record=await analysis.addCase(mid,attackCase,owner);const changed=await service.detail(mid,owner) as any;assert.equal(changed.controls[0].status,'VERIFICATION_REQUIRED');assert.equal(changed.verifications[0].result,'PASS');
    await assert.rejects(analysis.addCase(mid,attackCase,owner),/changed by another/);
    assert.equal((await analysis.list(mid,{},owner)).cases[0].nodes.length,3);
    await assert.rejects(pgClient.query("UPDATE threat_attack_nodes SET label='tamper' WHERE case_id=$1",[record.id]),/append-only/);
    await assert.rejects(pgClient.transaction(async client=>{await client.query("INSERT INTO threat_attack_cases(id,revision_id,threat_id,title,objective,assumptions,methodology,created_by) VALUES($1,$2,$3,'Invalid','Invalid','Invalid','ATTACK_TREE',$4)",[`invalid-case-${suffix}`,rid,current.id,owner.id]);}),/rooted tree/);
    await service.editArchitecture(mid,node.id,{...node,kind:'component',action:'UPDATE',reason:'Changed exposure',exposure:'INTERNET'},owner);
    await assert.rejects(analysis.decide(mid,generated.suggestionIds[2],{decision:'ACCEPTED',reason:'Stale'},reviewer),/fresh architecture/);
    assert.equal((await pgClient.query('SELECT count(*)::int AS n FROM threats WHERE revision_id=$1',[rid])).rows[0].n,2);
    for(const sid of generated.suggestionIds.slice(2))await analysis.decide(mid,sid,{decision:'REJECTED',reason:'Reassess changed architecture'},reviewer);
    await assert.rejects(pgClient.query("DELETE FROM threat_suggestion_dispositions WHERE suggestion_id=$1",[generated.suggestionIds[0]]),/append-only/);
  });
  await t.test('canonical finding changes block release before scheduler delivery and require fresh assessment',async()=>{
    const ciId=`tmtest-ci-${suffix}`;const typeId=`tmtest-type-${suffix}`;const findingId=`tmtest-finding-${suffix}`;
    await pgClient.query('INSERT INTO cmdb_ci_types(id,name) VALUES($1,$1)',[typeId]);
    await pgClient.query("INSERT INTO configuration_items(id,ci_number,name,type_id,status,lifecycle_status,environment,criticality,source,discovery_status,owner_user_id,asset_key,lifecycle_state) VALUES($1,$1,'Fixture CI',$2,'ACTIVE','IN_USE','PRODUCTION','LOW','MANUAL','VERIFIED',$3,$1,'ACTIVE')",[ciId,typeId,owner.id]);
    await pgClient.query("INSERT INTO cmdb_security_findings(id,asset_id,finding_type,severity,state,title,detection_key,first_observed_at,last_observed_at,resolved_at) VALUES($1,$2,'CORTEX_UNPROTECTED','HIGH','RESOLVED','Protection restored',$1,NOW(),NOW(),NOW())",[findingId,ciId]);
    const created=await service.create({title:'Finding correlation fixture',serviceId:appId,releaseId:ticketId,criticality:'LOW',dataClassification:'INTERNAL'},owner);const mid=String(created.model!.id);const rid=String(created.revision.id);
    const node=await service.addComponent(mid,{name:'Protected service',type:'SERVICE',securityZone:'INTERNAL',assetId:ciId},owner);
    const th=await service.addThreat(mid,{title:'Endpoint takeover',description:'Attack protection assumption',attackScenario:'Attacker disables endpoint protection',categories:['SPOOFING'],inherentLikelihood:2,inherentImpact:2,affectedComponentId:node.id},owner);
    const ctl=await service.addControl(th.id,{title:'Endpoint defense',description:'Verify defense controls',controlType:'PREVENTIVE'},owner);
    const link=await service.linkFinding(mid,{threatId:th.id,controlId:ctl.id,cmdbFindingId:findingId,assumption:'The endpoint remains protected'},owner);
    await assert.rejects(service.linkFinding(mid,{threatId:th.id,controlId:ctl.id,cmdbFindingId:findingId,assumption:'Duplicate'},owner),/duplicate key/);
    await assert.rejects(service.findingLinks(mid,outsider),/restricted/);
    const ev=await service.linkEvidence(mid,{attachmentId,controlId:ctl.id},owner);
    const verify=async(controlId:string,evidenceId:string)=>{const current=(await service.detail(mid,owner) as any).controls.find((item:any)=>item.id===controlId);await service.recordVerification(controlId,{controlScopeVersion:current.scopeVersion,result:'PASS',verificationType:'CONFIGURATION_REVIEW',testCase:'Verify endpoint protection',expectedResult:'Protected',evidenceIds:[evidenceId]},postReviewer);};
    await verify(ctl.id,ev.id);
    await service.calculateResidualRisk(th.id,{residualLikelihood:1,residualImpact:1,residualRiskRationale:'Observed controls'},postReviewer);await service.transitionThreat(th.id,{status:'MITIGATING',reason:'Implemented'},owner);await service.transitionThreat(th.id,{status:'MITIGATED',reason:'Verified'},postReviewer);
    await service.assessApplicability({threatModelId:mid,answers,justification:'Internal endpoint scope'},owner);await service.submit(mid,owner);await service.decideApproval(mid,{stage:'APPSEC',decision:'APPROVED'},reviewer);await service.decideApproval(mid,{stage:'SECURITY_ARCHITECTURE',decision:'APPROVED'},architect);
    assert.equal((await service.releaseGate(mid,owner)).securityGate,'PASS');const original=await service.exportSnapshot(mid,rid,owner);
    await pgClient.query("UPDATE cmdb_security_findings SET last_observed_at=last_observed_at+INTERVAL '1 second' WHERE id=$1",[findingId]);assert.equal((await service.releaseGate(mid,owner)).securityGate,'PASS');
    await pgClient.query("UPDATE cmdb_security_findings SET state='OPEN',resolved_at=NULL WHERE id=$1",[findingId]);assert.equal((await service.releaseGate(mid,owner)).securityGate,'BLOCK');
    await Promise.all([service.reconcileFindingChanges(admin),service.reconcileFindingChanges(admin)]);
    const copied=await service.detail(mid,owner) as any;assert.equal(copied.revisions.length,2);assert.equal(copied.model.status,'REVIEW_REQUIRED');assert.equal(copied.controls[0].status,'VERIFICATION_REQUIRED');assert.equal((await service.exportSnapshot(mid,rid,owner)).sha256,original.sha256);
    const currentLink=(await service.findingLinks(mid,owner))[0];const copiedEvidence=await service.linkEvidence(mid,{attachmentId,controlId:copied.controls[0].id},owner);
    await assert.rejects(verify(copied.controls[0].id,copiedEvidence.id),/contradicts/);
    await pgClient.query("UPDATE cmdb_security_findings SET state='RESOLVED',resolved_at=NOW() WHERE id=$1",[findingId]);
    await assert.rejects(service.assessFinding(mid,currentLink.id,{fingerprint:currentLink.current_fingerprint,reason:'Stale read'},postReviewer),/fresh assessment/);
    const refreshed=(await service.findingLinks(mid,owner))[0];await assert.rejects(service.assessFinding(mid,refreshed.id,{fingerprint:refreshed.current_fingerprint,reason:'Owner assessment'},owner),/authority/);
    await service.assessFinding(mid,refreshed.id,{fingerprint:refreshed.current_fingerprint,reason:'Current source state reviewed'},postReviewer);await verify(copied.controls[0].id,copiedEvidence.id);
    await assert.rejects(pgClient.query("UPDATE threat_finding_links SET assumption='tamper' WHERE id=$1",[link.id]),/append-only/);
    // A persisted quarantine wins over a stale in-process CLEAN projection.
    await pgClient.query("UPDATE ticket_attachments SET source_payload=jsonb_set(source_payload,'{virusScanStatus}','\"QUARANTINED\"') WHERE id=$1",[attachmentId]);
    await assert.rejects(verify(copied.controls[0].id,copiedEvidence.id),/clean retained evidence/);
    await pgClient.query("UPDATE ticket_attachments SET source_payload=jsonb_set(source_payload,'{virusScanStatus}','\"CLEAN\"') WHERE id=$1",[attachmentId]);
  });
  await t.test('structured architecture context is material, database constrained and cannot weaken screening floors',async()=>{
    const created=await service.create({title:'Architecture context fixture',serviceId:appId,criticality:'LOW',dataClassification:'INTERNAL'},owner);
    const mid=String(created.model!.id);const rid=String(created.revision.id);
    let node=await service.addComponent(mid,{name:'Gateway',type:'API_GATEWAY',securityZone:'INTERNAL'},owner);
    const destination=await service.addComponent(mid,{name:'Service',type:'MICROSERVICE',securityZone:'INTERNAL'},owner);
    let flow=await service.addDataFlow(mid,{name:'Requests',sourceComponentId:node.id,destinationComponentId:destination.id,dataClassification:'INTERNAL',encryptionInTransit:true},owner);
    const th=await service.addThreat(mid,{title:'Access',description:'Unauthorized access',attackScenario:'Actor bypasses ownership',categories:['SPOOFING'],inherentLikelihood:2,inherentImpact:2},owner);
    const ctl=await service.addControl(th.id,{title:'Authorize',description:'Object ownership',controlType:'PREVENTIVE'},owner);
    const ev=await service.linkEvidence(mid,{attachmentId,controlId:ctl.id},owner);
    await service.recordVerification(ctl.id,{controlScopeVersion:ctl.scopeVersion,result:'PASS',verificationType:'API_SECURITY_TEST',testCase:'Access',expectedResult:'403',evidenceIds:[ev.id]},postReviewer);
    const allFalse=Object.fromEntries(screeningRules.map(rule=>[rule.signal,false]));
    await service.assessApplicability({threatModelId:mid,answers:allFalse,justification:'Before context'},owner);
    const material=async(kind:'component'|'flow',entity:any,field:string,value:any)=>{
      const before=(await service.governanceDetail(mid,owner)).revision.architecture_version;
      const changed=await service.editArchitecture(mid,entity.id,{...entity,[field]:value,kind,action:'UPDATE',reason:`Assess ${field}`},owner);
      assert.equal(changed.entity![field],value);assert.equal(changed.entity!.contentVersion,entity.contentVersion+1);
      const revision=(await service.governanceDetail(mid,owner)).revision;assert.equal(revision.architecture_version,before+1);assert.equal(revision.tier,null);
      return changed.entity!;
    };
    for(const [key,value] of Object.entries({exposure:'INTERNET',authenticationMethod:'mTLS',privileges:'PRIVILEGED',hosting:'PUBLIC_CLOUD',environment:'PRODUCTION'}))node=await material('component',node,key,value);
    for(const [key,value] of Object.entries({authorizationContext:'Object ownership',encryptionMechanism:'TLS',encryptionVersion:'1.3',integrityProtection:'MESSAGE',internetExposure:false,thirdPartyInvolvement:true,logging:'SECURITY_EVENTS',purpose:'Requests'}))flow=await material('flow',flow,key,value);
    const detail=await service.detail(mid,owner) as any;assert.equal(detail.controls[0].status,'VERIFICATION_REQUIRED');assert.equal(detail.verifications[0].result,'PASS');assert.ok(detail.controls[0].scopeVersion>detail.verifications[0].controlScopeVersion);
    const assessment=await service.assessApplicability({threatModelId:mid,answers:allFalse,justification:'Persisted architecture is authoritative'},owner);
    assert.equal(assessment.tier,3);for(const signal of ['internetExposed','privilegedCapability','cloudDeployment','thirdPartyIntegration'])assert.equal(assessment.answers[signal],true);
    const audit=(await pgClient.query("SELECT old_value,new_value FROM threat_model_audit_events WHERE entity_id=$1 AND action='FLOW_UPDATED' ORDER BY occurred_at DESC LIMIT 1",[flow.id])).rows[0];
    // Every context edit shares the existing full-value, hash-chained architecture audit.
    assert.equal(audit.old_value.purpose,null);assert.equal(audit.new_value.entity.purpose,'Requests');assert.equal(audit.new_value.material,true);
    for(const type of ['CLIENT','WEB_APP','CACHE','FILE_STORE','OBJECT_STORAGE','HSM_KMS','IDENTITY_PROVIDER'])await service.addComponent(mid,{name:type,type,securityZone:'INTERNAL'},owner);
    const identity=await service.assessApplicability({threatModelId:mid,answers:allFalse,justification:'Key and identity capabilities'},owner);assert.equal(identity.answers.iamPamRelated,true);assert.equal(identity.answers.cryptography,true);assert.equal(identity.answers.secretsHandling,true);
    await assert.rejects(pgClient.query("UPDATE threat_model_components SET exposure='GUARANTEED_SAFE' WHERE id=$1",[node.id]),/check constraint/);
    await assert.rejects(pgClient.query("UPDATE threat_model_data_flows SET encryption_in_transit=false WHERE id=$1",[flow.id]),/threat_flow_encryption_context/);
    await assert.rejects(pgClient.query("UPDATE threat_model_data_flows SET logging='GUARANTEED_SAFE' WHERE id=$1",[flow.id]),/check constraint/);
    assert.equal((await pgClient.query('SELECT encryption_in_transit FROM threat_model_data_flows WHERE id=$1',[flow.id])).rows[0].encryption_in_transit,true);
  });
  await t.test('catalog versions are independently published and shared implementations retain exact verification scope',async()=>{
    const definition={code:`AUTHZ-${suffix.toUpperCase()}`,baseVersion:0,title:'Object authorization',description:'Authorize every protected request',controlFunction:'PREVENTIVE',verificationGuidance:'Exercise positive and negative authorization on every mapped threat'};
    await assert.rejects(catalog.create(definition,owner),/authority/);
    const version=await catalog.create(definition,reviewer);
    await assert.rejects(catalog.create(definition,reviewer),/changed by another/);
    await assert.rejects(catalog.decide(version.id,{decision:'PUBLISHED',reason:'Self publication'},reviewer),/cannot approve/);
    await assert.rejects(pgClient.query("INSERT INTO threat_control_catalog_decisions(id,catalog_version_id,decision,reason,decided_by) VALUES($1,$2,'RETIRED','Invalid skip',$3)",[`invalid-${suffix}`,version.id,architect.id]),/Invalid catalog/);
    await catalog.decide(version.id,{decision:'PUBLISHED',reason:'Independent guidance review'},architect);
    const centralAudit=(await pgClient.query("SELECT action,source_payload FROM audit_events WHERE entity_id=$1 ORDER BY timestamp",[version.id])).rows;
    assert.deepEqual(centralAudit.map(row=>row.action),['THREAT_CONTROL_CATALOG_CREATED','THREAT_CONTROL_CATALOG_PUBLISHED']);
    assert.match(centralAudit[0].source_payload.sha256,/^[a-f0-9]{64}$/);
    await assert.rejects(pgClient.query("UPDATE threat_control_catalog_versions SET title='tamper' WHERE id=$1",[version.id]),/append-only/);
    const newer=await catalog.create({...definition,baseVersion:1,description:'Updated guidance'},reviewer);
    const concurrent=await Promise.allSettled([catalog.create({...definition,baseVersion:2},reviewer),catalog.create({...definition,baseVersion:2},reviewer)]);
    assert.equal(concurrent.filter(result=>result.status==='fulfilled').length,1);
    const created=await service.create({title:'Shared controls fixture',serviceId:appId,criticality:'LOW',dataClassification:'INTERNAL',scopeSummary:'API access',architectureSummary:'Shared API gateway',assumptions:'Authenticated actor',securityObjectives:'Only authorized data access'},owner);
    const sharedModel=String(created.model!.id);
    await service.assessApplicability({threatModelId:sharedModel,answers,justification:'Internal authorization scope'},owner);
    await service.addComponent(sharedModel,{name:'Gateway',type:'API',securityZone:'INTERNAL'},owner);
    const scenario={description:'Unauthorized object read',attackScenario:'Another user attempts object access',categories:['SPOOFING'],inherentLikelihood:2,inherentImpact:2};
    const a=await service.addThreat(sharedModel,{...scenario,title:'Read path A'},owner);
    const b=await service.addThreat(sharedModel,{...scenario,title:'Read path B'},owner);
    await assert.rejects(service.addControl(a.id,{catalogVersionId:newer.id,implementationKey:'gateway'},owner),/published/);
    const shared=await service.addControl(a.id,{catalogVersionId:version.id,implementationKey:'gateway'},owner);
    assert.deepEqual(shared.threatIds,[a.id]);assert.equal(shared.scopeVersion,1);
    await assert.rejects(service.addControl(b.id,{catalogVersionId:version.id,implementationKey:'GATEWAY'},owner),/Duplicate/);
    const evidence=await service.linkEvidence(sharedModel,{attachmentId,controlId:shared.id},owner);
    const verification={result:'PASS',verificationType:'API_SECURITY_TEST',testCase:'Exercise authorization for every mapped threat',expectedResult:'Only authorized reads succeed',evidenceIds:[evidence.id]};
    await service.recordVerification(shared.id,verification,reviewer);
    await service.calculateResidualRisk(a.id,{residualLikelihood:1,residualImpact:1,residualRiskRationale:'Verified read protection'},reviewer);
    await service.transitionThreat(a.id,{status:'MITIGATING',reason:'Implemented'},owner);
    await service.transitionThreat(a.id,{status:'MITIGATED',reason:'Verified'},reviewer);
    await assert.rejects(service.mapControlThreat(modelId,{controlId:shared.id,threatId:b.id,scopeVersion:1,reason:'Cross-model'},owner),/current revision/);
    await assert.rejects(service.mapControlThreat(sharedModel,{controlId:shared.id,threatId:b.id,scopeVersion:1,reason:'Outsider'},outsider),/restricted/);
    const linked=await service.mapControlThreat(sharedModel,{controlId:shared.id,threatId:b.id,scopeVersion:1,reason:'Same gateway implementation covers both paths'},owner);
    assert.equal(linked.scopeVersion,2);assert.equal(linked.status,'VERIFICATION_REQUIRED');assert.equal(linked.threatIds.length,2);
    assert.equal((await pgClient.query('SELECT residual_score,status FROM threats WHERE id=$1',[a.id])).rows[0].residual_score,null);
    await assert.rejects(service.recordVerification(shared.id,{...verification,controlScopeVersion:1},reviewer),/scope is no longer current/);
    await assert.rejects(service.calculateResidualRisk(b.id,{residualLikelihood:1,residualImpact:1,residualRiskRationale:'Reuse old PASS'},reviewer),/current independent verification/);
    await assert.rejects(service.mapControlThreat(sharedModel,{controlId:shared.id,threatId:b.id,scopeVersion:1,reason:'Stale request'},owner),/changed by another/);
    const unmapped=await service.mapControlThreat(sharedModel,{controlId:shared.id,threatId:b.id,scopeVersion:2,action:'UNLINK',reason:'Correct draft scope'},owner);
    assert.equal(unmapped.scopeVersion,3);
    const relinked=await service.mapControlThreat(sharedModel,{controlId:shared.id,threatId:b.id,scopeVersion:3,reason:'Confirm both paths'},owner);
    assert.equal(relinked.scopeVersion,4);
    await service.createRequirement(sharedModel,{title:'Authorize path B',description:'Explicit deny across tenants',ownerId:owner.id,verificationMethod:'API_SECURITY_TEST',threatIds:[b.id],controlIds:[shared.id]},owner);
    await assert.rejects(service.mapControlThreat(sharedModel,{controlId:shared.id,threatId:b.id,scopeVersion:4,action:'UNLINK',reason:'Break requirement'},owner),/requirement mapping/);
    await service.recordVerification(shared.id,{...verification,controlScopeVersion:4},reviewer);
    for(const threat of [a,b]){
      await service.calculateResidualRisk(threat.id,{residualLikelihood:1,residualImpact:1,residualRiskRationale:'Current tests cover both paths'},reviewer);
      if(threat.id===b.id)await service.transitionThreat(threat.id,{status:'MITIGATING',reason:'Implemented'},owner);
      await service.transitionThreat(threat.id,{status:'MITIGATED',reason:'Verified current scope'},reviewer);
    }
    await service.assessApplicability({threatModelId:sharedModel,answers,justification:'Re-screen gateway'},owner);
    await service.submit(sharedModel,owner);
    await service.decideApproval(sharedModel,{stage:'APPSEC',decision:'APPROVED'},reviewer);
    await service.decideApproval(sharedModel,{stage:'SECURITY_ARCHITECTURE',decision:'APPROVED'},architect);
    assert.equal((await service.releaseGate(sharedModel,owner)).securityGate,'PASS');
    const snapshot=await service.exportSnapshot(sharedModel,String(created.revision.id),owner);
    assert.equal(snapshot.snapshot.controlMappings.length,2);assert.equal(snapshot.snapshot.controlDefinitions[0].id,version.id);
    await assert.rejects(pgClient.query('DELETE FROM threat_control_threats WHERE control_id=$1 AND threat_id=$2',[shared.id,b.id]),/immutable/);
    await catalog.decide(version.id,{decision:'RETIRED',reason:'Use revised guidance for new installations'},architect);
    assert.equal((await service.releaseGate(sharedModel,owner)).securityGate,'PASS');
    await service.createRevision(sharedModel,{changeReason:'Material change, preserve implementation scope'},owner);
    const copied=await service.detail(sharedModel,owner) as any;
    assert.equal(copied.controls.length,1);assert.equal(copied.controls[0].threatIds.length,2);assert.equal(copied.controls[0].catalogVersionId,version.id);assert.equal(copied.verifications.length,0);
    assert.equal((await service.governanceDetail(sharedModel,owner)).requirements[0].control_ids[0],copied.controls[0].id);
    await assert.rejects(service.addControl(copied.threats[0].id,{catalogVersionId:version.id,implementationKey:'new-installation'},owner),/published/);
    await assert.rejects(service.mapControlThreat(sharedModel,{controlId:copied.controls[0].id,threatId:a.id,scopeVersion:copied.controls[0].scopeVersion,reason:'Historical scope'},owner),/current revision/);
  });
  await t.test('owning one linked object never grants access to a different scope record',async () => {
    const foreignApp=`foreign-app-${suffix}`;
    await pgClient.query(`INSERT INTO bank_applications(id,code,name,tier,architecture_type,technical_owner_id,business_owner_id) VALUES($1,$1,'Foreign fixture','LOW','MONOLITH',$2,$2)`,[foreignApp,outsider.id]);
    db.data.applications.push({id:foreignApp,name:'Foreign fixture',technicalOwnerId:outsider.id,businessOwnerId:outsider.id} as any);
    await assert.rejects(service.create({title:'Cross-scope bypass',serviceId:foreignApp,releaseId:ticketId,dataClassification:'INTERNAL'},owner),/every linked scope/);
    await assert.rejects(service.create({title:'Admin scope bypass',serviceId:appId,dataClassification:'INTERNAL'},admin),/every linked scope/);
  });
  await t.test('emergency authorization, evidenced execution, independent review and approved revalidation are persistent',async () => {
    await pgClient.query(`INSERT INTO orchestration_business_calendars(id,name,timezone,workdays,business_start,business_end,holidays,is_24x7) VALUES('calendar-bank-baku','Bank calendar','Asia/Baku','[1,2,3,4,5]','09:00','18:00','[]',false) ON CONFLICT(id) DO NOTHING`);
    const created = await service.create({title:'Emergency fixture',serviceId:appId,criticality:'LOW',dataClassification:'INTERNAL'},owner);
    const emergencyModel = String(created.model!.id);
    await pgClient.query('UPDATE threat_models SET change_id=$1 WHERE id=$2',[ticketId,emergencyModel]);
    const approve = async (firstReviewer=reviewer) => {
      await service.assessApplicability({threatModelId:emergencyModel,answers:Object.fromEntries(screeningRules.map(rule=>[rule.signal,false])),justification:'Fixture minimum-impact screening'},owner);
      await service.submit(emergencyModel,owner);
      if(firstReviewer!==reviewer) await assert.rejects(service.decideApproval(emergencyModel,{stage:'APPSEC',decision:'APPROVED'},reviewer),/Author or owner cannot approve/);
      await service.decideApproval(emergencyModel,{stage:'APPSEC',decision:'APPROVED'},firstReviewer);
      await service.decideApproval(emergencyModel,{stage:'SECURITY_ARCHITECTURE',decision:'APPROVED'},architect);
    };
    await approve();
    const assessment = {changeId:ticketId,reason:'Urgent rollback',securityImpact:'No new data or identity boundary; preserve authorization',compensatingControls:'Security monitoring',rollbackPlan:'Restore last approved image'};
    await assert.rejects(service.requestEmergencyChange(emergencyModel,assessment,outsider),/restricted/);
    await assert.rejects(service.requestEmergencyChange(emergencyModel,{...assessment,changeId:'foreign'},owner),/linked/);
    const revoked = await service.requestEmergencyChange(emergencyModel,assessment,owner);
    await assert.rejects(service.requestEmergencyChange(emergencyModel,assessment,owner),/duplicate/);
    assert.equal((await service.releaseGate(emergencyModel,owner)).securityGate,'BLOCK');
    await assert.rejects(service.decideEmergencyChange(emergencyModel,revoked.id,{decision:'APPROVED',reason:'Self approve'}, {...owner,roles:['CISO']}),/cannot approve/);
    await assert.rejects(service.decideEmergencyChange(emergencyModel,revoked.id,{decision:'APPROVED',reason:'Not CISO'},reviewer),/CISO/);
    await service.decideEmergencyChange(emergencyModel,revoked.id,{decision:'APPROVED',reason:'Independent assessment'},ciso);
    await assert.rejects(service.authorizeRelease(emergencyModel,ticketId,reviewer),/explicitly bound/);
    const revokedAuthorization = await service.authorizeRelease(emergencyModel,ticketId,reviewer,revoked.id);
    await service.decideEmergencyChange(emergencyModel,revoked.id,{decision:'REVOKED',reason:'Changed deployment window'},ciso);
    await assert.rejects(service.consumeReleaseAuthorization(emergencyModel,{releaseId:ticketId,authorization:revokedAuthorization.authorization,idempotencyKey:'revoked'},reviewer),/emergency authorization/);
    await assert.rejects(service.decideEmergencyChange(emergencyModel,revoked.id,{decision:'APPROVED',reason:'Renew'},ciso),/new assessment/);
    const emergency = await service.requestEmergencyChange(emergencyModel,assessment,owner);
    await service.decideEmergencyChange(emergencyModel,emergency.id,{decision:'APPROVED',reason:'Independent assessment'},ciso);
    const auth = await service.authorizeRelease(emergencyModel,ticketId,reviewer,emergency.id);
    const consume = await service.consumeReleaseAuthorization(emergencyModel,{releaseId:ticketId,authorization:auth.authorization,idempotencyKey:`emergency-${suffix}`},reviewer);
    const deployment = {authorizationId:consume.authorizationId,executionReference:`external-run-${suffix}`,attachmentId,deployedAt:new Date().toISOString()};
    await assert.rejects(service.recordEmergencyDeployment(modelId,emergency.id,deployment,reviewer),/not found/);
    await assert.rejects(service.recordEmergencyDeployment(emergencyModel,emergency.id,{...deployment,attachmentId:'foreign'},reviewer),/evidence/);
    const result = await service.recordEmergencyDeployment(emergencyModel,emergency.id,deployment,reviewer);
    assert.equal(result.deploymentExecuted,false); assert.equal(result.executionSource,'OPERATOR_ATTESTATION');
    assert.equal((await service.recordEmergencyDeployment(emergencyModel,emergency.id,deployment,reviewer)).status,'DEPLOYED');
    assert.equal(((await service.detail(emergencyModel,owner)).model as any).status,'REVIEW_REQUIRED');
    await assert.rejects(service.recordEmergencyDeployment(emergencyModel,emergency.id,{...deployment,executionReference:'tamper'},reviewer),/immutable/);
    await assert.rejects(pgClient.query("UPDATE threat_emergency_changes SET security_impact='tamper' WHERE id=$1",[emergency.id]),/immutable/);
    await assert.rejects(pgClient.query("UPDATE threat_emergency_changes SET review_due_at=NOW()+INTERVAL '1 year' WHERE id=$1",[emergency.id]),/immutable/);
    await assert.rejects(service.reviewEmergencyChange(emergencyModel,emergency.id,{findings:'Self review',attachmentId},reviewer),/cannot independently/);
    await assert.rejects(service.reviewEmergencyChange(emergencyModel,emergency.id,{findings:'Self review',attachmentId},ciso),/cannot independently/);
    await service.reviewEmergencyChange(emergencyModel,emergency.id,{findings:'Independent post-change security checks passed',attachmentId},architect);
    await assert.rejects(service.closeEmergencyChange(emergencyModel,emergency.id,architect),/post-deployment model/);
    await approve(postReviewer);
    const approvedUpdate = (await service.governanceDetail(emergencyModel,owner)).emergencies.find((item:any)=>item.id===emergency.id) as any;
    assert.ok(approvedUpdate.model_updated_at); assert.equal(approvedUpdate.modelUpdateBreached,false);
    await service.closeEmergencyChange(emergencyModel,emergency.id,architect);
    assert.equal((await service.releaseGate(emergencyModel,owner)).securityGate,'PASS');
    await assert.rejects(pgClient.query("UPDATE threat_emergency_changes SET status='REQUESTED' WHERE id=$1",[emergency.id]),/immutable/);
    const lateId = `late-${suffix}`; const lateAuth = `late-auth-${suffix}`;
    await pgClient.query(`INSERT INTO threat_release_authorizations(id,threat_model_id,revision_id,release_id,issued_by,issued_at,expires_at,consumed_at,consumed_by,consumption_key,gate_snapshot) SELECT $1,threat_model_id,revision_id,release_id,issued_by,NOW()-INTERVAL '20 days',NOW()-INTERVAL '19 days',NOW()-INTERVAL '20 days',consumed_by,$1,gate_snapshot FROM threat_release_authorizations WHERE id=$2`,[lateAuth,auth.authorizationId]);
    await pgClient.query(`INSERT INTO threat_emergency_changes(id,threat_model_id,revision_id,change_id,policy_version_id,calendar_id,calendar_snapshot,status,reason,security_impact,compensating_controls,rollback_plan,requested_by,requested_at,approved_by,approved_at,authorization_expires_at,deployed_by,deployed_at,execution_reference,deployment_attachment_id,release_authorization_id,review_due_at,model_update_due_at) SELECT $1,threat_model_id,revision_id,change_id,policy_version_id,calendar_id,calendar_snapshot,'DEPLOYED','Historical overdue fixture',security_impact,compensating_controls,rollback_plan,requested_by,NOW()-INTERVAL '21 days',approved_by,NOW()-INTERVAL '20 days',NOW()-INTERVAL '19 days',deployed_by,NOW()-INTERVAL '20 days',$1,deployment_attachment_id,$2,NOW()-INTERVAL '18 days',NOW()-INTERVAL '15 days' FROM threat_emergency_changes WHERE id=$3`,[lateId,lateAuth,emergency.id]);
    assert.equal((await service.releaseGate(emergencyModel,owner)).securityGate,'BLOCK');
    const sweeps=await Promise.all([service.maintainGovernance(ciso),service.maintainGovernance(ciso)]);
    assert.ok(sweeps.reduce((sum,result)=>sum+result.emergencyBreaches,0)>=1);
    assert.equal((await pgClient.query("SELECT count(*)::int AS n FROM threat_model_audit_events WHERE entity_id=$1 AND action='EMERGENCY_SLA_BREACHED'",[lateId])).rows[0].n,2);
    assert.equal((await service.maintainGovernance(ciso)).emergencyBreaches,0);
    await assert.rejects(pgClient.query('UPDATE threat_emergency_changes SET review_breached_at=NULL WHERE id=$1',[lateId]),/immutable/);
    await service.reviewEmergencyChange(emergencyModel,lateId,{findings:'Late independent review',attachmentId},architect);
    assert.equal(((await service.governanceDetail(emergencyModel,owner)).emergencies.find((item:any)=>item.id===lateId) as any).reviewBreached,true);
  });
  await t.test('structured data and automatic boundary detection cannot be downgraded by frontend flags',async () => {
    const detail = await service.detail(modelId,owner) as any;
    const sourceId = detail.components[0].id;
    const destination = await service.addComponent(modelId,{name:'Restricted database',type:'DATABASE',securityZone:'RESTRICTED'},owner);
    await assert.rejects(service.addDataFlow(modelId,{name:'Unlabelled boundary',sourceComponentId:sourceId,destinationComponentId:destination.id,crossesTrustBoundary:false},owner),/requires a trust boundary/);
    const boundary = await service.addTrustBoundary(modelId,{name:'Restricted zone',boundaryType:'NETWORK'},owner);
    const flow = await service.addDataFlow(modelId,{name:'Classified flow',sourceComponentId:sourceId,destinationComponentId:destination.id,trustBoundaryId:boundary.id,crossesTrustBoundary:false},owner);
    assert.equal(flow.crossesTrustBoundary,true);
    const data = {name:'Bank data',classification:'RESTRICTED',bankSecrecy:true,ownerId:owner.id,retention:'Bank policy',allowedLocations:'Approved bank locations',encryptionRequirements:'TLS and encrypted storage',flowId:flow.id};
    await assert.rejects(service.addDataObject(modelId,{...data,classification:'PUBLIC'},owner),/at least RESTRICTED/);
    await service.addDataObject(modelId,data,owner);
    const assessment = await service.assessApplicability({threatModelId:modelId,answers:Object.fromEntries(screeningRules.map(rule=>[rule.signal,false])),justification:'Canonical data must win'},owner);
    assert.equal(assessment.tier,3);
    assert.ok(assessment.triggeredConditions.some(condition=>condition.signal==='bankSecrecy'));
    const before = (await service.governanceDetail(modelId,owner)).dataObjects.length;
    await assert.rejects(service.addDataObject(modelId,{...data,name:'Wrong revision',flowId:undefined,componentId:component.id},owner),/current revision/);
    assert.equal((await service.governanceDetail(modelId,owner)).dataObjects.length,before);
  });
  await t.test('scoped grants preserve clearance, independent authority, revocation and read-only auditor access',async()=>{
    await assert.rejects(service.detail(modelId,outsider),/restricted/);
    const read=await governanceAdmin.grant(modelId,{userId:outsider.id,permission:'READ',validUntil:new Date(Date.now()+86400000).toISOString(),reason:'Review assigned application'},owner);
    assert.equal((await service.detail(modelId,outsider)).model!.id,modelId);
    await assert.rejects(service.addComponent(modelId,{name:'Unauthorized edit',type:'API',securityZone:'INTERNAL'},outsider),/modify/);
    await assert.rejects(service.detail(modelId,{...outsider,securityClearance:'PUBLIC'}),/clearance/);
    await assert.rejects(governanceAdmin.grant(modelId,{userId:admin.id,permission:'CONTRIBUTE',validUntil:new Date(Date.now()+86400000).toISOString(),reason:'Attempt delegation'},outsider),/authority/);
    await governanceAdmin.revoke(modelId,read.id,{reason:'Review completed'},owner);
    await assert.rejects(service.detail(modelId,outsider),/restricted/);
    await assert.rejects(pgClient.query("DELETE FROM threat_model_access_grants WHERE id=$1",[read.id]),/append-only/);
    const write=await governanceAdmin.grant(modelId,{userId:outsider.id,permission:'CONTRIBUTE',validUntil:new Date(Date.now()+86400000).toISOString(),reason:'Assigned architecture contribution'},owner);
    await service.addComponent(modelId,{name:'Delegated component',type:'API',securityZone:'INTERNAL'},outsider);
    await assert.rejects(service.decideApproval(modelId,{stage:'APPSEC',decision:'APPROVED'},outsider),/authority|authorized|review|AppSec/i);
    await governanceAdmin.revoke(modelId,write.id,{reason:'Contribution completed'},owner);
    const auditor=await user('auditor',['AUDITOR']);
    await governanceAdmin.grant(modelId,{userId:auditor.id,permission:'CONTRIBUTE',validUntil:new Date(Date.now()+86400000).toISOString(),reason:'Read-only audit; role restriction must win'},owner);
    await service.detail(modelId,auditor);
    await assert.rejects(service.addComponent(modelId,{name:'Audit edit',type:'API',securityZone:'INTERNAL'},auditor),/read-only/);
  });
  await t.test('compliance proposals require an independent validated source and immutable retirement decisions',async()=>{
    const definition=await service.addComplianceRequirement({framework:`Internal fixture ${suffix}`,frameworkVersion:'1',code:'TEST-1',title:'Test interpretation, not regulatory certification',requirementKind:'BANK_POLICY',sourceUrl:'https://example.invalid/internal-policy'},reviewer);
    await assert.rejects(governanceAdmin.decideCompliance(definition.id,{decision:'VALIDATED',reason:'Self validation'},reviewer),/authority|author/);
    await governanceAdmin.decideCompliance(definition.id,{decision:'VALIDATED',reason:'Independent fixture validation'},architect);
    assert.equal((await pgClient.query('SELECT current_validation_status FROM threat_compliance_details WHERE id=$1',[definition.id])).rows[0].current_validation_status,'VALIDATED');
    await assert.rejects(governanceAdmin.decideCompliance(definition.id,{decision:'VALIDATED',reason:'Duplicate'},architect),/Invalid/);
    await governanceAdmin.decideCompliance(definition.id,{decision:'RETIRED',reason:'Superseded policy interpretation'},ciso);
    assert.equal((await pgClient.query('SELECT current_validation_status FROM threat_compliance_details WHERE id=$1',[definition.id])).rows[0].current_validation_status,'RETIRED');
    await assert.rejects(pgClient.query('DELETE FROM threat_compliance_decisions WHERE requirement_id=$1',[definition.id]),/append-only/);
  });
  await t.test('retirement requires independent fresh evidence and preserves holds, retention and immutable history',async()=>{
    const draft=await service.create({title:'Retirement fixture',serviceId:appId,criticality:'LOW',dataClassification:'CONFIDENTIAL_SECURITY_ONLY',businessOwnerId:owner.id,technicalOwnerId:owner.id,scopeSummary:'Decommission scope',architectureSummary:'Retired application',assumptions:'No active production',securityObjectives:'Retain governance history'},owner);
    const mid=String(draft.model!.id);
    await pgClient.query("UPDATE tickets SET category='CHANGE_REQUEST' WHERE id=$1",[ticketId]);
    const request=await governanceAdmin.requestRetirement(mid,{version:draft.model!.version,changeTicketId:ticketId,attachmentId,reason:'Evidence of completed decommission'},owner);
    await assert.rejects(governanceAdmin.decideRetirement(mid,request.id,{decision:'APPROVED',reason:'Owner self-approval'},owner),/CISO/);
    await governanceAdmin.retain(mid,{action:'HOLD_SET',reason:'Legal preservation notice'},architect);
    await assert.rejects(governanceAdmin.decideRetirement(mid,request.id,{decision:'APPROVED',reason:'Stale assessment'},ciso),/changed/);
    const current=(await governanceAdmin.lifecycle(mid,owner)).model;
    const fresh=await governanceAdmin.requestRetirement(mid,{version:current.version,changeTicketId:ticketId,attachmentId,reason:'Reassessed with legal hold retained'},owner);
    await governanceAdmin.decideRetirement(mid,fresh.id,{decision:'APPROVED',reason:'Independent decommission evidence reviewed'},ciso);
    const retired=(await governanceAdmin.lifecycle(mid,owner)).model;
    assert.equal(retired.status,'RETIRED');assert.equal(retired.legalHold,true);
    assert.ok(new Date(retired.retainUntil).getTime()>Date.now()+7*365*86400000);
    assert.ok(retired.retentionPolicyVersionId);
    await assert.rejects(service.addComponent(mid,{name:'Post-retirement mutation',type:'API',securityZone:'INTERNAL'},owner),/read-only/);
    await assert.rejects(pgClient.query("UPDATE threat_model_revisions SET scope_summary='Post-retirement tamper' WHERE id=$1",[draft.revision.id]),/Retired.*immutable/);
    await assert.rejects(pgClient.query('UPDATE threat_models SET legal_hold=false WHERE id=$1',[mid]),/audited/);
    await governanceAdmin.retain(mid,{action:'ARCHIVED',reason:'Archive retained security record'},architect);
    assert.equal((await governanceAdmin.lifecycle(mid,owner)).model.status,'ARCHIVED');
    await assert.rejects(governanceAdmin.retain(mid,{action:'HOLD_RELEASED',reason:'Original holder release'},architect),/Independent CISO/);
    await governanceAdmin.retain(mid,{action:'HOLD_RELEASED',reason:'Independent legal release approved'},ciso);
    await assert.rejects(governanceAdmin.retain(mid,{action:'RETENTION_EXTENDED',retainUntil:new Date(Date.now()+86400000).toISOString(),reason:'Attempt shorten'},ciso),/only be extended/);
    await assert.rejects(pgClient.query('DELETE FROM threat_retirement_decisions WHERE request_id=$1',[fresh.id]),/append-only/);
  });
  await t.test('search and aggregate reports enforce the same model scope and clearance as detail reads',async()=>{
    assert.ok((await pgClient.query('SELECT 1 FROM threat_model_scope_references WHERE threat_model_id=$1 AND application_id=$2',[modelId,appId])).rowCount);
    await assert.rejects(pgClient.query("UPDATE threat_models SET service_id='nonexistent-canonical-scope' WHERE id=$1",[modelId]),/canonical record/);
    assert.equal((await service.list(outsider,{q:'Governance fixture'})).length,0);
    assert.equal((await service.list(owner,{q:'Governance fixture',serviceId:appId,status:'DRAFT'})).some(row=>row.id===modelId),true);
    assert.equal((await service.list(owner,{q:"' OR 1=1 --"})).length,0);
    await assert.rejects(service.list(owner,{tier:4}),/less than or equal/);
    await assert.rejects(service.list(owner,{threatDueBefore:'2026-02-31'}));
    await assert.rejects(service.list(owner,{classification:'UNKNOWN'}));
    const current=await service.detail(modelId,owner) as any;
    const currentThreat=current.threats[0];const currentControl=current.controls[0];
    for(const filter of [{threatId:currentThreat.id},{threatId:currentThreat.key},{controlId:currentControl.id}]){
      assert.ok((await service.list(owner,{serviceId:appId,...filter})).some(row=>row.id===modelId));
      assert.equal((await service.list(outsider,filter)).length,0);
    }
    assert.equal((await service.list(owner,{threatId:threat.id})).length,0,'Historical threats must not match current revision filters');
    assert.equal((await service.list(owner,{controlId:control.id})).length,0,'Historical controls must not match current revision filters');
    assert.equal((await service.list(owner,{exceptionExpiresBefore:'1900-01-01T00:00:00Z'})).length,0);
    const dated=await service.create({title:'Dated search fixture',serviceId:appId,criticality:'LOW',dataClassification:'INTERNAL'},owner);
    const datedId=String(dated.model!.id);
    const datedThreat=await service.addThreat(datedId,{title:'Time-bound assumption',description:'Search fixture',attackScenario:'Fixture access',categories:['SPOOFING'],inherentLikelihood:1,inherentImpact:1,dueDate:'2027-01-15'},owner);
    const hasDated=async(filter:Record<string,unknown>)=>(await service.list(owner,{serviceId:appId,...filter})).some(row=>row.id===datedId);
    assert.equal(await hasDated({threatDueBefore:'2027-01-14'}),false);
    assert.equal(await hasDated({threatDueBefore:'2027-01-15'}),true);
    const expiry=new Date(Date.now()+86400000).toISOString();
    const exception=await service.requestRiskAcceptance(datedThreat.id,{reason:'Bounded fixture',businessJustification:'Test expiry filtering',compensatingControls:'Restricted access',remediationOwnerId:owner.id,remediationPlan:'Remove assumption',remediationDeadline:expiry,expiresAt:expiry},owner);
    const expiryFilter={exceptionExpiresBefore:expiry};
    assert.equal(await hasDated(expiryFilter),false,'Pending requests must not be counted as approved exceptions');
    await service.decideRiskAcceptance(exception.id,{decision:'APPROVED'},ciso);
    assert.equal(await hasDated(expiryFilter),true);
    assert.equal((await service.list(outsider,expiryFilter)).length,0);
    const reportOutsider=await user('report-outsider',['REQUESTER']);
    const empty=await service.governanceReport(reportOutsider);
    assert.deepEqual(empty.coverage,{});assert.equal(empty.threats.open_total,0);assert.equal(empty.applicationCoverage.total,0);
    const visible=await service.governanceReport(owner);
    assert.ok(visible.applicationCoverage.total>=1);assert.ok(visible.applicationCoverage.with_model>=1);
    const low=await service.governanceReport({...reviewer,securityClearance:'PUBLIC'});
    assert.deepEqual(low.coverage,{});assert.equal(low.threats.open_total,0);
  });
  await t.test('retired compliance mappings block live release and schedule exactly one auditable revalidation',async()=>{
    const definition=await service.addComplianceRequirement({framework:`Compliance cycle ${suffix}`,frameworkVersion:'1',code:'CONTROL-1',title:'Test control policy',requirementKind:'BANK_POLICY',sourceUrl:'https://example.invalid/policy/1'},reviewer);
    await governanceAdmin.decideCompliance(definition.id,{decision:'VALIDATED',reason:'Independent policy review'},architect);
    const created=await service.create({title:'Compliance revalidation fixture',serviceId:appId,criticality:'LOW',dataClassification:'INTERNAL'},owner);const mid=String(created.model!.id);const rid=String(created.revision.id);
    await service.addComponent(mid,{name:'Policy governed API',type:'API',securityZone:'INTERNAL'},owner);
    const threat=await service.addThreat(mid,{title:'Policy assumption',description:'Fixture',attackScenario:'Bypass governed access',categories:['BUSINESS_ABUSE'],inherentLikelihood:1,inherentImpact:1},owner);
    const control=await service.addControl(threat.id,{title:'Policy control',description:'Server access enforcement',controlType:'PREVENTIVE'},owner);
    await service.createRequirement(mid,{title:'Policy requirement',description:'Enforce authorized access',ownerId:owner.id,verificationMethod:'API_SECURITY_TEST',threatIds:[threat.id],controlIds:[control.id],complianceIds:[definition.id]},owner);
    assert.ok((await service.list(owner,{complianceId:definition.id})).some(row=>row.id===mid));
    assert.equal((await service.list(outsider,{complianceId:definition.id})).length,0);
    assert.equal((await service.list(owner,{complianceId:'missing-definition'})).length,0);
    const evidence=await service.linkEvidence(mid,{attachmentId,controlId:control.id},owner);
    await service.recordVerification(control.id,{result:'PASS',verificationType:'API_SECURITY_TEST',testCase:'Policy access',expectedResult:'403',evidenceIds:[evidence.id]},postReviewer);
    await service.calculateResidualRisk(threat.id,{residualLikelihood:1,residualImpact:1,residualRiskRationale:'Verified fixture'},postReviewer);
    await service.transitionThreat(threat.id,{status:'MITIGATING',reason:'Implemented'},owner);await service.transitionThreat(threat.id,{status:'MITIGATED',reason:'Verified'},postReviewer);
    await service.assessApplicability({threatModelId:mid,answers,justification:'Scope policy screened'},owner);await service.submit(mid,owner);
    await service.decideApproval(mid,{stage:'APPSEC',decision:'APPROVED'},reviewer);await service.decideApproval(mid,{stage:'SECURITY_ARCHITECTURE',decision:'APPROVED'},architect);
    const approved=await service.exportSnapshot(mid,rid,owner);assert.equal((await service.releaseGate(mid,owner)).securityGate,'PASS');
    await governanceAdmin.decideCompliance(definition.id,{decision:'RETIRED',reason:'Replaced interpretation'},ciso);
    assert.equal((await service.releaseGate(mid,owner)).securityGate,'BLOCK');
    await service.reconcileComplianceChanges(reviewer);await service.reconcileComplianceChanges(reviewer);
    const revised=await service.governanceDetail(mid,owner);assert.equal((await service.detail(mid,owner)).revisions.length,2);
    assert.equal((await service.exportSnapshot(mid,rid,owner)).sha256,approved.sha256);
    const replacement=await service.addComplianceRequirement({framework:`Compliance cycle ${suffix}`,frameworkVersion:'2',code:'CONTROL-1',title:'Replacement policy',requirementKind:'BANK_POLICY',sourceUrl:'https://example.invalid/policy/2'},reviewer);
    await assert.rejects(governanceAdmin.replaceComplianceMapping(mid,{requirementId:revised.requirements[0].id,revisionVersion:revised.revision.version,complianceIds:[replacement.id],reason:'Pending definition'},owner),/validation/);
    await governanceAdmin.decideCompliance(replacement.id,{decision:'VALIDATED',reason:'Independent replacement review'},architect);
    await governanceAdmin.replaceComplianceMapping(mid,{requirementId:revised.requirements[0].id,revisionVersion:revised.revision.version,complianceIds:[replacement.id],reason:'Reviewed replacement'},owner);
    assert.deepEqual((await service.governanceDetail(mid,owner)).requirements[0].compliance_ids,[replacement.id]);
    assert.equal((await service.releaseGate(mid,owner)).securityGate,'BLOCK');
  });
  await t.test('evidence downloads enforce persisted scope, scan state and binary digest before audited delivery',async()=>{
    const original=storageService.getFileBuffer;let reads=0;
    try{
      storageService.getFileBuffer=async()=>{reads++;return {buffer:Buffer.from('test'),mimeType:'text/plain'};};
      await assert.rejects(service.downloadEvidence(modelId,evidence.id,outsider),/restricted/);assert.equal(reads,0);
      const downloaded=await service.downloadEvidence(modelId,evidence.id,owner);assert.equal(downloaded.buffer.toString(),'test');
      assert.ok((await pgClient.query("SELECT 1 FROM threat_model_audit_events WHERE entity_id=$1 AND action='THREAT_EVIDENCE_DOWNLOADED'",[evidence.id])).rowCount);
      storageService.getFileBuffer=async()=>({buffer:Buffer.from('tampered'),mimeType:'text/plain'});
      await assert.rejects(service.downloadEvidence(modelId,evidence.id,owner),/integrity/);
      await pgClient.query("UPDATE ticket_attachments SET source_payload=jsonb_set(source_payload,'{virusScanStatus}','\"PENDING\"') WHERE id=$1",[attachmentId]);
      await assert.rejects(service.downloadEvidence(modelId,evidence.id,owner),/Clean retained/);
    }finally{storageService.getFileBuffer=original;await pgClient.query("UPDATE ticket_attachments SET source_payload=jsonb_set(source_payload,'{virusScanStatus}','\"CLEAN\"') WHERE id=$1",[attachmentId]);}
  });
});
