import test, { after, before } from 'node:test';
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { pgClient } from '../server/db/postgres/client.js';
import { ThreatModelRepository } from '../server/db/postgres/threat-model-repository.js';
import { db } from '../server/db/database.js';
import { config } from '../server/config/index.js';
import { ThreatModelService as service } from '../server/services/threat-model.service.js';
import { ThreatControlCatalogService as catalog } from '../server/services/threat-control-catalog.service.js';
import { screeningRules } from '../server/services/threat-model-policy.js';
import { canonicalJson } from '../shared/canonical-json.js';
import { assertDisposableDatabase } from './fixtures/disposable-database.js';
import type { BankUser } from '../shared/types/auth.js';

const enabled = process.env.RUN_CMDB_DISCOVERY_INTEGRATION === '1' && /(?:^|_)integration(?:_|$)/.test(config.DB_NAME);
before(async () => { if (enabled) await assertDisposableDatabase(pgClient, config.DB_NAME); });
after(() => pgClient.close());

test('persistent governance lifecycle, RBAC, review cycles, copies and immutable approval package', { skip: !enabled }, async t => {
  const suffix = randomUUID().slice(0,8);
  const user = async (name: string, roles: BankUser['roles']) => {
    const id = `tmtest-${name}-${suffix}`;
    await pgClient.query(`INSERT INTO bank_users(id,username,email,first_name,last_name,title,roles,security_clearance) VALUES($1,$1,$2,$1,'Fixture','TEST',$3::jsonb,'CONFIDENTIAL_SECURITY_ONLY')`, [id, `${id}@example.invalid`,JSON.stringify(roles)]);
    const actor = { id, username:id, fullName:id, roles, isActive:true, securityClearance:'CONFIDENTIAL_SECURITY_ONLY', ownedApplicationIds:[], ownedAssetIds:[], teamIds:[] } as unknown as BankUser;
    db.data.users.push(actor); return actor;
  };
  const owner = await user('owner',['APPLICATION_OWNER']);
  const reviewer = await user('reviewer',['APPSEC_ANALYST']);
  const architect = await user('architect',['INFOSEC_MANAGER']);
  const postReviewer = await user('post-reviewer',['APPSEC_ANALYST']);
  const ciso = await user('ciso',['CISO']);
  const admin = await user('admin',['PLATFORM_ADMIN']);
  const outsider = await user('outsider',['REQUESTER']);
  const appId = `tmtest-app-${suffix}`;
  await pgClient.query(`INSERT INTO bank_applications(id,code,name,tier,architecture_type,technical_owner_id,business_owner_id) VALUES($1,$1,'Fixture application','LOW','MONOLITH',$2,$2)`, [appId,owner.id]);
  db.data.applications.push({ id:appId, name:'Fixture application',technicalOwnerId:owner.id,businessOwnerId:owner.id } as any);
  const created = await service.create({ title:'Governance fixture',serviceId:appId,criticality:'LOW',dataClassification:'INTERNAL',businessOwnerId:owner.id,technicalOwnerId:owner.id,scopeSummary:'Fixture scope',architectureSummary:'Fixture architecture',assumptions:'Fixture assumptions',securityObjectives:'Test objectives' },owner);
  const modelId = String(created.model!.id); const revisionId = String(created.revision.id);
  const answers = Object.fromEntries(screeningRules.map(rule => [rule.signal, rule.signal === 'internalChange']));
  await t.test('unscreened model blocks submission; tier cannot be overridden', async () => {
    await assert.rejects(service.submit(modelId,owner),/screening is required/);
    await assert.rejects(service.assessApplicability({ threatModelId:modelId, answers, justification:'Fixture',tier:0 },owner),/tier override/);
    const assessment = await service.assessApplicability({ threatModelId:modelId, answers, justification:'Fixture' },owner);
    assert.equal(assessment.tier,1);
  });
  await t.test('object access and admin approval are rejected by backend', async () => {
    await assert.rejects(service.detail(modelId,outsider),/restricted/);
    await assert.rejects(service.detail(modelId,admin),/restricted/);
    await assert.rejects(service.decideApproval(modelId,{stage:'APPSEC',decision:'APPROVED'},admin),/authority/);
  });
  const component = await service.addComponent(modelId,{name:'API',type:'API',securityZone:'INTERNAL'},owner);
  const threat = await service.addThreat(modelId,{title:'Unauthorized access',description:'Test scenario',attackScenario:'Fixture actor accesses forbidden data',categories:['SPOOFING'],inherentLikelihood:2,inherentImpact:2,affectedComponentId:component.id},owner);
  const control = await service.addControl(threat.id,{title:'Authorization',description:'Server authorization',controlType:'PREVENTIVE',implementationOwnerId:owner.id},owner);
  await service.createRequirement(modelId,{title:'Server authorization',description:'Authorize all reads',ownerId:owner.id,verificationMethod:'API_SECURITY_TEST',threatIds:[threat.id],controlIds:[control.id]},owner);
  await t.test('duplicate requirement is rejected without a partial insert',async () => {
    await assert.rejects(service.createRequirement(modelId,{title:'Server authorization',description:'Duplicate',ownerId:owner.id,verificationMethod:'API_SECURITY_TEST',threatIds:[threat.id]},owner));
    assert.equal((await pgClient.query('SELECT count(*)::int AS n FROM threat_security_requirements WHERE revision_id=$1',[revisionId])).rows[0].n,1);
    await assert.rejects(service.transitionThreat(threat.id,{status:'CLOSED',reason:'Attempt bypass'},owner),/Invalid/);
    await assert.rejects(service.recordVerification(control.id,{result:'PASS',verificationType:'API_SECURITY_TEST',testCase:'test',expectedResult:'deny',evidenceIds:[]},reviewer),/evidence/);
  });
  const ticketId = `tmtest-ticket-${suffix}`;
  await pgClient.query(`INSERT INTO tickets(id,key,project_code,ticket_type_id,ticket_type_name,category,security_domain,title,description,status_id,status_name,status_category,workflow_id,technical_severity,business_priority,business_impact,inherent_risk,residual_risk,reporter_id,due_date,remediation_deadline) VALUES($1,$1,'TEST','TEST','Fixture','SECURITY_REVIEW','APPSEC','Fixture evidence','Fixture','test-open','Open','TODO','test-workflow','LOW','P3_MEDIUM','MODERATE','LOW','LOW',$2,NOW()+INTERVAL '1 day',NOW()+INTERVAL '1 day')`,[ticketId,owner.id]);
  const attachmentId = `tmtest-attachment-${suffix}`;
  await pgClient.query('UPDATE threat_models SET release_id=$1 WHERE id=$2',[ticketId,modelId]);
  await pgClient.query(`INSERT INTO ticket_attachments(id,ticket_id,file_name,file_size_bytes,mime_type,storage_key,sha256_hash,uploaded_by_user_id) VALUES($1,$2,'fixture.txt',4,'text/plain','test-only',$3,$4)`,[attachmentId,ticketId,createHash('sha256').update('test').digest('hex'),owner.id]);
  db.data.tickets.push({id:ticketId,reporterId:owner.id,requesterId:owner.id,ownerId:owner.id,confidentiality:'INTERNAL',securityDomain:'APPSEC',watcherIds:[],participantIds:[]} as any);
  db.data.attachments.push({id:attachmentId,ticketId,virusScanStatus:'CLEAN'} as any);
  const evidence = await service.linkEvidence(modelId,{attachmentId,controlId:control.id},owner);
  await service.recordVerification(control.id,{result:'PASS',verificationType:'API_SECURITY_TEST',testCase:'Unauthorized read',expectedResult:'403',evidenceIds:[evidence.id]},reviewer);
  await service.calculateResidualRisk(threat.id,{residualLikelihood:1,residualImpact:1,residualRiskRationale:'Fixture test proves authorization'},reviewer);
  await service.transitionThreat(threat.id,{status:'MITIGATING',reason:'Implemented'},owner);
  await service.transitionThreat(threat.id,{status:'MITIGATED',reason:'Verified'},reviewer);
  await t.test('approval from earlier review cycle does not survive requested changes',async () => {
    await service.assessApplicability({threatModelId:modelId,answers,justification:'Re-screen completed architecture'},owner);
    await service.submit(modelId,owner);
    await service.decideApproval(modelId,{stage:'APPSEC',decision:'APPROVED'},reviewer);
    await service.decideApproval(modelId,{stage:'SECURITY_ARCHITECTURE',decision:'CHANGES_REQUESTED'},architect);
    await service.submit(modelId,owner);
    await service.decideApproval(modelId,{stage:'SECURITY_ARCHITECTURE',decision:'APPROVED'},architect);
    assert.equal((await service.detail(modelId,owner)).model && ((await service.detail(modelId,owner)).model as any).status,'IN_REVIEW');
    await service.decideApproval(modelId,{stage:'APPSEC',decision:'APPROVED'},reviewer);
    assert.equal((await service.releaseGate(modelId,owner)).securityGate,'PASS');
  });
  await t.test('approved content and approval snapshot resist direct SQL writes',async () => {
    await assert.rejects(pgClient.query("UPDATE threats SET title='tamper' WHERE id=$1",[threat.id]),/immutable/);
    await assert.rejects(service.calculateResidualRisk(threat.id,{residualLikelihood:1,residualImpact:1,residualRiskRationale:'tamper'},reviewer),/immutable/);
    await assert.rejects(pgClient.query('DELETE FROM threat_model_approval_snapshots WHERE revision_id=$1',[revisionId]),/append-only/);
    const report = await service.exportSnapshot(modelId,revisionId,owner);
    assert.equal(report.sha256,createHash('sha256').update(canonicalJson(report.snapshot)).digest('hex'));
    assert.equal(report.snapshot.revision[0].status,'APPROVED');
    const audit = (await pgClient.query('SELECT * FROM threat_model_audit_events WHERE threat_model_id=$1 ORDER BY event_sequence DESC LIMIT 1',[modelId])).rows[0];
    assert.match(audit.event_hash,/^[a-f0-9]{64}$/);
    assert.equal(audit.event_hash,ThreatModelRepository.auditDigest(audit));
    assert.notEqual(audit.event_hash,ThreatModelRepository.auditDigest({...audit,action:'TAMPERED'}));
  });
  const authorization = await service.authorizeRelease(modelId,ticketId,reviewer);
  await t.test('release authorization is persisted, freshly evaluated and consumed idempotently',async () => {
    await assert.rejects(service.authorizeRelease(modelId,ticketId,admin),/authority/);
    const request = {releaseId:ticketId,authorization:authorization.authorization,idempotencyKey:'fixture-job-1'};
    assert.equal((await service.consumeReleaseAuthorization(modelId,request,reviewer)).deploymentExecuted,false);
    assert.equal((await service.consumeReleaseAuthorization(modelId,request,reviewer)).gate.securityGate,'PASS');
    await assert.rejects(service.consumeReleaseAuthorization(modelId,{...request,idempotencyKey:'fixture-job-2'},reviewer),/already consumed/);
  });
  await t.test('concurrent new revisions copy architecture and requirements exactly once without carrying verification',async () => {
    const results = await Promise.allSettled([service.createRevision(modelId,{changeReason:'Material API change'},owner),service.createRevision(modelId,{changeReason:'Concurrent change'},owner)]);
    assert.equal(results.filter(result=>result.status==='fulfilled').length,1);
    const detail = await service.detail(modelId,owner) as any;
    assert.equal(detail.components.length,1); assert.equal(detail.controls.length,1); assert.equal(detail.verifications.length,0);
    assert.equal(detail.threats[0].lineageId,threat.lineageId);
    assert.equal(detail.threats[0].previousThreatId,threat.id);
    const lineage=await service.threatLineage(detail.threats[0].id,{limit:1},owner);
    assert.equal(lineage.hasMore,true);assert.equal(lineage.versions[0].revisionNumber,2);
    const older=await service.threatLineage(detail.threats[0].id,{limit:1,offset:1},owner);
    assert.equal(older.versions[0].id,threat.id);assert.equal(older.versions[0].revisionStatus,'APPROVED');
    assert.equal((await service.exportSnapshot(modelId,revisionId,owner)).snapshot.threats[0].lineage_id,threat.lineageId);
    await assert.rejects(service.threatLineage(detail.threats[0].id,{},outsider),/restricted/);
    await assert.rejects(service.updateThreat(threat.id,{...threat,reason:'Historical edit'},owner),/no longer current/);
    assert.equal((await service.governanceDetail(modelId,owner)).requirements.length,1);
    assert.equal((await service.releaseGate(modelId,owner)).securityGate,'BLOCK');
    assert.equal((await service.exportSnapshot(modelId,revisionId,owner)).snapshot.revision[0].status,'APPROVED');
    await assert.rejects(service.consumeReleaseAuthorization(modelId,{releaseId:ticketId,authorization:authorization.authorization,idempotencyKey:'fixture-job-1'},reviewer),/no longer current/);
  });
  await t.test('high-risk exception uses calculated severity, bounded lifetime and independent CISO approval',async () => {
    const high = await service.addThreat(modelId,{title:'High scenario',description:'Fixture',attackScenario:'High scenario',categories:['BUSINESS_ABUSE'],inherentLikelihood:3,inherentImpact:4},owner);
    const request = {reason:'Remediation needs change window',businessJustification:'Bounded test exposure',compensatingControls:'Manual approvals',remediationOwnerId:owner.id,remediationPlan:'Remediate before expiry',remediationDeadline:new Date(Date.now()+86400000).toISOString(),expiresAt:new Date(Date.now()+2*86400000).toISOString()};
    await assert.rejects(service.requestRiskAcceptance(high.id,{...request,riskLevel:'LOW'},owner),/risk level override/);
    await assert.rejects(service.requestRiskAcceptance(high.id,{...request,expiresAt:new Date(Date.now()+31*86400000).toISOString()},owner),/maximum/);
    const exception = await service.requestRiskAcceptance(high.id,request,owner);
    await assert.rejects(service.decideRiskAcceptance(exception.id,{decision:'APPROVED'},reviewer),/CISO/);
    await service.decideRiskAcceptance(exception.id,{decision:'APPROVED'},ciso);
    await assert.rejects(service.decideRiskAcceptance(exception.id,{decision:'APPROVED'},ciso),/renewal/);
    await service.decideRiskAcceptance(exception.id,{decision:'REVOKED'},ciso);
    await assert.rejects(service.transitionThreat(high.id,{status:'ACCEPTED',reason:'Revoked'},reviewer),/current approved risk acceptance/);
  });
  await t.test('periodic review maintenance creates one revalidation draft and is replay safe',async () => {
    const created = await service.create({title:'Periodic screening fixture',serviceId:appId,criticality:'LOW',dataClassification:'INTERNAL'},owner);
    const periodicId = String(created.model!.id);
    await service.assessApplicability({threatModelId:periodicId,answers:Object.fromEntries(screeningRules.map(rule=>[rule.signal,false])),justification:'No security impact'},owner);
    await service.submit(periodicId,owner);
    await service.decideApproval(periodicId,{stage:'APPSEC',decision:'APPROVED'},reviewer);
    await service.decideApproval(periodicId,{stage:'SECURITY_ARCHITECTURE',decision:'APPROVED'},architect);
    await pgClient.query("UPDATE threat_models SET next_review_at=NOW()-INTERVAL '1 day' WHERE id=$1",[periodicId]);
    assert.equal((await service.releaseGate(periodicId,owner)).securityGate,'BLOCK');
    const first = await service.maintainGovernance(ciso);
    assert.ok(first.overdue>=1);
    const detail = await service.detail(periodicId,owner) as any;
    assert.equal(detail.model.status,'REVIEW_REQUIRED'); assert.equal(detail.revisions.length,2);
    assert.equal((await service.maintainGovernance(ciso)).overdue,0);
  });
  await t.test('authored threat changes preserve lineage and invalidate shared verification and stale risk acceptance',async()=>{
    const created=await service.create({title:'Content editing fixture',serviceId:appId,criticality:'LOW',dataClassification:'INTERNAL'},owner);
    const editModel=String(created.model!.id);
    await service.assessApplicability({threatModelId:editModel,answers:Object.fromEntries(screeningRules.map(rule=>[rule.signal,false])),justification:'Fixture'},owner);
    const a=await service.addThreat(editModel,{title:'Edit A',description:'Original',attackScenario:'Original scenario',categories:['SPOOFING'],inherentLikelihood:2,inherentImpact:2},owner);
    const b=await service.addThreat(editModel,{title:'Edit B',description:'Shared scope',attackScenario:'Other scenario',categories:['TAMPERING'],inherentLikelihood:2,inherentImpact:2},owner);
    assert.equal(a.lineageId,a.id);assert.equal(a.lineageOrigin,'NATIVE');assert.equal(a.contentVersion,1);
    const shared=await service.addControl(a.id,{title:'Shared authorization',description:'Both scenarios',controlType:'PREVENTIVE'},owner);
    await service.mapControlThreat(editModel,{controlId:shared.id,threatId:b.id,scopeVersion:1,action:'LINK',reason:'Shared enforcement'},owner);
    const companion=await service.addControl(a.id,{title:'Companion monitoring',description:'Monitor both assumptions',controlType:'DETECTIVE',requiredBeforeRelease:false},owner);
    const ev=await service.linkEvidence(editModel,{attachmentId,controlId:shared.id},owner);
    const pass=await service.recordVerification(shared.id,{controlScopeVersion:2,result:'PASS',verificationType:'API_SECURITY_TEST',testCase:'Both scenarios',expectedResult:'Denied',evidenceIds:[ev.id]},reviewer);
    for(const item of [a,b]){
      await service.calculateResidualRisk(item.id,{residualLikelihood:1,residualImpact:1,residualRiskRationale:'Test covers both'},reviewer);
      await service.transitionThreat(item.id,{status:'MITIGATING',reason:'Implemented'},owner);
      await service.transitionThreat(item.id,{status:'MITIGATED',reason:'Verified'},reviewer);
    }
    const request={reason:'Bounded fixture',businessJustification:'Business impact',compensatingControls:'Manual dual approval',remediationOwnerId:owner.id,remediationPlan:'Fix',remediationDeadline:new Date(Date.now()+86400000).toISOString(),expiresAt:new Date(Date.now()+2*86400000).toISOString()};
    const exception=await service.requestRiskAcceptance(a.id,request,owner);
    await service.decideRiskAcceptance(exception.id,{decision:'APPROVED'},reviewer);
    const pending=await service.requestRiskAcceptance(a.id,request,owner);
    const edit={...a,attackScenario:'Changed authorization assumptions',inherentLikelihood:3,inherentImpact:4,reason:'Expanded attacker capability'};
    await assert.rejects(service.updateThreat(a.id,edit,outsider),/restricted/);
    await assert.rejects(service.updateThreat(a.id,{...edit,affectedAssetId:'unknown-asset'},owner),/does not exist/);
    await assert.rejects(service.updateThreat(a.id,{...edit,affectedComponentId:component.id},owner),/threat revision/);
    await assert.rejects(service.updateThreat(a.id,{...edit,ownerId:'unknown-user'},owner),/active threat owner/);
    const edited=await service.updateThreat(a.id,edit,reviewer,{correlationId:'threat-edit-fixture'});
    assert.equal(edited.contentVersion,2);assert.equal(edited.lineageId,a.id);assert.equal(edited.status,'OPEN');assert.equal(edited.residualScore,undefined);
    const detail=await service.detail(editModel,owner) as any;
    assert.equal(detail.controls[0].scopeVersion,3);assert.equal(detail.controls[0].status,'VERIFICATION_REQUIRED');
    assert.equal(detail.controls.find((item:any)=>item.id===companion.id).status,'VERIFICATION_REQUIRED');
    const events=(await pgClient.query("SELECT correlation_id,payload FROM outbox_events WHERE topic='threat-control.verification.required' AND payload->>'threatModelId'=$1 AND payload->>'requestCorrelationId'='threat-edit-fixture'",[editModel])).rows;
    assert.equal(events.length,2);assert.equal(new Set(events.map(row=>row.correlation_id)).size,2);
    assert.equal(detail.threats.find((item:any)=>item.id===b.id).residualScore,undefined);
    assert.equal(detail.threats.find((item:any)=>item.id===b.id).status,'OPEN');
    assert.equal(detail.verifications.find((item:any)=>item.id===pass.id).result,'PASS');
    assert.equal(detail.exceptions.find((item:any)=>item.id===exception.id).status,'APPROVED');
    assert.equal(detail.exceptions.find((item:any)=>item.id===exception.id).threatContentVersion,1);
    assert.ok((await service.governanceReport(reviewer)).exceptions.stale>=1);
    await assert.rejects(service.transitionThreat(a.id,{status:'ACCEPTED',reason:'Old assessment'},reviewer),/current approved/);
    await assert.rejects(service.decideRiskAcceptance(pending.id,{decision:'APPROVED'},ciso),/fresh threat assessment/);
    await assert.rejects(pgClient.query("UPDATE threat_model_exceptions SET status='APPROVED' WHERE id=$1",[pending.id]),/fresh threat assessment/);
    await assert.rejects(pgClient.query('UPDATE threat_model_exceptions SET threat_content_version=2 WHERE id=$1',[exception.id]),/immutable/);
    await assert.rejects(service.recordVerification(shared.id,{controlScopeVersion:2,result:'PASS',verificationType:'API_SECURITY_TEST',testCase:'Stale',expectedResult:'Denied',evidenceIds:[ev.id]},reviewer),/changed|scope/);
    await assert.rejects(service.updateThreat(a.id,edit,reviewer),/changed by another/);
    const noop=await service.updateThreat(a.id,{...edited,reason:'No change'},reviewer);
    assert.equal(noop.contentVersion,2);
    assert.equal((await pgClient.query("SELECT count(*)::int AS n FROM threat_model_audit_events WHERE entity_id=$1 AND action='THREAT_UPDATED'",[a.id])).rows[0].n,1);
    const audit=(await pgClient.query("SELECT * FROM threat_model_audit_events WHERE entity_id=$1 AND action='THREAT_UPDATED'",[a.id])).rows[0];
    assert.equal(audit.old_value.content_version,1);assert.equal(audit.new_value.threat.content_version,2);assert.equal(audit.correlation_id,'threat-edit-fixture');
    assert.ok(audit.new_value.staleExceptions.includes(exception.id));
    const concurrent=await Promise.allSettled([service.updateThreat(a.id,{...edited,title:'Parallel A',reason:'Concurrent A'},reviewer),service.updateThreat(a.id,{...edited,title:'Parallel B',reason:'Concurrent B'},reviewer)]);
    assert.equal(concurrent.filter(result=>result.status==='fulfilled').length,1);
    await pgClient.query("UPDATE threats SET attack_scenario='Direct SQL content change' WHERE id=$1",[a.id]);
    const sqlState=(await pgClient.query('SELECT content_version FROM threats WHERE id=$1',[a.id])).rows[0];assert.equal(sqlState.content_version,4);
    assert.equal((await pgClient.query('SELECT scope_version FROM threat_controls WHERE id=$1',[shared.id])).rows[0].scope_version,5);
    await assert.rejects(pgClient.query('UPDATE threats SET previous_threat_id=$1 WHERE id=$2',[b.id,a.id]),/server-managed/);
    await assert.rejects(pgClient.query('UPDATE threat_lineage_members SET lineage_id=$1 WHERE threat_id=$2',[b.id,a.id]),/append-only/);
    await assert.rejects(pgClient.query(`INSERT INTO threats(id,revision_id,key,title,description,categories,attack_scenario,inherent_likelihood,inherent_impact,inherent_score,status,created_by_user_id,previous_threat_id)
      VALUES($1,$2,$1,'Invalid cross-model copy','Invalid','["SPOOFING"]','Invalid',1,1,1,'OPEN',$3,$4)`,[`cross-lineage-${suffix}`,created.revision.id,owner.id,threat.id]),/same model predecessor/);
    const raceThreat=(await service.detail(editModel,owner) as any).threats.find((item:any)=>item.id===a.id);
    const race=await Promise.allSettled([
      service.updateThreat(a.id,{...raceThreat,title:'Concurrent verification and edit',reason:'Reassess scope'},reviewer),
      service.recordVerification(shared.id,{controlScopeVersion:5,result:'PASS',verificationType:'API_SECURITY_TEST',testCase:'Concurrent scope',expectedResult:'Denied',evidenceIds:[ev.id]},postReviewer),
    ]);
    assert.equal(race[0].status,'fulfilled');
    if(race[1].status==='rejected')assert.match(String(race[1].reason),/scope|changed/);
    const afterRace=await service.detail(editModel,owner) as any;
    assert.equal(afterRace.controls[0].scopeVersion,6);assert.equal(afterRace.controls[0].status,'VERIFICATION_REQUIRED');
    assert.equal(afterRace.verifications.some((item:any)=>item.controlScopeVersion===6&&item.result==='PASS'),false);
    const fresh=await service.requestRiskAcceptance(a.id,request,owner);assert.equal(fresh.threatContentVersion,5);
    await service.decideRiskAcceptance(fresh.id,{decision:'APPROVED'},ciso);
    await service.transitionThreat(a.id,{status:'ACCEPTED',reason:'Fresh assessment'},reviewer);
    await service.submit(editModel,owner);
    const latest=(await service.detail(editModel,owner) as any).threats.find((item:any)=>item.id===a.id);
    await assert.rejects(service.updateThreat(a.id,{...latest,title:'Review mutation',reason:'Blocked'},owner),/immutable/);
    await assert.rejects(service.decideApproval(editModel,{stage:'APPSEC',decision:'APPROVED'},reviewer),/contributing author/);
  });
  await t.test('architecture edits enforce graph integrity, fresh evidence and immutable snapshots',async()=>{
    const created=await service.create({title:'Architecture fixture',serviceId:appId,releaseId:ticketId,criticality:'LOW',dataClassification:'INTERNAL'},owner);
    const mid=String(created.model!.id);const rid=String(created.revision.id);
    const a=await service.addComponent(mid,{name:'Client',type:'PROCESS',securityZone:'INTERNAL'},owner);
    const b=await service.addComponent(mid,{name:'API',type:'API',securityZone:'INTERNAL'},owner);
    const boundary=await service.addTrustBoundary(mid,{name:'External boundary',boundaryType:'NETWORK'},owner);
    const flow=await service.addDataFlow(mid,{name:'Requests',sourceComponentId:a.id,destinationComponentId:b.id,protocol:'HTTPS',port:443,dataClassification:'INTERNAL',encryptionInTransit:true},owner);
    assert.equal(flow.crossesTrustBoundary,false);
    await service.addDataObject(mid,{name:'Request IDs',classification:'INTERNAL',ownerId:owner.id,retention:'Bank policy',allowedLocations:'Bank',encryptionRequirements:'TLS',flowId:flow.id},owner);
    const th=await service.addThreat(mid,{title:'Object access',description:'Unauthorized read',attackScenario:'Actor accesses another object',categories:['SPOOFING'],inherentLikelihood:2,inherentImpact:2,affectedComponentId:b.id,affectedDataFlowId:flow.id},owner);
    const ctl=await service.addControl(th.id,{title:'Object authorization',description:'Authorize every read',controlType:'PREVENTIVE'},owner);
    await service.createRequirement(mid,{title:'Access enforcement',description:'Deny unauthorized access',ownerId:owner.id,verificationMethod:'API_SECURITY_TEST',threatIds:[th.id],controlIds:[ctl.id]},owner);
    const ev=await service.linkEvidence(mid,{attachmentId,controlId:ctl.id},owner);
    const verify=async()=>{const detail=await service.detail(mid,owner) as any;await service.recordVerification(ctl.id,{controlScopeVersion:detail.controls[0].scopeVersion,result:'PASS',verificationType:'API_SECURITY_TEST',testCase:'Current architecture',expectedResult:'403',evidenceIds:[ev.id]},postReviewer);await service.calculateResidualRisk(th.id,{residualLikelihood:1,residualImpact:1,residualRiskRationale:'Current evidence'},postReviewer);await service.transitionThreat(th.id,{status:'MITIGATING',reason:'Implemented'},owner);await service.transitionThreat(th.id,{status:'MITIGATED',reason:'Verified'},postReviewer);};
    await verify();await service.assessApplicability({threatModelId:mid,answers,justification:'Initial architecture'},owner);
    const baseline=(await service.governanceDetail(mid,owner)).revision.architecture_version;
    const request={reason:'Bounded risk',businessJustification:'Fixture impact',compensatingControls:'Manual review',remediationOwnerId:owner.id,remediationPlan:'Fix',remediationDeadline:new Date(Date.now()+86400000).toISOString(),expiresAt:new Date(Date.now()+2*86400000).toISOString()};
    const exception=await service.requestRiskAcceptance(th.id,request,owner);assert.equal(exception.architectureVersion,baseline);await service.decideRiskAcceptance(exception.id,{decision:'APPROVED'},postReviewer);
    const pending=await service.requestRiskAcceptance(th.id,request,owner);
    const doc=await service.editArchitecture(mid,a.id,{...a,kind:'component',action:'UPDATE',name:'Documented client',reason:'Clarify name'},reviewer);
    assert.equal(doc.entity!.contentVersion,2);assert.equal((await service.governanceDetail(mid,owner)).revision.architecture_version,baseline);
    let detail=await service.detail(mid,owner) as any;assert.equal(detail.controls[0].status,'VERIFIED');assert.equal(detail.threats[0].status,'MITIGATED');
    assert.equal((await service.editArchitecture(mid,a.id,{...doc.entity,kind:'component',action:'UPDATE',reason:'No-op'},reviewer)).changed,false);
    await assert.rejects(service.editArchitecture(mid,a.id,{...a,kind:'component',action:'UPDATE',reason:'Stale'},owner),/changed by another/);
    const edit={...doc.entity,kind:'component',action:'UPDATE',securityZone:'INTERNET',reason:'External exposure'};
    await assert.rejects(service.editArchitecture(mid,a.id,edit,outsider),/restricted/);
    await assert.rejects(service.editArchitecture(mid,component.id,edit,owner),/not found/);
    await assert.rejects(service.editArchitecture(mid,a.id,edit,owner),/requires a trust boundary/);
    assert.equal((await service.governanceDetail(mid,owner)).revision.architecture_version,baseline);
    await assert.rejects(service.editArchitecture(mid,a.id,{kind:'component',action:'DELETE',contentVersion:2,reason:'Referenced'},owner),/Referenced architecture/);
    const linked=await service.editArchitecture(mid,flow.id,{...flow,kind:'flow',action:'UPDATE',trustBoundaryId:boundary.id,crossesTrustBoundary:false,reason:'Boundary'},reviewer,{correlationId:'architecture-fixture'});
    assert.equal(linked.entity!.crossesTrustBoundary,true);await service.editArchitecture(mid,a.id,edit,reviewer);
    detail=await service.detail(mid,owner) as any;assert.equal(detail.controls[0].status,'VERIFICATION_REQUIRED');assert.equal(detail.threats[0].status,'OPEN');assert.equal(detail.threats[0].residualScore,undefined);assert.equal(detail.verifications[0].result,'PASS');
    assert.equal(detail.exceptions.find((item:any)=>item.id===exception.id).status,'APPROVED');assert.equal((await service.governanceDetail(mid,owner)).revision.tier,null);
    await assert.rejects(service.submit(mid,owner),/screening is required/);await assert.rejects(service.decideRiskAcceptance(pending.id,{decision:'APPROVED'},ciso),/fresh architecture/);
    await assert.rejects(service.transitionThreat(th.id,{status:'ACCEPTED',reason:'Old architecture'},reviewer),/current approved/);
    await assert.rejects(pgClient.query('UPDATE threat_model_exceptions SET architecture_version=999 WHERE id=$1',[pending.id]),/immutable/);
    await assert.rejects(pgClient.query('UPDATE threat_model_revisions SET architecture_version=1 WHERE id=$1',[rid]),/server-managed/);
    await assert.rejects(pgClient.query('DELETE FROM threat_model_trust_boundaries WHERE id=$1',[boundary.id]),/Referenced architecture/);
    await assert.rejects(service.editArchitecture(mid,flow.id,{...linked.entity,kind:'flow',action:'UPDATE',destinationComponentId:component.id,reason:'Cross-model'},owner),/current revision/);
    await assert.rejects(service.editArchitecture(mid,flow.id,{...linked.entity,kind:'flow',action:'UPDATE',dataClassification:'HIGHLY_RESTRICTED_HR_LEGAL',reason:'Insufficient clearance'},owner),/restricted/);
    const edits=await Promise.allSettled([service.editArchitecture(mid,flow.id,{...linked.entity,kind:'flow',action:'UPDATE',protocol:'TLS',reason:'A'},reviewer),service.editArchitecture(mid,flow.id,{...linked.entity,kind:'flow',action:'UPDATE',protocol:'HTTP/2',reason:'B'},reviewer)]);assert.equal(edits.filter(result=>result.status==='fulfilled').length,1);
    const currentFlow=(await service.detail(mid,owner) as any).dataFlows[0];
    const raised=await service.editArchitecture(mid,flow.id,{...currentFlow,kind:'flow',action:'UPDATE',dataClassification:'CONFIDENTIAL_SECURITY_ONLY',reason:'Sensitive exchange'},owner);
    assert.equal(((await service.detail(mid,owner) as any).model).dataClassification,'CONFIDENTIAL_SECURITY_ONLY');
    await service.editArchitecture(mid,flow.id,{...raised.entity,kind:'flow',action:'UPDATE',dataClassification:'INTERNAL',reason:'Remove sensitive exchange'},owner);
    assert.equal(((await service.detail(mid,owner) as any).model).dataClassification,'CONFIDENTIAL_SECURITY_ONLY');
    const unused=await service.addComponent(mid,{name:'Unused draft node',type:'OTHER',securityZone:'INTERNAL'},owner);
    assert.equal((await service.editArchitecture(mid,unused.id,{kind:'component',action:'DELETE',contentVersion:unused.contentVersion,reason:'Draft mistake'},owner)).deleted,true);
    const deletion=(await pgClient.query("SELECT old_value,new_value FROM threat_model_audit_events WHERE entity_id=$1 AND action='COMPONENT_REMOVED'",[unused.id])).rows[0];assert.equal(deletion.old_value.name,'Unused draft node');assert.equal(deletion.new_value.entity,null);
    const dataContext=await service.governanceDetail(mid,owner);const priorVersion=dataContext.revision.architecture_version;
    await service.addDataObject(mid,{dataObjectId:dataContext.dataObjects[0].id,componentId:a.id},owner);
    assert.equal((await service.governanceDetail(mid,owner)).revision.architecture_version,priorVersion+1);
    assert.ok((await pgClient.query("SELECT 1 FROM outbox_events WHERE topic='threat-control.verification.required' AND payload->>'threatModelId'=$1 AND payload->>'architectureVersion'=$2",[mid,String(priorVersion+1)])).rowCount);
    const screening=await service.assessApplicability({threatModelId:mid,answers:Object.fromEntries(screeningRules.map(rule=>[rule.signal,false])),justification:'Persisted boundary must win'},owner);assert.ok(screening.tier>=2);
    await verify();await service.submit(mid,owner);await assert.rejects(service.decideApproval(mid,{stage:'APPSEC',decision:'APPROVED'},reviewer),/contributing author/);
    await service.decideApproval(mid,{stage:'APPSEC',decision:'APPROVED'},postReviewer);await service.decideApproval(mid,{stage:'SECURITY_ARCHITECTURE',decision:'APPROVED'},architect);
    assert.equal((await service.releaseGate(mid,owner)).securityGate,'PASS');const report=await service.exportSnapshot(mid,rid,owner);assert.ok(report.snapshot.revision[0].architecture_version>baseline);
    await assert.rejects(service.editArchitecture(mid,b.id,{...b,kind:'component',action:'UPDATE',reason:'Approved edit'},owner),/immutable/);await assert.rejects(pgClient.query("UPDATE threat_model_data_flows SET protocol='HTTP' WHERE id=$1",[flow.id]),/immutable/);
    await service.createRevision(mid,{changeReason:'Next revision'},owner);const copied=await service.detail(mid,owner) as any;assert.equal(copied.dataFlows[0].crossesTrustBoundary,true);assert.equal(copied.dataFlows[0].encryptionInTransit,true);assert.equal(copied.verifications.length,0);assert.equal((await service.exportSnapshot(mid,rid,owner)).sha256,report.sha256);
  });
  await t.test('catalog versions are independently published and shared implementations retain exact verification scope',async()=>{
    const definition={code:`AUTHZ-${suffix.toUpperCase()}`,baseVersion:0,title:'Object authorization',description:'Authorize every protected request',controlFunction:'PREVENTIVE',verificationGuidance:'Exercise positive and negative authorization on every mapped threat'};
    await assert.rejects(catalog.create(definition,owner),/authority/);
    const version=await catalog.create(definition,reviewer);
    await assert.rejects(catalog.create(definition,reviewer),/changed by another/);
    await assert.rejects(catalog.decide(version.id,{decision:'PUBLISHED',reason:'Self publication'},reviewer),/cannot approve/);
    await assert.rejects(pgClient.query("INSERT INTO threat_control_catalog_decisions(id,catalog_version_id,decision,reason,decided_by) VALUES($1,$2,'RETIRED','Invalid skip',$3)",[`invalid-${suffix}`,version.id,architect.id]),/Invalid catalog/);
    await catalog.decide(version.id,{decision:'PUBLISHED',reason:'Independent guidance review'},architect);
    const centralAudit=(await pgClient.query("SELECT action,source_payload FROM audit_events WHERE entity_id=$1 ORDER BY timestamp",[version.id])).rows;
    assert.deepEqual(centralAudit.map(row=>row.action),['THREAT_CONTROL_CATALOG_CREATED','THREAT_CONTROL_CATALOG_PUBLISHED']);
    assert.match(centralAudit[0].source_payload.sha256,/^[a-f0-9]{64}$/);
    await assert.rejects(pgClient.query("UPDATE threat_control_catalog_versions SET title='tamper' WHERE id=$1",[version.id]),/append-only/);
    const newer=await catalog.create({...definition,baseVersion:1,description:'Updated guidance'},reviewer);
    const concurrent=await Promise.allSettled([catalog.create({...definition,baseVersion:2},reviewer),catalog.create({...definition,baseVersion:2},reviewer)]);
    assert.equal(concurrent.filter(result=>result.status==='fulfilled').length,1);
    const created=await service.create({title:'Shared controls fixture',serviceId:appId,criticality:'LOW',dataClassification:'INTERNAL',scopeSummary:'API access',architectureSummary:'Shared API gateway',assumptions:'Authenticated actor',securityObjectives:'Only authorized data access'},owner);
    const sharedModel=String(created.model!.id);
    await service.assessApplicability({threatModelId:sharedModel,answers,justification:'Internal authorization scope'},owner);
    await service.addComponent(sharedModel,{name:'Gateway',type:'API',securityZone:'INTERNAL'},owner);
    const scenario={description:'Unauthorized object read',attackScenario:'Another user attempts object access',categories:['SPOOFING'],inherentLikelihood:2,inherentImpact:2};
    const a=await service.addThreat(sharedModel,{...scenario,title:'Read path A'},owner);
    const b=await service.addThreat(sharedModel,{...scenario,title:'Read path B'},owner);
    await assert.rejects(service.addControl(a.id,{catalogVersionId:newer.id,implementationKey:'gateway'},owner),/published/);
    const shared=await service.addControl(a.id,{catalogVersionId:version.id,implementationKey:'gateway'},owner);
    assert.deepEqual(shared.threatIds,[a.id]);assert.equal(shared.scopeVersion,1);
    await assert.rejects(service.addControl(b.id,{catalogVersionId:version.id,implementationKey:'GATEWAY'},owner),/Duplicate/);
    const evidence=await service.linkEvidence(sharedModel,{attachmentId,controlId:shared.id},owner);
    const verification={result:'PASS',verificationType:'API_SECURITY_TEST',testCase:'Exercise authorization for every mapped threat',expectedResult:'Only authorized reads succeed',evidenceIds:[evidence.id]};
    await service.recordVerification(shared.id,verification,reviewer);
    await service.calculateResidualRisk(a.id,{residualLikelihood:1,residualImpact:1,residualRiskRationale:'Verified read protection'},reviewer);
    await service.transitionThreat(a.id,{status:'MITIGATING',reason:'Implemented'},owner);
    await service.transitionThreat(a.id,{status:'MITIGATED',reason:'Verified'},reviewer);
    await assert.rejects(service.mapControlThreat(modelId,{controlId:shared.id,threatId:b.id,scopeVersion:1,reason:'Cross-model'},owner),/current revision/);
    await assert.rejects(service.mapControlThreat(sharedModel,{controlId:shared.id,threatId:b.id,scopeVersion:1,reason:'Outsider'},outsider),/restricted/);
    const linked=await service.mapControlThreat(sharedModel,{controlId:shared.id,threatId:b.id,scopeVersion:1,reason:'Same gateway implementation covers both paths'},owner);
    assert.equal(linked.scopeVersion,2);assert.equal(linked.status,'VERIFICATION_REQUIRED');assert.equal(linked.threatIds.length,2);
    assert.equal((await pgClient.query('SELECT residual_score,status FROM threats WHERE id=$1',[a.id])).rows[0].residual_score,null);
    await assert.rejects(service.recordVerification(shared.id,{...verification,controlScopeVersion:1},reviewer),/scope is no longer current/);
    await assert.rejects(service.calculateResidualRisk(b.id,{residualLikelihood:1,residualImpact:1,residualRiskRationale:'Reuse old PASS'},reviewer),/current independent verification/);
    await assert.rejects(service.mapControlThreat(sharedModel,{controlId:shared.id,threatId:b.id,scopeVersion:1,reason:'Stale request'},owner),/changed by another/);
    const unmapped=await service.mapControlThreat(sharedModel,{controlId:shared.id,threatId:b.id,scopeVersion:2,action:'UNLINK',reason:'Correct draft scope'},owner);
    assert.equal(unmapped.scopeVersion,3);
    const relinked=await service.mapControlThreat(sharedModel,{controlId:shared.id,threatId:b.id,scopeVersion:3,reason:'Confirm both paths'},owner);
    assert.equal(relinked.scopeVersion,4);
    await service.createRequirement(sharedModel,{title:'Authorize path B',description:'Explicit deny across tenants',ownerId:owner.id,verificationMethod:'API_SECURITY_TEST',threatIds:[b.id],controlIds:[shared.id]},owner);
    await assert.rejects(service.mapControlThreat(sharedModel,{controlId:shared.id,threatId:b.id,scopeVersion:4,action:'UNLINK',reason:'Break requirement'},owner),/requirement mapping/);
    await service.recordVerification(shared.id,{...verification,controlScopeVersion:4},reviewer);
    for(const threat of [a,b]){
      await service.calculateResidualRisk(threat.id,{residualLikelihood:1,residualImpact:1,residualRiskRationale:'Current tests cover both paths'},reviewer);
      if(threat.id===b.id)await service.transitionThreat(threat.id,{status:'MITIGATING',reason:'Implemented'},owner);
      await service.transitionThreat(threat.id,{status:'MITIGATED',reason:'Verified current scope'},reviewer);
    }
    await service.assessApplicability({threatModelId:sharedModel,answers,justification:'Re-screen gateway'},owner);
    await service.submit(sharedModel,owner);
    await service.decideApproval(sharedModel,{stage:'APPSEC',decision:'APPROVED'},reviewer);
    await service.decideApproval(sharedModel,{stage:'SECURITY_ARCHITECTURE',decision:'APPROVED'},architect);
    assert.equal((await service.releaseGate(sharedModel,owner)).securityGate,'PASS');
    const snapshot=await service.exportSnapshot(sharedModel,String(created.revision.id),owner);
    assert.equal(snapshot.snapshot.controlMappings.length,2);assert.equal(snapshot.snapshot.controlDefinitions[0].id,version.id);
    await assert.rejects(pgClient.query('DELETE FROM threat_control_threats WHERE control_id=$1 AND threat_id=$2',[shared.id,b.id]),/immutable/);
    await catalog.decide(version.id,{decision:'RETIRED',reason:'Use revised guidance for new installations'},architect);
    assert.equal((await service.releaseGate(sharedModel,owner)).securityGate,'PASS');
    await service.createRevision(sharedModel,{changeReason:'Material change, preserve implementation scope'},owner);
    const copied=await service.detail(sharedModel,owner) as any;
    assert.equal(copied.controls.length,1);assert.equal(copied.controls[0].threatIds.length,2);assert.equal(copied.controls[0].catalogVersionId,version.id);assert.equal(copied.verifications.length,0);
    assert.equal((await service.governanceDetail(sharedModel,owner)).requirements[0].control_ids[0],copied.controls[0].id);
    await assert.rejects(service.addControl(copied.threats[0].id,{catalogVersionId:version.id,implementationKey:'new-installation'},owner),/published/);
    await assert.rejects(service.mapControlThreat(sharedModel,{controlId:copied.controls[0].id,threatId:a.id,scopeVersion:copied.controls[0].scopeVersion,reason:'Historical scope'},owner),/current revision/);
  });
  await t.test('owning one linked object never grants access to a different scope record',async () => {
    const foreignApp=`foreign-app-${suffix}`;
    await pgClient.query(`INSERT INTO bank_applications(id,code,name,tier,architecture_type,technical_owner_id,business_owner_id) VALUES($1,$1,'Foreign fixture','LOW','MONOLITH',$2,$2)`,[foreignApp,outsider.id]);
    db.data.applications.push({id:foreignApp,name:'Foreign fixture',technicalOwnerId:outsider.id,businessOwnerId:outsider.id} as any);
    await assert.rejects(service.create({title:'Cross-scope bypass',serviceId:foreignApp,releaseId:ticketId,dataClassification:'INTERNAL'},owner),/every linked scope/);
    await assert.rejects(service.create({title:'Admin scope bypass',serviceId:appId,dataClassification:'INTERNAL'},admin),/every linked scope/);
  });
  await t.test('emergency authorization, evidenced execution, independent review and approved revalidation are persistent',async () => {
    await pgClient.query(`INSERT INTO orchestration_business_calendars(id,name,timezone,workdays,business_start,business_end,holidays,is_24x7) VALUES('calendar-bank-baku','Bank calendar','Asia/Baku','[1,2,3,4,5]','09:00','18:00','[]',false) ON CONFLICT(id) DO NOTHING`);
    const created = await service.create({title:'Emergency fixture',serviceId:appId,criticality:'LOW',dataClassification:'INTERNAL'},owner);
    const emergencyModel = String(created.model!.id);
    await pgClient.query('UPDATE threat_models SET change_id=$1 WHERE id=$2',[ticketId,emergencyModel]);
    const approve = async (firstReviewer=reviewer) => {
      await service.assessApplicability({threatModelId:emergencyModel,answers:Object.fromEntries(screeningRules.map(rule=>[rule.signal,false])),justification:'Fixture minimum-impact screening'},owner);
      await service.submit(emergencyModel,owner);
      if(firstReviewer!==reviewer) await assert.rejects(service.decideApproval(emergencyModel,{stage:'APPSEC',decision:'APPROVED'},reviewer),/Author or owner cannot approve/);
      await service.decideApproval(emergencyModel,{stage:'APPSEC',decision:'APPROVED'},firstReviewer);
      await service.decideApproval(emergencyModel,{stage:'SECURITY_ARCHITECTURE',decision:'APPROVED'},architect);
    };
    await approve();
    const assessment = {changeId:ticketId,reason:'Urgent rollback',securityImpact:'No new data or identity boundary; preserve authorization',compensatingControls:'Security monitoring',rollbackPlan:'Restore last approved image'};
    await assert.rejects(service.requestEmergencyChange(emergencyModel,assessment,outsider),/restricted/);
    await assert.rejects(service.requestEmergencyChange(emergencyModel,{...assessment,changeId:'foreign'},owner),/linked/);
    const revoked = await service.requestEmergencyChange(emergencyModel,assessment,owner);
    await assert.rejects(service.requestEmergencyChange(emergencyModel,assessment,owner),/duplicate/);
    assert.equal((await service.releaseGate(emergencyModel,owner)).securityGate,'BLOCK');
    await assert.rejects(service.decideEmergencyChange(emergencyModel,revoked.id,{decision:'APPROVED',reason:'Self approve'}, {...owner,roles:['CISO']}),/cannot approve/);
    await assert.rejects(service.decideEmergencyChange(emergencyModel,revoked.id,{decision:'APPROVED',reason:'Not CISO'},reviewer),/CISO/);
    await service.decideEmergencyChange(emergencyModel,revoked.id,{decision:'APPROVED',reason:'Independent assessment'},ciso);
    await assert.rejects(service.authorizeRelease(emergencyModel,ticketId,reviewer),/explicitly bound/);
    const revokedAuthorization = await service.authorizeRelease(emergencyModel,ticketId,reviewer,revoked.id);
    await service.decideEmergencyChange(emergencyModel,revoked.id,{decision:'REVOKED',reason:'Changed deployment window'},ciso);
    await assert.rejects(service.consumeReleaseAuthorization(emergencyModel,{releaseId:ticketId,authorization:revokedAuthorization.authorization,idempotencyKey:'revoked'},reviewer),/emergency authorization/);
    await assert.rejects(service.decideEmergencyChange(emergencyModel,revoked.id,{decision:'APPROVED',reason:'Renew'},ciso),/new assessment/);
    const emergency = await service.requestEmergencyChange(emergencyModel,assessment,owner);
    await service.decideEmergencyChange(emergencyModel,emergency.id,{decision:'APPROVED',reason:'Independent assessment'},ciso);
    const auth = await service.authorizeRelease(emergencyModel,ticketId,reviewer,emergency.id);
    const consume = await service.consumeReleaseAuthorization(emergencyModel,{releaseId:ticketId,authorization:auth.authorization,idempotencyKey:`emergency-${suffix}`},reviewer);
    const deployment = {authorizationId:consume.authorizationId,executionReference:`external-run-${suffix}`,attachmentId,deployedAt:new Date().toISOString()};
    await assert.rejects(service.recordEmergencyDeployment(modelId,emergency.id,deployment,reviewer),/not found/);
    await assert.rejects(service.recordEmergencyDeployment(emergencyModel,emergency.id,{...deployment,attachmentId:'foreign'},reviewer),/evidence/);
    const result = await service.recordEmergencyDeployment(emergencyModel,emergency.id,deployment,reviewer);
    assert.equal(result.deploymentExecuted,false); assert.equal(result.executionSource,'OPERATOR_ATTESTATION');
    assert.equal((await service.recordEmergencyDeployment(emergencyModel,emergency.id,deployment,reviewer)).status,'DEPLOYED');
    assert.equal(((await service.detail(emergencyModel,owner)).model as any).status,'REVIEW_REQUIRED');
    await assert.rejects(service.recordEmergencyDeployment(emergencyModel,emergency.id,{...deployment,executionReference:'tamper'},reviewer),/immutable/);
    await assert.rejects(pgClient.query("UPDATE threat_emergency_changes SET security_impact='tamper' WHERE id=$1",[emergency.id]),/immutable/);
    await assert.rejects(pgClient.query("UPDATE threat_emergency_changes SET review_due_at=NOW()+INTERVAL '1 year' WHERE id=$1",[emergency.id]),/immutable/);
    await assert.rejects(service.reviewEmergencyChange(emergencyModel,emergency.id,{findings:'Self review',attachmentId},reviewer),/cannot independently/);
    await assert.rejects(service.reviewEmergencyChange(emergencyModel,emergency.id,{findings:'Self review',attachmentId},ciso),/cannot independently/);
    await service.reviewEmergencyChange(emergencyModel,emergency.id,{findings:'Independent post-change security checks passed',attachmentId},architect);
    await assert.rejects(service.closeEmergencyChange(emergencyModel,emergency.id,architect),/post-deployment model/);
    await approve(postReviewer);
    const approvedUpdate = (await service.governanceDetail(emergencyModel,owner)).emergencies.find((item:any)=>item.id===emergency.id) as any;
    assert.ok(approvedUpdate.model_updated_at); assert.equal(approvedUpdate.modelUpdateBreached,false);
    await service.closeEmergencyChange(emergencyModel,emergency.id,architect);
    assert.equal((await service.releaseGate(emergencyModel,owner)).securityGate,'PASS');
    await assert.rejects(pgClient.query("UPDATE threat_emergency_changes SET status='REQUESTED' WHERE id=$1",[emergency.id]),/immutable/);
    const lateId = `late-${suffix}`; const lateAuth = `late-auth-${suffix}`;
    await pgClient.query(`INSERT INTO threat_release_authorizations(id,threat_model_id,revision_id,release_id,issued_by,issued_at,expires_at,consumed_at,consumed_by,consumption_key,gate_snapshot) SELECT $1,threat_model_id,revision_id,release_id,issued_by,NOW()-INTERVAL '20 days',NOW()-INTERVAL '19 days',NOW()-INTERVAL '20 days',consumed_by,$1,gate_snapshot FROM threat_release_authorizations WHERE id=$2`,[lateAuth,auth.authorizationId]);
    await pgClient.query(`INSERT INTO threat_emergency_changes(id,threat_model_id,revision_id,change_id,policy_version_id,calendar_id,calendar_snapshot,status,reason,security_impact,compensating_controls,rollback_plan,requested_by,requested_at,approved_by,approved_at,authorization_expires_at,deployed_by,deployed_at,execution_reference,deployment_attachment_id,release_authorization_id,review_due_at,model_update_due_at) SELECT $1,threat_model_id,revision_id,change_id,policy_version_id,calendar_id,calendar_snapshot,'DEPLOYED','Historical overdue fixture',security_impact,compensating_controls,rollback_plan,requested_by,NOW()-INTERVAL '21 days',approved_by,NOW()-INTERVAL '20 days',NOW()-INTERVAL '19 days',deployed_by,NOW()-INTERVAL '20 days',$1,deployment_attachment_id,$2,NOW()-INTERVAL '18 days',NOW()-INTERVAL '15 days' FROM threat_emergency_changes WHERE id=$3`,[lateId,lateAuth,emergency.id]);
    assert.equal((await service.releaseGate(emergencyModel,owner)).securityGate,'BLOCK');
    const sweeps=await Promise.all([service.maintainGovernance(ciso),service.maintainGovernance(ciso)]);
    assert.ok(sweeps.reduce((sum,result)=>sum+result.emergencyBreaches,0)>=1);
    assert.equal((await pgClient.query("SELECT count(*)::int AS n FROM threat_model_audit_events WHERE entity_id=$1 AND action='EMERGENCY_SLA_BREACHED'",[lateId])).rows[0].n,2);
    assert.equal((await service.maintainGovernance(ciso)).emergencyBreaches,0);
    await assert.rejects(pgClient.query('UPDATE threat_emergency_changes SET review_breached_at=NULL WHERE id=$1',[lateId]),/immutable/);
    await service.reviewEmergencyChange(emergencyModel,lateId,{findings:'Late independent review',attachmentId},architect);
    assert.equal(((await service.governanceDetail(emergencyModel,owner)).emergencies.find((item:any)=>item.id===lateId) as any).reviewBreached,true);
  });
  await t.test('structured data and automatic boundary detection cannot be downgraded by frontend flags',async () => {
    const detail = await service.detail(modelId,owner) as any;
    const sourceId = detail.components[0].id;
    const destination = await service.addComponent(modelId,{name:'Restricted database',type:'DATABASE',securityZone:'RESTRICTED'},owner);
    await assert.rejects(service.addDataFlow(modelId,{name:'Unlabelled boundary',sourceComponentId:sourceId,destinationComponentId:destination.id,crossesTrustBoundary:false},owner),/requires a trust boundary/);
    const boundary = await service.addTrustBoundary(modelId,{name:'Restricted zone',boundaryType:'NETWORK'},owner);
    const flow = await service.addDataFlow(modelId,{name:'Classified flow',sourceComponentId:sourceId,destinationComponentId:destination.id,trustBoundaryId:boundary.id,crossesTrustBoundary:false},owner);
    assert.equal(flow.crossesTrustBoundary,true);
    const data = {name:'Bank data',classification:'RESTRICTED',bankSecrecy:true,ownerId:owner.id,retention:'Bank policy',allowedLocations:'Approved bank locations',encryptionRequirements:'TLS and encrypted storage',flowId:flow.id};
    await assert.rejects(service.addDataObject(modelId,{...data,classification:'PUBLIC'},owner),/at least RESTRICTED/);
    await service.addDataObject(modelId,data,owner);
    const assessment = await service.assessApplicability({threatModelId:modelId,answers:Object.fromEntries(screeningRules.map(rule=>[rule.signal,false])),justification:'Canonical data must win'},owner);
    assert.equal(assessment.tier,3);
    assert.ok(assessment.triggeredConditions.some(condition=>condition.signal==='bankSecrecy'));
    const before = (await service.governanceDetail(modelId,owner)).dataObjects.length;
    await assert.rejects(service.addDataObject(modelId,{...data,name:'Wrong revision',flowId:undefined,componentId:component.id},owner),/current revision/);
    assert.equal((await service.governanceDetail(modelId,owner)).dataObjects.length,before);
  });
});
