/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        semantic: {
          page: 'var(--surface-page)',
          'page-muted': 'var(--surface-page-muted)',
          panel: 'var(--surface-panel)',
          subtle: 'var(--surface-subtle)',
          hover: 'var(--surface-hover)',
          selected: 'var(--surface-selected)',
          primary: 'var(--text-primary)',
          strong: 'var(--text-strong)',
          strongest: 'var(--text-strongest)',
          secondary: 'var(--text-secondary)',
          muted: 'var(--text-muted)',
          placeholder: 'var(--text-placeholder)',
          inverse: 'var(--text-inverse)',
          border: 'var(--border-default)',
          borderSubtle: 'var(--border-subtle)',
          borderStrong: 'var(--border-strong)',
          'border-subtle': 'var(--border-subtle)',
          'border-strong': 'var(--border-strong)',
          focus: 'var(--border-focus)',
          brand: 'var(--color-brand-500)',
          brandHover: 'var(--color-brand-600)',
          'brand-hover-deep': 'var(--color-brand-hover-deep)',
          success: 'var(--status-success-text)',
          successSurface: 'var(--status-success-bg)',
          'success-surface': 'var(--status-success-bg)',
          info: 'var(--status-info-text)',
          infoSurface: 'var(--status-info-bg)',
          'info-surface': 'var(--status-info-bg)',
          infoBorder: 'var(--color-jira-blue-100)',
          warning: 'var(--status-warning-text)',
          warningSurface: 'var(--status-warning-bg)',
          danger: 'var(--status-danger-text)',
          dangerSurface: 'var(--status-danger-bg)',
          dangerBorder: 'var(--color-danger-100)',
          'danger-surface': 'var(--status-danger-bg)',
          'danger-border': 'var(--color-danger-100)',
          'warning-surface': 'var(--color-warning-50)',
          'warning-border': 'var(--color-warning-100)',
          'warning-bright': 'var(--color-warning-bright)',
          'danger-strong': 'var(--color-danger-strong)',
          'brand-danger': 'var(--color-brand-danger)',
          purple: 'var(--color-purple-500)',
          'purple-surface': 'var(--color-purple-50)',
          'purple-border': 'var(--color-purple-100)',
          'content-alt': 'var(--color-content-alt)',
          'jira-muted-alt': 'var(--color-jira-muted-alt)',
          'jira-icon': 'var(--color-jira-icon)',
          'jira-muted-stronger': 'var(--color-jira-muted-stronger)',
          'surface-alt': 'var(--color-surface-alt)',
          'jira-blocked-surface': 'var(--color-jira-blocked-bg)',
          'jira-blocked-border': 'var(--color-jira-blocked-border)',
          'warning-border-strong': 'var(--color-warning-border-strong)',
          dark: 'var(--surface-dark)',
          'dark-inset': 'var(--surface-dark-inset)',
          'dark-selected': 'var(--surface-dark-selected)',
          auth: 'var(--surface-auth)',
          'auth-loading': 'var(--surface-auth-loading)',
          'dark-muted': 'var(--color-dark-text-muted)',
          table: 'var(--color-table-border)',
          'info-soft': 'var(--status-info-soft-bg)',
          'info-soft-border': 'var(--status-info-soft-border)',
          'info-strong': 'var(--status-info-strong-text)',
          'info-hover': 'var(--status-info-hover)',
          'info-cyan': 'var(--status-info-cyan)',
          'jira-soft': 'var(--surface-jira-soft)',
          'jira-soft-border': 'var(--border-jira-soft)',
          'warning-soft': 'var(--status-warning-soft-bg)',
          'warning-soft-border': 'var(--status-warning-soft-border)',
          'warning-strong': 'var(--status-warning-strong-text)',
          'warning-amber': 'var(--status-warning-amber-bg)',
          'warning-highlight': 'var(--status-warning-highlight-bg)',
          'success-soft': 'var(--status-success-soft-bg)',
          'success-soft-border': 'var(--status-success-soft-border)',
          'success-ring': 'var(--status-success-ring)',
          'success-strong-soft': 'var(--status-success-strong-soft-bg)',
          'success-strong-border': 'var(--status-success-strong-border)',
          'success-pale': 'var(--status-success-pale-bg)',
          'success-pale-border': 'var(--status-success-pale-border)',
          'success-strong': 'var(--status-success-strong-text)',
          'success-card': 'var(--surface-success-card)',
          'danger-card': 'var(--surface-danger-card)',
          'warning-card': 'var(--surface-warning-card)',
          'muted-alt': 'var(--text-muted-alt)',
          'neutral-soft': 'var(--surface-neutral-soft)',
          'info-canvas': 'var(--surface-info-canvas)',
          'project-canvas': 'var(--surface-project-canvas)',
          'project-success': 'var(--surface-project-success)',
          'warning-note': 'var(--surface-warning-note)',
          'warning-note-border': 'var(--border-warning-note)',
          'warning-note-text': 'var(--text-warning-note)',
          'warning-legacy': 'var(--surface-warning-legacy)',
          'warning-legacy-border': 'var(--border-warning-legacy)',
          'warning-legacy-text': 'var(--text-warning-legacy)',
          'warning-medium': 'var(--color-warning-medium)',
          'warning-accent': 'var(--color-warning-legacy-accent)',
          'info-utility': 'var(--surface-info-utility)',
          'info-utility-alt': 'var(--surface-info-utility-alt)',
          'info-utility-text': 'var(--text-info-utility)',
          'info-utility-border': 'var(--border-info-utility)',
          'danger-utility': 'var(--surface-danger-utility)',
          'danger-critical': 'var(--surface-danger-critical)',
          'danger-critical-border': 'var(--border-danger-critical)',
          'danger-critical-text': 'var(--text-danger-critical)',
          'purple-muted': 'var(--text-purple-muted)',
          'success-hover': 'var(--color-success-hover)',
          'brand-ink-hover': 'var(--color-brand-ink-hover)',
          'jira-brand-hover': 'var(--color-jira-blue-hover)',
          'jira-brand-active': 'var(--color-jira-blue-active)',
          'jira-border-muted': 'var(--border-jira-muted)',
          'auth-overlay': 'var(--surface-auth-overlay)',
          'auth-portal': 'var(--surface-auth-portal)',
          'modal-tint': 'var(--surface-modal-tint)',
          'project-border': 'var(--border-project)',
          'project-border-strong': 'var(--border-project-strong)',
          'purple-soft': 'var(--color-purple-soft)',
          'purple-strong': 'var(--color-purple-600)',
          'brand-ink': 'var(--color-brand-ink)',
          'jira-muted': 'var(--color-jira-muted)',
          'jira-muted-strong': 'var(--color-jira-muted-strong)',
          'jira-muted-light': 'var(--color-jira-muted-light)',
          'jira-primary': 'var(--color-jira-text)',
          'jira-brand': 'var(--color-jira-blue-500)',
          'jira-brand-surface': 'var(--color-jira-brand-surface)',
          'jira-border': 'var(--color-jira-border)',
          'jira-hover': 'var(--color-jira-hover)',
          'jira-surface': 'var(--color-jira-surface-muted)',
          'neutral-surface': 'var(--color-neutral-250)',
          'success-border': 'var(--color-brand-100)',
          'info-border': 'var(--color-info-100)',
          'jira-info-border': 'var(--color-jira-info-border)',
        },
        wrike: {
          green: 'var(--color-brand-500)',
          greenHover: 'var(--color-brand-600)',
          greenLight: 'var(--color-brand-50)',
          greenDark: 'var(--color-brand-700)',
          greenAccent: 'var(--color-brand-accent)',
          midnight: 'var(--color-neutral-900)',
          midnightFair: 'var(--color-brand-ink)',
          midnightMiddle: 'var(--color-jira-muted-strong)',
          midnightLight: 'var(--color-neutral-400)',
          bg: 'var(--surface-page)',
          surface: 'var(--surface-panel)',
          surfaceSecondary: 'var(--surface-subtle)',
          border: 'var(--border-default)',
          borderSubtle: 'var(--border-subtle)',
          blue: 'var(--color-info-500)',
          blueLight: 'var(--color-info-50)',
          red: 'var(--color-brand-danger)',
          redLight: 'var(--color-danger-50)',
          amber: 'var(--color-warning-accent)',
          amberLight: 'var(--color-warning-50)',
          purple: 'var(--color-purple-500)',
          purpleLight: 'var(--color-purple-soft)',
        },
      },
      fontSize: {
        label: ['var(--font-size-label)', { lineHeight: '1rem' }],
        caption: ['var(--font-size-caption)', { lineHeight: '0.875rem' }],
        micro: ['var(--font-size-micro)', { lineHeight: '0.75rem' }],
        overline: ['var(--font-size-overline)', { lineHeight: '0.75rem' }],
        '2xs': ['0.75rem', { lineHeight: '1.05rem' }],       // 12px
        'xs': ['0.84rem', { lineHeight: '1.25rem' }],        // ~13.5px
        'sm': ['0.95rem', { lineHeight: '1.4rem' }],         // ~15.2px
        'base': ['1.05rem', { lineHeight: '1.55rem' }],      // ~16.8px
        'md': ['1.125rem', { lineHeight: '1.65rem' }],       // 18px
        'lg': ['1.25rem', { lineHeight: '1.75rem' }],        // 20px
        'xl': ['1.4rem', { lineHeight: '1.9rem' }],          // 22.4px
        '2xl': ['1.7rem', { lineHeight: '2.2rem' }],         // 27.2px
        '3xl': ['2.1rem', { lineHeight: '2.6rem' }],         // 33.6px
      },
      fontFamily: {
        sans: ['var(--font-family-sans)'],
        mono: ['var(--font-family-mono)'],
      },
      spacing: {
        ds0: 'var(--space-0)',
        ds1: 'var(--space-1)',
        ds2: 'var(--space-2)',
        ds3: 'var(--space-3)',
        ds4: 'var(--space-4)',
        ds5: 'var(--space-5)',
        ds6: 'var(--space-6)',
        ds8: 'var(--space-8)',
        ds10: 'var(--space-10)',
        ds12: 'var(--space-12)',
      },
      minWidth: {
        dsFilter: 'var(--size-filter-min-width)',
        dsTimeline: 'var(--size-timeline-min-width)',
      },
      maxWidth: {
        dsContent: 'var(--size-content-wide)',
        dsTruncateCompact: 'var(--size-truncate-compact)',
        dsTruncateWide: 'var(--size-truncate-wide)',
      },
      minHeight: {
        dsCalendarCell: 'var(--size-calendar-cell-height)',
      },
      maxHeight: {
        dsModal: 'var(--size-modal-max-height)',
        dsModalCompact: 'var(--size-modal-max-height-compact)',
      },
      borderRadius: {
        dsXs: 'var(--radius-xs)',
        dsSm: 'var(--radius-sm)',
        dsMd: 'var(--radius-md)',
        dsLg: 'var(--radius-lg)',
        dsXl: 'var(--radius-xl)',
        dsFull: 'var(--radius-full)',
      },
      transitionDuration: {
        dsFast: 'var(--duration-fast)',
        dsNormal: 'var(--duration-normal)',
        dsSlow: 'var(--duration-slow)',
      },
      zIndex: {
        // Legacy feature modals still use z-modal; keep it mapped to the
        // shared modal token until those JSX surfaces are migrated.
        modal: 'var(--z-modal)',
        dsBase: 'var(--z-base)',
        dsContent: 'var(--z-content)',
        dsSticky: 'var(--z-sticky)',
        dsHeader: 'var(--z-header)',
        dsFloating: 'var(--z-floating)',
        dsDropdown: 'var(--z-dropdown)',
        dsOverlay: 'var(--z-overlay)',
        dsModal: 'var(--z-modal)',
        dsToast: 'var(--z-toast)',
        dsDialog: 'var(--z-dialog)',
      },
      boxShadow: {
        'wrike-xs': 'var(--shadow-xs)',
        'wrike-sm': 'var(--shadow-sm)',
        'wrike-md': 'var(--shadow-md)',
        'wrike-lg': 'var(--shadow-lg)',
        modal: 'var(--shadow-modal)',
        'brand-glow': 'var(--shadow-brand-glow)',
        'brand-soft': 'var(--shadow-brand-soft)',
      },
    },
  },
  plugins: [],
}
