import React,{useEffect,useState} from 'react';
import type {ThreatModelDetail} from './ThreatModelDetailPanel.js';
type Props={detail:ThreatModelDetail;mutable:boolean;fetchWithAuth:(url:string,options?:RequestInit)=>Promise<Response>;onRefresh:()=>Promise<void>};
const input='jira-input mt-1 w-full';
type Node={key:string;parentKey:string|null;kind:'STEP'|'AND'|'OR';label:string};
export function ThreatAnalysisEditor({detail,mutable,fetchWithAuth,onRefresh}:Props){
  const [data,setData]=useState<any>();const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [offset,setOffset]=useState(0);const [refresh,setRefresh]=useState(0);
  const [selected,setSelected]=useState<any>();const [decision,setDecision]=useState('ACCEPTED');const [content,setContent]=useState('');const [caseThreat,setCaseThreat]=useState<any>();
  const [nodes,setNodes]=useState<Node[]>([{key:'root',parentKey:null,kind:'STEP',label:''}]);
  const base=`/api/threat-models/${detail.model.id}/analysis`;
  useEffect(()=>{const controller=new AbortController();setError('');setData(undefined);void fetchWithAuth(`${base}?offset=${offset}&limit=25`,{signal:controller.signal}).then(async response=>{const result=await response.json();if(!response.ok||!result.success)throw new Error(result.error||'Analysis load failed');if(!controller.signal.aborted)setData(result.analysis);}).catch(cause=>{if(!controller.signal.aborted)setError(cause.message);});return()=>controller.abort();},[base,offset,refresh,fetchWithAuth]);
  const post=async(path:string,payload:unknown)=>{setBusy(true);setError('');setNotice('');try{const response=await fetchWithAuth(base+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok||!result.success)throw new Error(result.error||'Analysis operation failed');await onRefresh();setRefresh(value=>value+1);setSelected(undefined);setCaseThreat(undefined);setNotice('Saved to the server. No approval or verification was granted.');return true;}catch(cause){setError(cause instanceof Error?cause.message:'Operation failed');return false;}finally{setBusy(false);}};
  const submit=(event:React.FormEvent<HTMLFormElement>,path:string,transform:(form:FormData)=>unknown)=>{event.preventDefault();try{void post(path,transform(new FormData(event.currentTarget)));}catch(cause){setError(cause instanceof Error?cause.message:'Invalid form');}};
  const field=(name:string,label:string,multiline=false)=><label>{label}{multiline?<textarea name={name} className={input} required maxLength={10000}/>:<input name={name} className={input} required maxLength={255}/>}</label>;
  return <section className="space-y-4">
    <p>Candidate hypotheses are not confirmed threats. Only a security analyst may accept, modify, reject or correlate a duplicate. Architecture changes make earlier candidates stale.</p>
    {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
    <form onSubmit={event=>submit(event,'/suggest',form=>({componentId:form.get('componentId')}))}><fieldset disabled={!mutable||busy} className="flex gap-3 items-end"><label>Persisted component<select name="componentId" required className={input}><option value="">Select…</option>{detail.components.map(node=><option key={node.id} value={node.id}>{node.name}</option>)}</select></label><button className="jira-btn-primary">Generate STRIDE candidates</button></fieldset></form>
    <details><summary>Import externally generated candidate with provenance</summary><form onSubmit={event=>submit(event,'/import',form=>({...Object.fromEntries(form),content:JSON.parse(String(form.get('content')))}))}><fieldset disabled={!mutable||busy} className="grid md:grid-cols-2 gap-3"><label>Source<select className={input} name="source"><option>AI_ASSISTED</option><option>IMPORT</option></select></label>{field('provider','Provider / source system')}{field('modelVersion','Model / source version')}{field('provenanceReference','Source run / record reference')}<label className="md:col-span-2">Full candidate JSON<textarea className={input} name="content" required maxLength={100000}/></label><p>Provenance is recorded as USER_SUPPLIED. This does not claim the platform called or validated an AI provider.</p><button className="jira-btn-primary">Import as pending suggestion</button></fieldset></form></details>
    {!data?<button type="button" onClick={()=>setRefresh(value=>value+1)}>Reload analysis</button>:<>
      <ul className="space-y-2">{data.suggestions.map((item:any)=><li key={item.id} className="border border-semantic-jira-border p-3 rounded"><p>{item.proposed_content.title} · {item.decision||'SUGGESTED'} {item.stale&&'· STALE'}</p><p>{item.source} · {item.provenance_kind} · {item.provider||item.rule_version} {item.model_version} · architecture v{item.architecture_version}</p><details><summary>Candidate, provenance and decision</summary><p>{item.provenance_reference}</p><pre className="whitespace-pre-wrap">{JSON.stringify(item.proposed_content,null,2)}</pre><p>{item.reason} {item.threat_id} {item.decided_by}</p></details>{!item.decision&&<button disabled={!mutable||busy} className="jira-btn-subtle" onClick={()=>{setSelected(item);setDecision(item.stale?'REJECTED':'ACCEPTED');setContent(JSON.stringify(item.proposed_content,null,2));}}>Record analyst disposition</button>}</li>)}</ul>
      <div className="flex gap-3"><button disabled={!offset} onClick={()=>setOffset(value=>Math.max(0,value-25))}>Previous</button><button disabled={!data.hasMore} onClick={()=>setOffset(value=>value+25)}>Next</button></div>
      {selected&&<form onSubmit={event=>submit(event,`/suggestions/${selected.id}/disposition`,form=>({decision,reason:form.get('reason'),...(decision==='DUPLICATE'?{threatId:form.get('threatId')}:{ }),...(decision==='MODIFIED'?{content:JSON.parse(content)}:{})}))}><fieldset disabled={!mutable||busy} className="grid gap-3"><p>{selected.proposed_content.title}</p><select className={input} value={decision} onChange={event=>setDecision(event.target.value)}>{['ACCEPTED','MODIFIED','REJECTED','DUPLICATE'].map(value=><option disabled={selected.stale&&['ACCEPTED','MODIFIED'].includes(value)} key={value}>{value}</option>)}</select>{field('reason','Analyst reasoning',true)}{decision==='DUPLICATE'&&<label>Existing threat<select className={input} name="threatId" required><option value="">Select…</option>{detail.threats.map(threat=><option key={threat.id} value={threat.id}>{threat.key} · {threat.title}</option>)}</select></label>}{decision==='MODIFIED'&&<label>Assessed full threat content<textarea className={input} required maxLength={100000} value={content} onChange={event=>setContent(event.target.value)}/></label>}<button className="jira-btn-primary">Record immutable disposition</button></fieldset></form>}
      <details><summary>Add abuse case / attack tree</summary><form onSubmit={event=>submit(event,'/cases',form=>({...Object.fromEntries(form),threatId:caseThreat?.id,contentVersion:caseThreat?.contentVersion,nodes}))}><fieldset disabled={!mutable||busy} className="grid gap-3"><label>Threat<select className={input} required value={caseThreat?.id||''} onChange={event=>setCaseThreat(detail.threats.find(threat=>threat.id===event.target.value))}><option value="">Select…</option>{detail.threats.map(threat=><option key={threat.id} value={threat.id}>{threat.key} · {threat.title}</option>)}</select></label>{caseThreat&&caseThreat.contentVersion!==detail.threats.find(threat=>threat.id===caseThreat.id)?.contentVersion&&<p role="alert">Threat changed. Re-select it to capture the current version.</p>}{field('title','Case title')}{field('objective','Attacker objective',true)}{field('assumptions','Explicit assumptions',true)}<label>Methodology<select className={input} name="methodology"><option>ABUSE_CASE</option><option>ATTACK_TREE</option></select></label><p>One root. AND/OR nodes need at least two children; STEP nodes are leaves.</p>{nodes.map((node,index)=><div key={node.key} className="grid md:grid-cols-3 gap-2"><label>{node.key}<input className={input} required maxLength={2000} value={node.label} onChange={event=>setNodes(items=>items.map(item=>item.key===node.key?{...item,label:event.target.value}:item))}/></label><select className={input} value={node.kind} onChange={event=>setNodes(items=>items.map(item=>item.key===node.key?{...item,kind:event.target.value as Node['kind']}:item))}>{['STEP','AND','OR'].map(value=><option key={value}>{value}</option>)}</select>{index>0&&<select className={input} value={node.parentKey||'root'} onChange={event=>setNodes(items=>items.map(item=>item.key===node.key?{...item,parentKey:event.target.value}:item))}>{nodes.slice(0,index).map(parent=><option key={parent.key} value={parent.key}>{parent.key}: {parent.label}</option>)}</select>}</div>)}<button type="button" disabled={nodes.length>=100} onClick={()=>setNodes(items=>[...items,{key:`node${items.length}`,parentKey:'root',kind:'STEP',label:''}])}>Add child node</button><button type="button" disabled={nodes.length<=1} onClick={()=>setNodes(items=>items.slice(0,-1))}>Remove last unsaved node</button><button className="jira-btn-primary">Save analysis and invalidate verification scope</button></fieldset></form></details>
      {data.cases.map((item:any)=><details key={item.id}><summary>{item.title} · {item.methodology}</summary><p>{item.objective}</p><p>Assumptions: {item.assumptions}</p><ul>{item.nodes.map((node:any)=><li key={node.id}>{node.ordinal+1}. {node.node_kind}: {node.label} · parent {node.parent_id?item.nodes.findIndex((parent:any)=>parent.id===node.parent_id)+1:'root'}</li>)}</ul></details>)}
    </>}
  </section>;
}
