import React,{useEffect,useState} from 'react';
import type {ThreatModelDetail} from './ThreatModelDetailPanel.js';

type Props={detail:ThreatModelDetail;mutable:boolean;fetchWithAuth:(url:string,options?:RequestInit)=>Promise<Response>;onRefresh:()=>Promise<void>};
export function ThreatControlCatalogEditor({detail,mutable,fetchWithAuth,onRefresh}:Props){
  const [catalog,setCatalog]=useState<any[]>([]);const [search,setSearch]=useState('');const [query,setQuery]=useState('');const [offset,setOffset]=useState(0);const [reload,setReload]=useState(0);
  const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
  const [scopeChoice,setScopeChoice]=useState<{id:string;version:number}>();
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');
    void fetchWithAuth(`/api/threat-control-catalog?limit=25&offset=${offset}&search=${encodeURIComponent(query)}`,{signal:controller.signal}).then(async response=>{
      const result=await response.json();if(!response.ok||!result.success)throw new Error(result.error||'Catalog load failed.');if(!controller.signal.aborted)setCatalog(result.definitions);
    }).catch(cause=>{if(!controller.signal.aborted)setError(cause.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();
  },[query,offset,reload]);
  const field=(name:string,label:string,type='text',value='')=><label>{label}<input name={name} type={type} defaultValue={value} required className="jira-input mt-1 w-full"/></label>;
  const select=(name:string,label:string,items:any[])=><label>{label}<select name={name} required className="jira-input mt-1 w-full" defaultValue="" onChange={event=>{if(name==='controlId')setScopeChoice({id:event.target.value,version:detail.controls.find(control=>control.id===event.target.value)?.scopeVersion || 1});}}><option value="">Select…</option>{items.map(item=><option key={item.id} value={item.id}>{item.code ? `${item.code} v${item.version} · ` : ''}{item.title || item.key} {item.status ? `· ${item.status}` : ''}</option>)}</select></label>;
  const save=(label:string)=><button type="submit" disabled={busy} className="jira-btn-primary">{label}</button>;
  const submit=async(event:React.FormEvent<HTMLFormElement>,path:(form:FormData)=>string,body:(form:FormData)=>unknown=Object.fromEntries)=>{
    event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);setError('');
    try{const response=await fetchWithAuth(path(form),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body(form))});const result=await response.json();if(!response.ok||!result.success)throw new Error(result.error||'Control operation failed.');await onRefresh();setReload(value=>value+1);}
    catch(cause){setError(cause instanceof Error?cause.message:'Control operation failed.');}finally{setBusy(false);}
  };
  return <section className="space-y-4">
    <p>Catalog definitions are reusable guidance, not evidence of effectiveness. Each implementation retains its own owner, ticket, threat scope and independent verification. Do not put credentials or secrets in the catalog.</p>
    {error&&<div role="alert" className="text-semantic-danger border p-3 rounded">{error}<button type="button" className="jira-btn-subtle ml-2" onClick={()=>setReload(value=>value+1)}>Reload catalog</button></div>}
    <form onSubmit={event=>{event.preventDefault();setOffset(0);setQuery(search);}} className="flex gap-2"><input aria-label="Search control catalog" className="jira-input" value={search} onChange={event=>setSearch(event.target.value)}/><button className="jira-btn-subtle">Search</button></form>
    {loading?<p>Loading catalog…</p>:<ul className="space-y-2">{catalog.map(item=><li key={item.id} className="border border-semantic-jira-border p-3 rounded"><strong>{item.code} v{item.version} · {item.title}</strong> · {item.control_function} · {item.status}<p>{item.description}</p><p>Verify: {item.verification_guidance}</p>{item.reference_url&&<a href={item.reference_url} target="_blank" rel="noopener noreferrer">Reference source</a>}</li>)}</ul>}
    <div className="flex gap-2"><button className="jira-btn-subtle" disabled={!offset||loading} onClick={()=>setOffset(value=>Math.max(0,value-25))}>Previous</button><span>Page {offset/25+1}</span><button className="jira-btn-subtle" disabled={catalog.length<25||loading} onClick={()=>setOffset(value=>value+25)}>Next</button></div>
    <details><summary>Create immutable catalog version (AppSec)</summary><form onSubmit={event=>void submit(event,()=>'/api/threat-control-catalog',form=>({...Object.fromEntries(form),baseVersion:Number(form.get('baseVersion'))}))}><fieldset disabled={busy} className="grid md:grid-cols-2 gap-3 mt-3">
      {field('code','Canonical code, e.g. AUTHZ-OBJECT')}{field('baseVersion','Current latest version (0 for a new code)','number','0')}{field('title','Control title')}{field('description','Control purpose and implementation guidance')}<label>Function<select name="controlFunction" className="jira-input mt-1 w-full">{['PREVENTIVE','DETECTIVE','CORRECTIVE','COMPENSATING'].map(value=><option key={value}>{value}</option>)}</select></label>{field('verificationGuidance','How effectiveness must be tested')}{save('Create draft catalog version')}
    </fieldset></form></details>
    <details><summary>Independent catalog publication / retirement</summary><form onSubmit={event=>void submit(event,form=>`/api/threat-control-catalog/${form.get('definitionId')}/decision`,form=>({decision:form.get('decision'),reason:form.get('reason')}))}><fieldset disabled={busy} className="grid gap-3 mt-3">{select('definitionId','Version from the current catalog page',catalog.filter(item=>item.status!=='RETIRED'))}<label>Decision<select name="decision" className="jira-input mt-1 w-full"><option>PUBLISHED</option><option>RETIRED</option></select></label>{field('reason','Independent decision rationale')}{save('Record catalog decision')}</fieldset></form></details>
    <details open><summary>Instantiate a published control in this model</summary><form onSubmit={event=>void submit(event,form=>`/api/threats/${form.get('threatId')}/catalog-controls`,form=>({catalogVersionId:form.get('catalogVersionId'),implementationKey:form.get('implementationKey'),description:form.get('description')}))}><fieldset disabled={!mutable||busy} className="grid gap-3 mt-3">{select('catalogVersionId','Published definition from current page',catalog.filter(item=>item.status==='PUBLISHED'))}{select('threatId','Initial threat',detail.threats)}{field('implementationKey','Stable implementation scope key, e.g. payments-api-authz')}{field('description','Concrete implementation and acceptance criteria')}{save('Create implementation and remediation workflow')}</fieldset></form></details>
    <div><h4>Current implementations</h4><ul>{detail.controls.map(control=><li key={control.id}>{control.title} · {control.catalogCode ? `${control.catalogCode} v${control.catalogVersion}` : 'Uncatalogued legacy/custom control'} · scope v{control.scopeVersion} · {control.status}<p>{(control.threatIds||[control.threatId]).map((id:string)=>detail.threats.find(threat=>threat.id===id)?.title||id).join(' / ')}</p></li>)}</ul></div>
    <form onSubmit={event=>void submit(event,()=>`/api/threat-models/${detail.model.id}/control-threat-mappings`,form=>({...Object.fromEntries(form),scopeVersion:scopeChoice?.id===form.get('controlId')?scopeChoice.version:0}))}><fieldset disabled={!mutable||busy} className="grid gap-3">{select('controlId','Existing implementation',detail.controls)}{select('threatId','Threat to link or unlink',detail.threats)}<label>Mapping action<select name="action" className="jira-input mt-1 w-full"><option>LINK</option><option>UNLINK</option></select></label>{field('reason','Scope-change rationale')}{save('Change scope and require re-verification')}</fieldset><p>Changing scope invalidates the previous PASS and mapped residual-risk decisions. Approved revisions are immutable. The original anchor and requirement-dependent mappings cannot be removed.</p></form>
  </section>;
}
