import React,{useEffect,useState} from 'react';
import type {ThreatModelDetail} from './ThreatModelDetailPanel.js';
type Props={detail:ThreatModelDetail;mutable:boolean;fetchWithAuth:(url:string,options?:RequestInit)=>Promise<Response>;onRefresh:()=>Promise<void>};
const input='jira-input mt-1 w-full';
export function ThreatFindingEditor({detail,mutable,fetchWithAuth,onRefresh}:Props){
  const [links,setLinks]=useState<any[]>([]);const [refresh,setRefresh]=useState(0);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [kind,setKind]=useState('cmdbFindingId');const [selected,setSelected]=useState<any>();
  const base=`/api/threat-models/${detail.model.id}/finding-links`;
  useEffect(()=>{const controller=new AbortController();void fetchWithAuth(base,{signal:controller.signal}).then(async response=>{const result=await response.json();if(!response.ok||!result.success)throw new Error(result.error||'Finding correlations unavailable');if(!controller.signal.aborted)setLinks(result.links);}).catch(cause=>{if(!controller.signal.aborted)setError(cause.message);});return()=>controller.abort();},[base,refresh,fetchWithAuth]);
  const submit=async(event:React.FormEvent<HTMLFormElement>,assessment=false)=>{event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);setError('');setNotice('');try{const response=await fetchWithAuth(assessment?`${base}/${selected.id}/assessment`:base,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(assessment?{fingerprint:selected.current_fingerprint,reason:form.get('reason')}:{threatId:form.get('threatId'),controlId:form.get('controlId'),[kind]:form.get('sourceId'),assumption:form.get('assumption')})});const result=await response.json();if(!response.ok||!result.success)throw new Error(result.error||'Finding operation failed');await onRefresh();setRefresh(value=>value+1);setSelected(undefined);setNotice('Persisted. The control still requires fresh independent verification.');}catch(cause){setError(cause instanceof Error?cause.message:'Operation failed');}finally{setBusy(false);}};
  return <section className="space-y-4"><p>Correlate only canonical CMDB findings or security tickets already in this architecture scope. Closing a finding never verifies a control. Source security changes block the gate immediately and scheduled maintenance creates a revalidation draft.</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
    <form onSubmit={event=>void submit(event)}><fieldset disabled={!mutable||busy} className="grid md:grid-cols-2 gap-3"><label>Threat<select name="threatId" className={input} required><option value="">Select…</option>{detail.threats.map(item=><option key={item.id} value={item.id}>{item.key} · {item.title}</option>)}</select></label><label>Mapped control<select name="controlId" className={input} required><option value="">Select…</option>{detail.controls.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Canonical source<select className={input} value={kind} onChange={event=>setKind(event.target.value)}><option value="cmdbFindingId">CMDB / Cortex finding</option><option value="findingTicketId">Security ticket (SAST/SCA/DAST/manual)</option></select></label><label>Existing finding ID<input name="sourceId" className={input} required maxLength={64}/></label><label>Control assumption contradicted by this finding<textarea name="assumption" className={input} required maxLength={4000}/></label><button className="jira-btn-primary">Link canonical finding</button></fieldset></form>
    <ul className="space-y-2">{links.map(link=><li className="border border-semantic-jira-border rounded p-3" key={link.id}><p>{link.cmdb_finding_id||link.finding_ticket_id} · {link.current_state||'UNAVAILABLE'} · {link.current_severity}</p><p>{link.assumption}</p><p>{link.current_fingerprint===(link.assessed_fingerprint||link.source_fingerprint)?'Source matches recorded assessment':'SOURCE CHANGED — reassessment required'}</p><button className="jira-btn-subtle" disabled={!mutable||busy} onClick={()=>setSelected({...link})}>Assess current source state</button></li>)}</ul>
    {selected&&<form onSubmit={event=>void submit(event,true)}><fieldset disabled={!mutable||busy}><p>Assessment of {selected.cmdb_finding_id||selected.finding_ticket_id} · {selected.current_state}</p><label>Analyst reasoning<textarea name="reason" className={input} required maxLength={4000}/></label><button className="jira-btn-primary">Record assessment and require verification</button></fieldset></form>}
  </section>;
}
