import React, { useEffect, useState } from 'react';
import { Settings2, Save, Plus } from 'lucide-react';
import type { BankUser } from '../../../shared/types/auth.js';

type FetchWithAuth = (url: string, options?: RequestInit) => Promise<Response>;
const signalDefaults = ['internetExposed', 'customerData', 'confidentialData', 'financialTransactions', 'authenticationChange', 'authorizationChange', 'privilegedCapability', 'externalApi', 'trustBoundary', 'thirdPartyIntegration', 'cloudDeployment', 'newDataStore', 'cryptography', 'secretsHandling', 'paymentRelated', 'coreBankingRelated', 'iamPamRelated', 'criticalInfrastructure', 'materialArchitectureChange', 'highCriticalAsset', 'securityIncidentDriven'];
const dayDefaults = { CRITICAL: 1, HIGH: 14, MEDIUM: 30, LOW: 90 };

export const ThreatModelGovernancePanel: React.FC<{ fetchWithAuth: FetchWithAuth; currentUser?: BankUser | null; onError: (message: string) => void }> = ({ fetchWithAuth, currentUser, onError }) => {
  const [policy, setPolicy] = useState<any>(null); const [backlog, setBacklog] = useState<any[]>([]); const [busy, setBusy] = useState(false);
  const [item, setItem] = useState({ systemName: '', tier: 'TIER_1', status: 'NOT_STARTED', criticality: 'HIGH', targetDate: '', notes: '' });
  const canAdmin = Boolean(currentUser?.roles.some((role) => ['PLATFORM_ADMIN', 'CISO', 'INFOSEC_ADMIN', 'INFOSEC_MANAGER', 'APPSEC_ANALYST', 'GRC_ANALYST'].includes(role)));
  const canPolicy = Boolean(currentUser?.roles.some((role) => ['PLATFORM_ADMIN', 'CISO', 'INFOSEC_ADMIN', 'INFOSEC_MANAGER'].includes(role)));
  const load = async () => {
    if (!canAdmin) return;
    try {
      const [policyRes, backlogRes] = await Promise.all([fetchWithAuth('/api/threat-model-policy'), fetchWithAuth('/api/threat-model-migration-backlog')]);
      const policyData = await policyRes.json(); const backlogData = await backlogRes.json();
      if (policyData.success) setPolicy(policyData.policy?.policy || policyData.policy); else onError(policyData.error || 'Threat Model policy could not be loaded.');
      if (backlogData.success) setBacklog(backlogData.backlog || []); else onError(backlogData.error || 'Migration backlog could not be loaded.');
    } catch (error) { onError(error instanceof Error ? error.message : 'Threat Model governance data could not be loaded.'); }
  };
  useEffect(() => { void load(); }, [canAdmin]);
  const savePolicy = async (event: React.FormEvent) => {
    event.preventDefault(); if (!canPolicy || !policy) return; setBusy(true);
    try {
      const response = await fetchWithAuth('/api/threat-model-policy', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ organizationId: 'org-bank', policy }) }); const data = await response.json();
      if (!data.success) throw new Error(data.error || 'Policy could not be saved.'); await load();
    } catch (error) { onError(error instanceof Error ? error.message : 'Policy could not be saved.'); } finally { setBusy(false); }
  };
  const saveBacklog = async (event: React.FormEvent) => {
    event.preventDefault(); if (!canAdmin) return; setBusy(true);
    try {
      const response = await fetchWithAuth('/api/threat-model-migration-backlog', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...item, organizationId: 'org-bank' }) }); const data = await response.json();
      if (!data.success) throw new Error(data.error || 'Backlog entry could not be saved.'); setItem({ systemName: '', tier: 'TIER_1', status: 'NOT_STARTED', criticality: 'HIGH', targetDate: '', notes: '' }); await load();
    } catch (error) { onError(error instanceof Error ? error.message : 'Backlog entry could not be saved.'); } finally { setBusy(false); }
  };
  if (!canAdmin) return null;
  const field = 'jira-input mt-1 w-full';
  return <section className="bg-semantic-panel border border-semantic-jira-border rounded-md p-5 space-y-5"><div className="flex items-center gap-2"><Settings2 className="w-4 h-4 text-semantic-jira-brand" /><div><h2 className="font-bold text-semantic-jira-primary">Threat Model governance administration</h2><p className="text-xs text-semantic-jira-muted">Policy changes and migration coverage are persisted and audited server-side.</p></div></div>{policy && <form onSubmit={savePolicy} className="grid md:grid-cols-2 xl:grid-cols-4 gap-3 border-t border-semantic-jira-border pt-4"><label className="text-xs">Review frequency (days)<input className={field} type="number" min="1" max="730" value={policy.reviewFrequencyDays || 365} onChange={(event) => setPolicy({ ...policy, reviewFrequencyDays: Number(event.target.value) })} /></label><label className="text-xs">Release-blocking severities<select className={field} multiple value={policy.releaseBlockingSeverities || []} onChange={(event) => setPolicy({ ...policy, releaseBlockingSeverities: [...event.currentTarget.selectedOptions].map((option) => option.value) })}>{['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-xs">Required approval stages<select className={field} multiple value={policy.requiredApprovalStages || []} onChange={(event) => setPolicy({ ...policy, requiredApprovalStages: [...event.currentTarget.selectedOptions].map((option) => option.value) })}>{['APPSEC', 'SECURITY_ARCHITECTURE', 'RISK_AUTHORITY'].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-xs">Required signals (comma-separated)<textarea className={field} rows={3} value={(policy.requiredSignals || signalDefaults).join(', ')} onChange={(event) => setPolicy({ ...policy, requiredSignals: event.target.value.split(',').map((value) => value.trim()).filter(Boolean) })} /></label><Thresholds label="Remediation SLA (days)" values={policy.remediationSlaDays || dayDefaults} onChange={(values) => setPolicy({ ...policy, remediationSlaDays: values })} /><Thresholds label="Max exception duration (days)" values={policy.maxExceptionDays || { CRITICAL: 30, HIGH: 90, MEDIUM: 180, LOW: 365 }} onChange={(values) => setPolicy({ ...policy, maxExceptionDays: values })} /><Thresholds label="Verification expiry (days)" values={policy.verificationExpirationDays || { DEFAULT: 90, SAST: 30, SCA: 30, DAST: 30, PENETRATION_TEST: 180 }} onChange={(values) => setPolicy({ ...policy, verificationExpirationDays: values })} /><div className="flex items-end">{canPolicy ? <button disabled={busy} className="jira-btn-primary w-full"><Save className="w-4 h-4" />Save policy</button> : <span className="text-xs text-semantic-jira-muted">Only CISO or platform security administrators can change policy.</span>}</div></form>}
    <div className="grid xl:grid-cols-[1fr_360px] gap-5 border-t border-semantic-jira-border pt-4"><div><h3 className="text-xs font-bold uppercase tracking-wider text-semantic-jira-primary mb-2">Tier 1–3 migration backlog</h3>{backlog.length ? <div className="divide-y divide-semantic-jira-border border border-semantic-jira-border rounded">{backlog.map((entry) => <div key={entry.id} className="p-3 text-xs"><b>{entry.systemName}</b> · {entry.tier.replace('_', ' ')} · {entry.status.replace('_', ' ')} · {entry.criticality}{entry.targetDate ? ` · target ${entry.targetDate}` : ''}{entry.currentThreatModelKey ? ` · ${entry.currentThreatModelKey}` : ''}</div>)}</div> : <p className="text-xs text-semantic-jira-muted">No authorized migration backlog entries.</p>}</div><form onSubmit={saveBacklog} className="border border-semantic-jira-border rounded p-3 grid grid-cols-2 gap-2"><div className="col-span-2 text-xs font-bold text-semantic-jira-primary">Add or update backlog entry</div><label className="col-span-2 text-xs">System name<input required className={field} value={item.systemName} onChange={(event) => setItem({ ...item, systemName: event.target.value })} /></label><label className="text-xs">Tier<select className={field} value={item.tier} onChange={(event) => setItem({ ...item, tier: event.target.value })}>{['TIER_1', 'TIER_2', 'TIER_3'].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-xs">Status<select className={field} value={item.status} onChange={(event) => setItem({ ...item, status: event.target.value })}>{['NOT_STARTED', 'PLANNED', 'IN_PROGRESS', 'APPROVED', 'OVERDUE'].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-xs">Criticality<select className={field} value={item.criticality} onChange={(event) => setItem({ ...item, criticality: event.target.value })}>{['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-xs">Target date<input className={field} type="date" value={item.targetDate} onChange={(event) => setItem({ ...item, targetDate: event.target.value })} /></label><label className="col-span-2 text-xs">Notes<textarea className={field} value={item.notes} onChange={(event) => setItem({ ...item, notes: event.target.value })} /></label><button disabled={busy} className="col-span-2 jira-btn-subtle"><Plus className="w-4 h-4" />Save backlog entry</button></form></div></section>;
};

const Thresholds: React.FC<{ label: string; values: Record<string, number>; onChange: (values: Record<string, number>) => void }> = ({ label, values, onChange }) => <fieldset className="border border-semantic-jira-border rounded p-2"><legend className="px-1 text-xs text-semantic-jira-muted">{label}</legend><div className="grid grid-cols-2 gap-2">{Object.entries(values).map(([key, value]) => <label key={key} className="text-caption">{key}<input className="jira-input mt-1 w-full" type="number" min="1" max="730" value={value} onChange={(event) => onChange({ ...values, [key]: Number(event.target.value) })} /></label>)}</div></fieldset>;
