apiVersion: v1
kind: Secret
metadata:
  name: aegissec-secrets
  namespace: bank-infosec
  labels:
    app.kubernetes.io/name: aegissec
type: Opaque
stringData:
  DATABASE_URL: "postgresql://bank_admin:BankSecureProdPassword2026!@postgres-service:5432/bank_infosec_db"
  DB_USER: "bank_admin"
  DB_PASSWORD: "BankSecureProdPassword2026!"
  REDIS_PASSWORD: "RedisSecureProdPassword2026!"
  JWT_SECRET: "aegissec-super-secure-production-jwt-key-for-apex-bank-2026"
  S3_ACCESS_KEY_ID: "AKIA_ENTERPRISE_AWS_KEY"
  S3_SECRET_ACCESS_KEY: "SUPER_SECRET_AWS_STORAGE_KEY"
