import { useState } from 'react';
import { AlertCircle, Loader2, X } from 'lucide-react';

type Props = { fetchWithAuth: (url: string, options?: RequestInit) => Promise<Response>; connector?: any; onClose: () => void; onSaved: () => Promise<void>; t: (key: string) => string };

export const LibreNmsConnectorModal: React.FC<Props> = ({ fetchWithAuth, connector, onClose, onSaved, t }) => {
  const [form, setForm] = useState({ name: connector?.name || 'LibreNMS Network Inventory', endpointUrl: connector?.nonSecretConfiguration?.endpointUrl || '', tokenReference: connector?.hasSecretReference ? '' : 'env://LIBRENMS_API_TOKEN', environment: connector?.environment || 'PRODUCTION', enabled: connector ? Boolean(connector.enabled) : true, allowPrivate: Boolean(connector?.endpointAllowPrivateNetwork) });
  const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try {
    const body: any = { ...(connector ? { version: Number(connector.version) } : {}), name: form.name, connectorType: 'LIBRENMS', libreNmsUrl: form.endpointUrl, environment: form.environment, enabled: form.enabled, endpointAllowPrivateNetwork: form.allowPrivate, tlsVerifyCertificates: true, requestTimeoutMs: 30000, responseSizeLimitBytes: 4194304, scheduleMinutes: 0 };
    if (!connector || form.tokenReference) body.secretReference = form.tokenReference;
    const response = await fetchWithAuth(connector ? `/api/cmdb/discovery/connectors/${encodeURIComponent(connector.id)}` : '/api/cmdb/discovery/connectors', { method: connector ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || t('Could not save LibreNMS connector.')); await onSaved(); onClose();
  } catch (cause) { setError(cause instanceof Error ? cause.message : t('Could not save LibreNMS connector.')); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-modal overflow-y-auto bg-semantic-modal-tint/60 backdrop-blur-sm p-4"><div className="flex min-h-full items-center justify-center"><form onSubmit={(event) => void save(event)} role="dialog" aria-modal="true" className="wrike-card w-full max-w-xl overflow-hidden"><div className="flex justify-between border-b border-semantic-border px-6 py-5"><div><h2 className="text-xl font-bold">{t('LibreNMS network inventory')}</h2><p className="mt-1 text-sm text-semantic-muted">{t('Read-only HTTPS API. The API token remains server-side as an env:// reference.')}</p></div><button type="button" onClick={onClose} className="jira-btn-subtle p-2"><X className="h-4 w-4" /></button></div><div className="space-y-4 px-6 py-5">{error && <div className="flex gap-2 text-sm text-semantic-danger"><AlertCircle className="h-4 w-4" />{error}</div>}<label className="block text-sm text-semantic-muted">{t('Name')}<input required value={form.name} onChange={(e) => setForm((v) => ({ ...v, name: e.target.value }))} className="jira-input mt-1 w-full" /></label><label className="block text-sm text-semantic-muted">{t('LibreNMS HTTPS origin')}<input required type="url" placeholder="https://librenms.bank.local" value={form.endpointUrl} onChange={(e) => setForm((v) => ({ ...v, endpointUrl: e.target.value }))} className="jira-input mt-1 w-full" /></label><label className="block text-sm text-semantic-muted">{t('Server token reference')}<input required={!connector} placeholder="env://LIBRENMS_API_TOKEN" value={form.tokenReference} onChange={(e) => setForm((v) => ({ ...v, tokenReference: e.target.value }))} className="jira-input mt-1 w-full" /></label><label className="flex gap-2 text-sm text-semantic-primary"><input type="checkbox" checked={form.allowPrivate} onChange={(e) => setForm((v) => ({ ...v, allowPrivate: e.target.checked }))} />{t('Approved private-network target')}</label><label className="flex gap-2 text-sm text-semantic-primary"><input type="checkbox" checked={form.enabled} onChange={(e) => setForm((v) => ({ ...v, enabled: e.target.checked }))} />{t('Enable connector')}</label></div><div className="flex justify-end gap-3 border-t border-semantic-border px-6 py-4"><button type="button" onClick={onClose} className="jira-btn-subtle">{t('Cancel')}</button><button disabled={saving} className="jira-btn-primary">{saving && <Loader2 className="h-4 w-4 animate-spin" />}{t('Save LibreNMS')}</button></div></form></div></div>;
};
