import { useEffect, useState } from 'react';
import { CheckCircle2, GitMerge, Loader2 } from 'lucide-react';

export const ReconciliationWorkbench: React.FC<{ fetchWithAuth: (url: string, options?: RequestInit) => Promise<Response>; t: (key: string) => string }> = ({ fetchWithAuth, t }) => {
  const [items, setItems] = useState<any[]>([]); const [selected, setSelected] = useState<any>(); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = async (background = false) => { if (!background) setLoading(true); try { const response = await fetchWithAuth('/api/cmdb/discovery/correlation-cases?page=1&pageSize=100'); const body = await response.json(); if (!response.ok || !body.success) throw new Error(body.error || t('Could not load reconciliation cases.')); setItems(body.items || []); setSelected((old: any) => (body.items || []).find((item: any) => item.id === old?.id) || body.items?.[0]); } catch (e) { if (!background) setError(e instanceof Error ? e.message : t('Could not load reconciliation cases.')); } finally { if (!background) setLoading(false); } };
  useEffect(() => { void load(); const refresh = () => void load(true); const interval = window.setInterval(() => { if (document.visibilityState === 'visible') void load(true); }, 15000); window.addEventListener('aegis:discovery-status-changed', refresh); return () => { window.clearInterval(interval); window.removeEventListener('aegis:discovery-status-changed', refresh); }; }, []);
  const decide = async (action: 'MATCH_EXISTING' | 'CREATE_NEW' | 'DISMISS', assetId?: string) => { if (!selected) return; setBusy(true); try { const response = await fetchWithAuth(`/api/cmdb/discovery/correlation-cases/${selected.id}/resolve`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, assetId, note: `Operator decision: ${action}`, version: 1 }) }); const body = await response.json(); if (!response.ok || !body.success) throw new Error(body.error || t('Could not resolve reconciliation case.')); await load(); } catch (e) { setError(e instanceof Error ? e.message : t('Could not resolve reconciliation case.')); } finally { setBusy(false); } };
  if (loading) return <div className="wrike-card p-8"><Loader2 className="mx-auto h-5 w-5 animate-spin" /></div>;
  return <section className="grid gap-4 lg:grid-cols-[280px_1fr]">{error && <p className="text-semantic-danger">{error}</p>}<aside className="wrike-card divide-y divide-semantic-border">{items.length ? items.map((item) => <button key={item.id} onClick={() => setSelected(item)} className={`block w-full p-3 text-left text-xs ${selected?.id === item.id ? 'bg-semantic-info-surface' : ''}`}><strong>{item.sourceObjectType}: {item.sourceObjectId}</strong><p className="text-semantic-muted">{item.outcome}</p></button>) : <p className="p-4 text-sm text-semantic-muted">{t('No open reconciliation cases.')}</p>}</aside>{selected && <article className="wrike-card space-y-4 p-5"><div className="flex gap-2 text-semantic-info"><GitMerge className="h-4 w-4" /><strong>{t('Reconciliation workbench')}</strong></div><p className="text-xs text-semantic-muted">{selected.summary}</p><div className="grid gap-3 md:grid-cols-2 text-xs"><div className="rounded border border-semantic-border p-3"><strong>{t('Incoming source record')}</strong><p>{selected.sourceObjectType}</p><p className="font-mono break-all">{selected.sourceObjectId}</p><p>{t('Source')}: {selected.connectorId}</p></div><div className="rounded border border-semantic-border p-3"><strong>{t('Strong/conflicting identity')}</strong><p>{selected.outcome}</p><p>{new Date(selected.openedAt).toLocaleString()}</p></div></div>{(selected.candidates || []).map((candidate: any) => <div key={candidate.assetId} className="rounded border border-semantic-border p-3 text-xs"><div className="flex justify-between"><strong>{candidate.name} · {candidate.ciNumber}</strong><b>{Math.round(candidate.score)}%</b></div><p className="mt-2 text-semantic-muted">{(candidate.evidence || []).map((e: any) => `${e.strength}: ${e.signal}`).join(' · ')}</p><button disabled={busy} onClick={() => void decide('MATCH_EXISTING', candidate.assetId)} className="jira-btn-primary mt-3"><CheckCircle2 className="h-4 w-4" />{t('Link')}</button></div>)}<div className="flex flex-wrap gap-2"><button disabled={busy} onClick={() => void decide('CREATE_NEW')} className="jira-btn-subtle">{t('Create New Asset')}</button><button disabled={busy} onClick={() => void decide('DISMISS')} className="jira-btn-subtle">{t('Keep Separate / Mark False Match')}</button></div></article>}</section>;
};
