import { useState } from 'react';
import { AlertCircle, Loader2, X } from 'lucide-react';

type Props = { fetchWithAuth: (url: string, options?: RequestInit) => Promise<Response>; connector?: any; onClose: () => void; onSaved: () => Promise<void>; t: (key: string) => string };

/** Deliberately has no credential fields: the worker identity may only browse SMB shares. */
export const SmbPrinterConnectorModal: React.FC<Props> = ({ fetchWithAuth, connector, onClose, onSaved, t }) => {
  const [form, setForm] = useState({ name: connector?.name || 'Printer Server SRV010', host: connector?.nonSecretConfiguration?.host || '192.168.0.110', environment: connector?.environment || 'PRODUCTION', enabled: connector ? Boolean(connector.enabled) : true });
  const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try {
    const response = await fetchWithAuth(connector ? `/api/cmdb/discovery/connectors/${encodeURIComponent(connector.id)}` : '/api/cmdb/discovery/connectors', { method: connector ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...(connector ? { version: Number(connector.version) } : {}), name: form.name, connectorType: 'SMB_PRINTER', smbHost: form.host, environment: form.environment, enabled: form.enabled, scheduleMinutes: 0 }) });
    const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || t('Could not save SMB printer connector.')); await onSaved(); onClose();
  } catch (cause) { setError(cause instanceof Error ? cause.message : t('Could not save SMB printer connector.')); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-modal overflow-y-auto bg-slate-950/45 p-3 sm:p-6"><div className="flex min-h-full items-center justify-center"><form onSubmit={(event) => void save(event)} aria-modal="true" role="dialog" className="wrike-card flex w-full max-w-xl flex-col overflow-hidden rounded-2xl shadow-2xl"><div className="flex items-start justify-between border-b border-semantic-border px-6 py-5"><div><h2 className="text-xl font-bold text-semantic-primary">{t('Add SMB Printer Server')}</h2><p className="mt-1 text-sm text-semantic-muted">{t('Uses only read-only SMB share enumeration (net view). No credentials, printer installation, job submission, configuration changes, or write operation is permitted.')}</p></div><button type="button" onClick={onClose} className="jira-btn-subtle p-2"><X className="h-4 w-4" /></button></div><div className="space-y-4 px-6 py-5">{error && <div className="flex gap-2 text-sm text-semantic-danger"><AlertCircle className="h-4 w-4" />{error}</div>}<div className="grid gap-4 sm:grid-cols-2"><label className="text-sm text-semantic-muted">{t('Name')}<input required value={form.name} onChange={(e) => setForm((v) => ({ ...v, name: e.target.value }))} className="jira-input mt-1 w-full" /></label><label className="text-sm text-semantic-muted">{t('Environment')}<select value={form.environment} onChange={(e) => setForm((v) => ({ ...v, environment: e.target.value }))} className="jira-input mt-1 w-full">{['PRODUCTION','DR','UAT','TEST','DEV'].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-sm text-semantic-muted sm:col-span-2">{t('Printer server')}<input required value={form.host} onChange={(e) => setForm((v) => ({ ...v, host: e.target.value }))} placeholder="192.168.0.110" className="jira-input mt-1 w-full" /><span className="mt-1 block text-xs">{t('Hostname or IPv4 address only. This target is displayed in the Connection List and stored with READ_ONLY access mode.')}</span></label></div><label className="flex items-center gap-2 text-sm text-semantic-primary"><input type="checkbox" checked={form.enabled} onChange={(e) => setForm((v) => ({ ...v, enabled: e.target.checked }))} />{t('Enable connector after save')}</label></div><div className="flex justify-end gap-3 border-t border-semantic-border px-6 py-4"><button type="button" onClick={onClose} className="jira-btn-subtle">{t('Cancel')}</button><button disabled={saving} className="jira-btn-primary">{saving && <Loader2 className="h-4 w-4 animate-spin" />}{t('Save read-only SMB source')}</button></div></form></div></div>;
};
