const escape=(value:unknown)=>String(value??'').replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]!));
const value=(item:unknown)=>typeof item==='object'&&item!==null?JSON.stringify(item,null,2):String(item??'—');
/** Self-contained, script-free human-readable rendering of an already-approved stored snapshot. */
export function renderThreatSnapshotReport(report:{sha256:string;snapshot:Record<string,unknown>}):string{
  const snapshot=report.snapshot;const model=snapshot.model as Record<string,unknown>|undefined;
  const sections=Object.entries(snapshot).filter(([key])=>!['formatVersion','modelId','revisionId'].includes(key)).map(([key,items])=>{
    const rows=Array.isArray(items)?items:[items];
    return `<section><h2>${escape(key.replace(/([A-Z])/g,' $1'))}</h2>${rows.length?rows.map((row,index)=>`<article><h3>${escape((row as any)?.title||(row as any)?.name||(row as any)?.key||(row as any)?.id||`Record ${index+1}`)}</h3><dl>${Object.entries(typeof row==='object'&&row!==null?row:{value:row}).map(([field,content])=>`<dt>${escape(field)}</dt><dd><pre>${escape(value(content))}</pre></dd>`).join('')}</dl></article>`).join(''):'<p>No records in this approved snapshot.</p>'}</section>`;
  }).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>${escape(model?.key||snapshot.modelId)} — approved threat model</title><style>body{font:14px/1.5 system-ui,sans-serif;color:#17243a;max-width:1100px;margin:40px auto;padding:0 24px}h1{font-size:28px}h2{text-transform:capitalize;border-bottom:2px solid #314b72;padding-bottom:8px;margin-top:32px}h3{font-size:16px}article{border:1px solid #cbd3df;padding:16px;margin:14px 0;break-inside:avoid}dl{display:grid;grid-template-columns:minmax(150px,25%) 1fr;margin:0}dt,dd{margin:0;padding:5px;border-bottom:1px solid #edf0f5}dt{font-weight:600;overflow-wrap:anywhere}pre{font:12px/1.5 ui-monospace,monospace;white-space:pre-wrap;overflow-wrap:anywhere;margin:0}.notice{background:#eef3fa;padding:16px}code{overflow-wrap:anywhere}@media print{body{margin:0;max-width:none;font-size:10pt}article{break-inside:auto}h2,h3{break-after:avoid}a{color:inherit}}</style></head><body><h1>${escape(model?.title||'Approved Threat Model')}</h1><p>${escape(model?.key)} · Revision ${escape(snapshot.revisionId)} · ${escape(model?.data_classification)}</p><div class="notice">Immutable approval evidence pack. This rendering contains the stored approval-time snapshot, not current live state. Mappings are not compliance certification. Implementation is not verification.<br>Canonical snapshot SHA-256: <code>${escape(report.sha256)}</code><br>Renderer: threat-snapshot-html/1. The hash identifies canonical JSON snapshot content, not these HTML bytes.</div>${sections}</body></html>`;
}
