import { DatabaseSchema } from './database.js';

export const initialSeedData: DatabaseSchema = {
  ticketRelationships: [],
  ticketTasks: [],
  ticketWorklogs: [],
  ticketSlaInstances: [],
  ticketSatisfaction: [],
  ticketAiRecommendations: [],
  divisions: [
    { id: 'div-sec', code: 'CISO', name: 'Information Security & Cyber Defense' },
    { id: 'div-it', code: 'IT_OPS', name: 'Information Technology & Cloud Infrastructure' },
    { id: 'div-banking', code: 'CORE_BANK', name: 'Retail & Corporate Banking Systems' },
    { id: 'div-hr', code: 'HR_CORP', name: 'Human Resources & Corporate Governance' },
  ],
  departments: [
    {
      id: 'dept-secops',
      divisionId: 'div-sec',
      code: 'INFOSEC',
      name: 'Information Security & Cyber Defense',
      description: 'Threat hunting, SOC operations, AppSec hardening, incident triage and security governance.',
      managerId: 'usr-ciso',
      adminUserIds: ['usr-ciso', 'usr-soc-lead'],
      color: '#0052CC',
      icon: 'Shield',
      isActive: true,
      memberCount: 8,
      connectionCount: 4,
      templateCount: 4,
      activeTaskCount: 12,
      settings: {
        defaultSlaHours: 4,
        criticalSlaHours: 1,
        autoAssignEnabled: true,
        defaultAssigneeId: 'usr-soc-lead',
        requireDualApproval: true,
        allowedTicketCategories: ['INCIDENT', 'VULNERABILITY', 'SECURITY_EXCEPTION', 'SECURITY_REVIEW', 'DLP_ALERT'],
        workingHours: { start: '00:00', end: '23:59', timezone: 'Asia/Baku' },
        notifications: { emailAlerts: true, escalateAfterHours: 2 },
      },
      createdAt: '2026-01-01T08:00:00Z',
    },
    {
      id: 'dept-it',
      divisionId: 'div-it',
      code: 'IT_OPS',
      name: 'IT Infrastructure & Cloud Operations',
      description: 'Active Directory identity management, hypervisors, cloud gateways, patching, and hardware support.',
      managerId: 'usr-it-lead',
      adminUserIds: ['usr-it-lead'],
      color: '#00875A',
      icon: 'Server',
      isActive: true,
      memberCount: 14,
      connectionCount: 4,
      templateCount: 3,
      activeTaskCount: 9,
      settings: {
        defaultSlaHours: 24,
        criticalSlaHours: 2,
        autoAssignEnabled: true,
        defaultAssigneeId: 'usr-it-lead',
        requireDualApproval: false,
        allowedTicketCategories: ['IAM_REQUEST', 'GENERAL_REQUEST', 'SECURITY_REVIEW'],
        workingHours: { start: '09:00', end: '18:00', timezone: 'Asia/Baku' },
        notifications: { emailAlerts: true, escalateAfterHours: 4 },
      },
      createdAt: '2026-01-01T08:00:00Z',
    },
    {
      id: 'dept-hr',
      divisionId: 'div-hr',
      code: 'HR_LEGAL',
      name: 'Human Resources & Personnel',
      description: 'Employee lifecycle, onboarding KYC, security clearance background checks, NDA compliance and payroll.',
      managerId: 'usr-hr-lead',
      adminUserIds: ['usr-hr-lead'],
      color: '#6554C0',
      icon: 'Users',
      isActive: true,
      memberCount: 6,
      connectionCount: 3,
      templateCount: 3,
      activeTaskCount: 5,
      settings: {
        defaultSlaHours: 48,
        criticalSlaHours: 8,
        autoAssignEnabled: true,
        defaultAssigneeId: 'usr-hr-lead',
        requireDualApproval: true,
        allowedTicketCategories: ['SECURITY_REVIEW', 'GENERAL_REQUEST', 'IAM_REQUEST'],
        workingHours: { start: '09:00', end: '18:00', timezone: 'Asia/Baku' },
        notifications: { emailAlerts: true, escalateAfterHours: 8 },
      },
      createdAt: '2026-01-01T08:00:00Z',
    },
    {
      id: 'dept-core',
      divisionId: 'div-banking',
      code: 'CORE_BANK',
      name: 'Core Banking Engineering & SWIFT',
      description: 'Temenos T24 transactional engine, SWIFT Alliance gateway, payment clearing rails, and core ledger DBs.',
      managerId: 'usr-core-lead',
      adminUserIds: ['usr-core-lead'],
      color: '#FF5630',
      icon: 'CreditCard',
      isActive: true,
      memberCount: 11,
      connectionCount: 4,
      templateCount: 3,
      activeTaskCount: 7,
      settings: {
        defaultSlaHours: 12,
        criticalSlaHours: 1,
        autoAssignEnabled: true,
        defaultAssigneeId: 'usr-core-lead',
        requireDualApproval: true,
        allowedTicketCategories: ['SECURITY_REVIEW', 'VULNERABILITY', 'INCIDENT'],
        workingHours: { start: '08:00', end: '20:00', timezone: 'Asia/Baku' },
        notifications: { emailAlerts: true, escalateAfterHours: 2 },
      },
      createdAt: '2026-01-01T08:00:00Z',
    },
    {
      id: 'dept-grc',
      divisionId: 'div-sec',
      code: 'GRC',
      name: 'Governance, Risk & Regulatory Compliance',
      description: 'Central Bank regulatory reporting, ISO 27001 / PCI-DSS compliance audits, and enterprise risk registers.',
      managerId: 'usr-grc-officer',
      adminUserIds: ['usr-grc-officer'],
      color: '#00B8D9',
      icon: 'CheckSquare',
      isActive: true,
      memberCount: 5,
      connectionCount: 2,
      templateCount: 2,
      activeTaskCount: 4,
      settings: {
        defaultSlaHours: 72,
        criticalSlaHours: 12,
        autoAssignEnabled: false,
        defaultAssigneeId: 'usr-grc-officer',
        requireDualApproval: true,
        allowedTicketCategories: ['AUDIT_FINDING', 'SECURITY_EXCEPTION', 'RISK_ACCEPTANCE', 'THIRD_PARTY_ASSESSMENT'],
        workingHours: { start: '09:00', end: '18:00', timezone: 'Asia/Baku' },
        notifications: { emailAlerts: true, escalateAfterHours: 12 },
      },
      createdAt: '2026-01-01T08:00:00Z',
    },
  ],
  teams: [
    { id: 'team-soc', departmentId: 'dept-secops', code: 'SOC', name: 'SOC Triage & Threat Hunting', securityDomain: 'SOC' },
    { id: 'team-appsec', departmentId: 'dept-secops', code: 'APPSEC_ENG', name: 'AppSec & Penetration Testing', securityDomain: 'APPSEC' },
    { id: 'team-grc', departmentId: 'dept-grc', code: 'GRC_OPS', name: 'Risk Management & Dual-Control', securityDomain: 'GRC' },
    { id: 'team-it-infra', departmentId: 'dept-it', code: 'IT_INFRA', name: 'Systems & Cloud Infrastructure' },
    { id: 'team-hr-ops', departmentId: 'dept-hr', code: 'HR_OPS', name: 'HR Operations & Clearance' },
    { id: 'team-swift-eng', departmentId: 'dept-core', code: 'SWIFT_DEV', name: 'Payment Gateway Squad' },
  ],
  users: [
    {
      id: 'usr-ciso',
      username: 'u.gasimli',
      sAMAccountName: 'u.gasimli',
      email: 'u.gasimli@apexbank.int',
      fullName: 'Unsal Gasimli',
      title: 'Chief Information Security Officer (Global Admin)',
      departmentId: 'dept-secops',
      divisionId: 'div-sec',
      teamIds: ['team-soc', 'team-grc'],
      roles: ['PLATFORM_ADMIN', 'CISO', 'INFOSEC_ADMIN', 'APPROVER'],
      securityClearance: 'HIGHLY_RESTRICTED_HR_LEGAL',
      ownedApplicationIds: ['app-core-bank', 'app-swift'],
      ownedAssetIds: ['ast-core-01', 'ast-fw-01'],
      ownedRiskIds: ['risk-001'],
      distributionGroups: ['İnformasiya Təhlükəsizliyi DG', 'Enterprise_Security_Admins', 'Executive_Board'],
      isActive: true,
    },
    {
      id: 'usr-it-lead',
      username: 'm.rustamov',
      sAMAccountName: 'm.rustamov',
      email: 'm.rustamov@apexbank.int',
      fullName: 'Murad Rustamov',
      title: 'Head of IT Operations & Infrastructure',
      departmentId: 'dept-it',
      divisionId: 'div-it',
      teamIds: ['team-it-infra'],
      roles: ['DEPARTMENT_ADMIN', 'IT_ADMIN', 'TEAM_LEAD', 'APPROVER'],
      securityClearance: 'CONFIDENTIAL_SECURITY_ONLY',
      ownedApplicationIds: ['app-vpn-gw'],
      ownedAssetIds: ['ast-dc-01', 'ast-esxi-01'],
      ownedRiskIds: [],
      distributionGroups: ['IT_Operations_Admins'],
      isActive: true,
    },
    {
      id: 'usr-hr-lead',
      username: 'n.huseynova',
      sAMAccountName: 'n.huseynova',
      email: 'n.huseynova@apexbank.int',
      fullName: 'Nigar Huseynova',
      title: 'Head of Human Resources & Personnel',
      departmentId: 'dept-hr',
      divisionId: 'div-hr',
      teamIds: ['team-hr-ops'],
      roles: ['DEPARTMENT_ADMIN', 'HR_ADMIN', 'APPROVER'],
      securityClearance: 'HIGHLY_RESTRICTED_HR_LEGAL',
      ownedApplicationIds: [],
      ownedAssetIds: [],
      ownedRiskIds: [],
      distributionGroups: ['HR_Management_DG'],
      isActive: true,
    },
    {
      id: 'usr-core-lead',
      username: 't.aliyev',
      sAMAccountName: 't.aliyev',
      email: 't.aliyev@apexbank.int',
      fullName: 'Tarlan Aliyev',
      title: 'Principal Core Banking & SWIFT Lead',
      departmentId: 'dept-core',
      divisionId: 'div-banking',
      teamIds: ['team-swift-eng'],
      roles: ['DEPARTMENT_ADMIN', 'CORE_BANK_ADMIN', 'APPLICATION_OWNER', 'APPROVER'],
      securityClearance: 'CONFIDENTIAL_SECURITY_ONLY',
      ownedApplicationIds: ['app-core-bank', 'app-swift'],
      ownedAssetIds: ['ast-core-01'],
      ownedRiskIds: [],
      distributionGroups: ['Core_Banking_Engineers'],
      isActive: true,
    },
    {
      id: 'usr-soc-lead',
      username: 'e.mammadov',
      sAMAccountName: 'e.mammadov',
      email: 'e.mammadov@apexbank.int',
      fullName: 'Elnur Mammadov',
      title: 'SOC Operations & Incident Lead',
      departmentId: 'dept-secops',
      divisionId: 'div-sec',
      teamIds: ['team-soc'],
      roles: ['DEPARTMENT_ADMIN', 'INFOSEC_ADMIN', 'TEAM_LEAD', 'SECURITY_ANALYST', 'SOC_ANALYST', 'APPROVER'],
      securityClearance: 'CONFIDENTIAL_SECURITY_ONLY',
      ownedApplicationIds: [],
      ownedAssetIds: ['ast-siem-01'],
      ownedRiskIds: [],
      distributionGroups: ['SOC_Incident_Responders'],
      isActive: true,
    },
    {
      id: 'usr-appsec-spec',
      username: 'l.aliyeva',
      sAMAccountName: 'l.aliyeva',
      email: 'l.aliyeva@apexbank.int',
      fullName: 'Leyla Aliyeva',
      title: 'Senior AppSec Engineer',
      departmentId: 'dept-secops',
      divisionId: 'div-sec',
      teamIds: ['team-appsec'],
      roles: ['APPSEC_ANALYST', 'SECURITY_ANALYST'],
      securityClearance: 'CONFIDENTIAL_SECURITY_ONLY',
      ownedApplicationIds: ['app-mobile-bank'],
      ownedAssetIds: [],
      ownedRiskIds: [],
      distributionGroups: ['AppSec_Reviewers'],
      isActive: true,
    },
    {
      id: 'usr-grc-officer',
      username: 'r.huseynov',
      sAMAccountName: 'r.huseynov',
      email: 'r.huseynov@apexbank.int',
      fullName: 'Rashad Huseynov',
      title: 'Senior GRC & Compliance Auditor',
      departmentId: 'dept-grc',
      divisionId: 'div-sec',
      teamIds: ['team-grc'],
      roles: ['DEPARTMENT_ADMIN', 'AUDITOR', 'REQUESTER'],
      securityClearance: 'RESTRICTED',
      ownedApplicationIds: [],
      ownedAssetIds: [],
      ownedRiskIds: ['risk-002'],
      distributionGroups: ['İnformasiya Təhlükəsizliyi DG'],
      isActive: true,
    },
  ],
  workflows: [
    {
      id: 'wf-secops-default',
      name: 'Bank SecOps Incident & Finding Lifecycle',
      description: 'ISO 27001 & PCI-DSS standard state machine for banking security tickets',
      version: 2,
      isActive: true,
      ticketTypeId: 'SEC',
      states: [
        { id: 'OPEN', name: 'Open / Triage', category: 'TO_DO', color: '#22272B' },
        { id: 'IN_PROGRESS', name: 'In Progress', category: 'IN_PROGRESS', color: '#1C2B41' },
        { id: 'WAITING_FOR_CUSTOMER', name: 'Waiting for Customer', category: 'IN_REVIEW', color: '#594300', isPausedSLA: true, pauseReason: 'Waiting for requester information' },
        { id: 'WAITING_FOR_VENDOR', name: 'Waiting for Vendor', category: 'IN_REVIEW', color: '#594300', isPausedSLA: true, pauseReason: 'Waiting for external vendor' },
        { id: 'WAITING_FOR_APPROVAL', name: 'Waiting for Approval', category: 'IN_REVIEW', color: '#403294', isPausedSLA: true, pauseReason: 'Approval decision pending' },
        { id: 'UNDER_REVIEW', name: 'Under Review', category: 'IN_REVIEW', color: '#332E1B' },
        { id: 'RESOLVED', name: 'Resolved', category: 'IN_REVIEW', color: '#164B35' },
        { id: 'CLOSED', name: 'Closed', category: 'DONE', color: '#162E25', isTerminal: true },
        { id: 'CANCELLED', name: 'Cancelled', category: 'CANCELLED', color: '#5E6C84', isTerminal: true },
      ],
      transitions: [
        { id: 'tr-start', name: 'Start Investigation', fromStateId: 'OPEN', toStateId: 'IN_PROGRESS', allowedRoles: ['SECURITY_ANALYST', 'SOC_ANALYST', 'CISO'] },
        { id: 'tr-wait-customer', name: 'Wait for Customer', fromStateId: 'IN_PROGRESS', toStateId: 'WAITING_FOR_CUSTOMER', allowedRoles: ['SECURITY_ANALYST', 'SOC_ANALYST', 'APPSEC_ANALYST', 'CISO'], requireComment: true },
        { id: 'tr-wait-vendor', name: 'Wait for Vendor', fromStateId: 'IN_PROGRESS', toStateId: 'WAITING_FOR_VENDOR', allowedRoles: ['SECURITY_ANALYST', 'SOC_ANALYST', 'APPSEC_ANALYST', 'CISO'], requireComment: true },
        { id: 'tr-resume-customer', name: 'Resume Work', fromStateId: 'WAITING_FOR_CUSTOMER', toStateId: 'IN_PROGRESS', allowedRoles: ['SECURITY_ANALYST', 'SOC_ANALYST', 'APPSEC_ANALYST', 'CISO'] },
        { id: 'tr-resume-vendor', name: 'Resume Work', fromStateId: 'WAITING_FOR_VENDOR', toStateId: 'IN_PROGRESS', allowedRoles: ['SECURITY_ANALYST', 'SOC_ANALYST', 'APPSEC_ANALYST', 'CISO'] },
        { id: 'tr-review', name: 'Submit for Review', fromStateId: 'IN_PROGRESS', toStateId: 'UNDER_REVIEW', allowedRoles: ['SECURITY_ANALYST', 'SOC_ANALYST', 'APPSEC_ANALYST', 'CISO'] },
        { id: 'tr-resolve', name: 'Resolve Issue', fromStateId: 'UNDER_REVIEW', toStateId: 'RESOLVED', allowedRoles: ['CISO', 'TEAM_LEAD', 'APPROVER'], requireComment: true, requiredFields: ['resolutionCode', 'resolutionSummary'], actions: ['SET_RESOLVED_AT', 'STOP_SLA'] },
        { id: 'tr-close', name: 'Close Ticket', fromStateId: 'RESOLVED', toStateId: 'CLOSED', allowedRoles: ['CISO', 'TEAM_LEAD', 'APPROVER', 'REQUESTER'], actions: ['SET_CLOSED_AT'] },
        { id: 'tr-reopen', name: 'Reopen', fromStateId: 'RESOLVED', toStateId: 'OPEN', allowedRoles: ['CISO', 'TEAM_LEAD', 'PLATFORM_ADMIN'] },
        { id: 'tr-reopen-closed', name: 'Reopen', fromStateId: 'CLOSED', toStateId: 'OPEN', allowedRoles: ['CISO', 'TEAM_LEAD', 'PLATFORM_ADMIN'], actions: ['CLEAR_RESOLUTION', 'START_SLA'] },
        { id: 'tr-cancel', name: 'Cancel Ticket', fromStateId: 'OPEN', toStateId: 'CANCELLED', allowedRoles: ['CISO', 'TEAM_LEAD', 'PLATFORM_ADMIN'], requireComment: true, requiredFields: ['resolutionCode', 'resolutionSummary'] },
      ],
    },
  ],
  slaPolicies: [
    {
      id: 'sla-p1-emergency',
      name: 'P1 Critical Banking Security SLA',
      description: '15-minute response, 2-hour containment for Tier-1 banking systems',
      isDefault: true,
      businessHoursOnly: false,
      businessStartTime: '09:00',
      businessEndTime: '18:00',
      timezone: 'Asia/Baku',
      excludeWeekends: false,
      excludeHolidays: false,
      thresholds: {
        CRITICAL: { acknowledgmentMinutes: 15, firstResponseMinutes: 15, remediationMinutes: 120, resolutionMinutes: 120 },
        HIGH: { acknowledgmentMinutes: 30, firstResponseMinutes: 60, remediationMinutes: 1440, resolutionMinutes: 2880 },
        MEDIUM: { acknowledgmentMinutes: 60, firstResponseMinutes: 240, remediationMinutes: 4320, resolutionMinutes: 10080 },
        LOW: { acknowledgmentMinutes: 120, firstResponseMinutes: 480, remediationMinutes: 10080, resolutionMinutes: 20160 },
        INFORMATIONAL: { acknowledgmentMinutes: 240, firstResponseMinutes: 1440, remediationMinutes: 20160, resolutionMinutes: 43200 },
      },
    },
  ],
  applications: [
    {
      id: 'app-core-bank',
      code: 'CORE-BANK',
      name: 'Apex Core Banking Gateway (Temenos T24)',
      description: 'Central transactional banking core engine and accounts database',
      criticality: 'TIER_1',
      environment: 'PRODUCTION',
      technicalOwnerId: 'usr-ciso',
      businessOwnerId: 'usr-ciso',
      securityLeadId: 'usr-ciso',
      developmentTeamId: 'dept-core',
      techStack: ['Java', 'Oracle DB', 'Kafka', 'Docker'],
      gitRepositories: ['https://git.apexbank.int/core/banking-service'],
      connectedDatabases: ['prod-core-db01.apexbank.local'],
      connectedApis: ['https://api.apexbank.int/v1/core'],
      internetExposed: false,
      dataClassification: 'HIGHLY_RESTRICTED_HR_LEGAL',
      activeRiskCount: 1,
      openVulnerabilitiesCount: 1,
    },
    {
      id: 'app-swift',
      code: 'SWIFT-ALLIANCE',
      name: 'SWIFT Alliance Access Messaging Interface',
      description: 'Interbank SWIFT messaging terminal and financial sanction filter',
      criticality: 'TIER_1',
      environment: 'PRODUCTION',
      technicalOwnerId: 'usr-soc-lead',
      businessOwnerId: 'usr-ciso',
      securityLeadId: 'usr-ciso',
      developmentTeamId: 'dept-secops',
      techStack: ['C++', 'MQSeries', 'RHEL 9'],
      gitRepositories: ['https://git.apexbank.int/payments/swift-access'],
      connectedDatabases: ['prod-swift-db01.apexbank.local'],
      connectedApis: ['https://swift-gw.apexbank.int/alliance'],
      internetExposed: false,
      dataClassification: 'HIGHLY_RESTRICTED_HR_LEGAL',
      activeRiskCount: 1,
      openVulnerabilitiesCount: 1,
    },
    {
      id: 'app-mobile-bank',
      code: 'MOB-APP',
      name: 'Apex Retail Mobile Banking Backend API',
      description: 'Customer facing retail banking mobile application API cluster',
      criticality: 'TIER_1',
      environment: 'PRODUCTION',
      technicalOwnerId: 'usr-appsec-spec',
      businessOwnerId: 'usr-grc-officer',
      securityLeadId: 'usr-appsec-spec',
      developmentTeamId: 'dept-core',
      techStack: ['Node.js', 'TypeScript', 'PostgreSQL', 'Redis'],
      gitRepositories: ['https://git.apexbank.int/mobile/api-gateway'],
      connectedDatabases: ['prod-mobile-pg01.apexbank.local'],
      connectedApis: ['https://api.apexbank.az/mobile/v2'],
      internetExposed: true,
      dataClassification: 'RESTRICTED',
      activeRiskCount: 0,
      openVulnerabilitiesCount: 2,
    },
  ],
  assets: [
    {
      id: 'ast-core-01',
      name: 'srv-prod-core-gw01.apexbank.local',
      hostname: 'srv-prod-core-gw01',
      ipAddress: '10.100.20.14',
      environment: 'PRODUCTION',
      criticality: 'TIER_1',
      internetExposed: false,
      businessService: 'Core Banking Payment Router',
      applicationId: 'app-core-bank',
      assetType: 'SERVER',
      ownerId: 'usr-ciso',
      departmentId: 'dept-secops',
      dataClassification: 'HIGHLY_RESTRICTED_HR_LEGAL',
      cmdbId: 'CMDB-SRV-8821',
      openTicketCount: 2,
      criticalFindingCount: 1,
    },
    {
      id: 'ast-fw-01',
      name: 'paloalto-dc1-perimeter01.apexbank.local',
      hostname: 'pa-dc1-perim01',
      ipAddress: '10.100.1.1',
      environment: 'PRODUCTION',
      criticality: 'TIER_1',
      internetExposed: true,
      businessService: 'Perimeter DC1 Gateway Firewall',
      applicationId: 'app-swift',
      assetType: 'FIREWALL',
      ownerId: 'usr-soc-lead',
      departmentId: 'dept-secops',
      dataClassification: 'CONFIDENTIAL_SECURITY_ONLY',
      cmdbId: 'CMDB-NET-0112',
      openTicketCount: 1,
      criticalFindingCount: 0,
    },
  ],
  risks: [
    {
      id: 'risk-001',
      riskCode: 'RSK-2026-001',
      title: 'Legacy Cryptographic Cipher Suites on Swift Edge Terminals',
      description: 'TLS 1.1 handshake enabled on fallback payment terminal connections.',
      ownerId: 'usr-ciso',
      departmentId: 'dept-secops',
      affectedApplicationIds: ['app-swift'],
      affectedAssetIds: ['ast-core-01'],
      likelihood: 3,
      impact: 4,
      inherentScore: 12,
      inherentRating: 'HIGH',
      existingControls: 'Perimeter firewall rate-limiting and intrusion prevention sensor',
      residualLikelihood: 2,
      residualImpact: 3,
      residualScore: 6,
      residualRating: 'MEDIUM',
      treatmentStrategy: 'MITIGATE',
      treatmentPlan: 'Enforce TLS 1.3 only and migrate legacy POS connectors by Q3.',
      treatmentDeadline: new Date(Date.now() + 7776000000).toISOString(),
      status: 'IDENTIFIED',
      linkedTicketIds: ['tick-soc-101'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'risk-002',
      riskCode: 'RSK-2026-002',
      title: 'Privileged Access Elevation via Secondary Jump-Host',
      description: 'Dual-control bypass potential if secondary jump-host SSH keys are cached.',
      ownerId: 'usr-grc-officer',
      departmentId: 'dept-grc',
      affectedApplicationIds: ['app-core-bank'],
      affectedAssetIds: ['ast-fw-01'],
      likelihood: 2,
      impact: 5,
      inherentScore: 10,
      inherentRating: 'HIGH',
      existingControls: 'SSH key rotation policy and dual-factor authentication',
      residualLikelihood: 1,
      residualImpact: 4,
      residualScore: 4,
      residualRating: 'LOW',
      treatmentStrategy: 'MITIGATE',
      treatmentPlan: 'Enforce hardware FIDO2 keys and 4-eyes session recording.',
      treatmentDeadline: new Date(Date.now() + 5184000000).toISOString(),
      status: 'TREATMENT_IN_PROGRESS',
      linkedTicketIds: ['tick-grc-103'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  tickets: [
    {
      id: 'tick-soc-101',
      key: 'SEC-101',
      projectCode: 'SEC',
      ticketTypeId: 'INCIDENT',
      ticketTypeName: 'Cyber Security Incident',
      category: 'INCIDENT',
      securityDomain: 'SOC',
      title: 'Distributed Brute Force & Credential Stuffing on SWIFT Gateway',
      description: 'SOC SIEM detected 12,000+ failed authentication attempts originating from 14 distinct autonomous systems against SWIFT Alliance gateway edge.',
      statusId: 'IN_PROGRESS',
      statusName: 'In Progress',
      statusCategory: 'IN_PROGRESS',
      workflowId: 'wf-secops-default',
      workflowVersion: 1,
      technicalSeverity: 'CRITICAL',
      businessPriority: 'P1_URGENT',
      businessImpact: 'CATASTROPHIC',
      inherentRisk: 'CRITICAL',
      residualRisk: 'HIGH',
      riskScore: 25,
      confidentiality: 'HIGHLY_RESTRICTED_HR_LEGAL',
      reporterId: 'usr-soc-lead',
      assigneeId: 'usr-ciso',
      securityOwnerId: 'usr-ciso',
      applicationId: 'app-swift',
      assetId: 'ast-core-01',
      watcherIds: ['usr-soc-lead', 'usr-appsec-spec'],
      tags: ['SWIFT', 'BRUTE_FORCE', 'P1', 'SOC_EMERGENCY'],
      dueDate: new Date(Date.now() + 86400000).toISOString(),
      remediationDeadline: new Date(Date.now() + 86400000).toISOString(),
      slaState: 'BREACHED',
      slaBreachDeadline: new Date(Date.now() - 3600000).toISOString(),
      slaRemainingMinutes: -45,
      version: 1,
      createdAt: new Date(Date.now() - 14400000).toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'tick-appsec-102',
      key: 'SEC-102',
      projectCode: 'SEC',
      ticketTypeId: 'VULNERABILITY',
      ticketTypeName: 'Application Security Finding',
      category: 'VULNERABILITY',
      securityDomain: 'APPSEC',
      title: 'CVE-2026-3829: Critical Remote Code Execution in Banking API Gateway',
      description: 'SAST & DAST scans identified deserialization flaw in the REST payload handling layer of Core Banking API.',
      statusId: 'OPEN',
      statusName: 'Open / Triage',
      statusCategory: 'TO_DO',
      workflowId: 'wf-secops-default',
      workflowVersion: 1,
      technicalSeverity: 'HIGH',
      businessPriority: 'P2_HIGH',
      businessImpact: 'SIGNIFICANT',
      inherentRisk: 'HIGH',
      residualRisk: 'MEDIUM',
      riskScore: 16,
      cvssScore: 8.8,
      cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
      confidentiality: 'CONFIDENTIAL_SECURITY_ONLY',
      reporterId: 'usr-appsec-spec',
      assigneeId: 'usr-appsec-spec',
      securityOwnerId: 'usr-ciso',
      applicationId: 'app-core-bank',
      assetId: 'ast-core-01',
      watcherIds: ['usr-ciso'],
      tags: ['CVE-2026-3829', 'APPSEC', 'DESERIALIZATION'],
      dueDate: new Date(Date.now() + 172800000).toISOString(),
      remediationDeadline: new Date(Date.now() + 172800000).toISOString(),
      slaState: 'AT_RISK',
      slaRemainingMinutes: 75,
      version: 1,
      createdAt: new Date(Date.now() - 7200000).toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'tick-grc-103',
      key: 'SEC-103',
      projectCode: 'SEC',
      ticketTypeId: 'SECURITY_EXCEPTION',
      ticketTypeName: 'Security Policy Exception Waiver',
      category: 'SECURITY_EXCEPTION',
      securityDomain: 'GRC',
      title: 'Production Firewall Policy Exception: Swift Edge Port 8443 Direct Whitelist',
      description: 'Requesting temporary 30-day firewall exception to route Swift staging telemetry through perimeter proxy.',
      statusId: 'UNDER_REVIEW',
      statusName: 'Under Review',
      statusCategory: 'IN_REVIEW',
      workflowId: 'wf-secops-default',
      workflowVersion: 1,
      technicalSeverity: 'MEDIUM',
      businessPriority: 'P3_MEDIUM',
      businessImpact: 'MODERATE',
      inherentRisk: 'MEDIUM',
      residualRisk: 'LOW',
      riskScore: 9,
      confidentiality: 'RESTRICTED',
      reporterId: 'usr-grc-officer',
      assigneeId: 'usr-ciso',
      securityOwnerId: 'usr-ciso',
      applicationId: 'app-swift',
      assetId: 'ast-fw-01',
      watcherIds: ['usr-grc-officer', 'usr-soc-lead'],
      tags: ['EXCEPTION', 'FIREWALL', 'DUAL_CONTROL'],
      dueDate: new Date(Date.now() + 259200000).toISOString(),
      remediationDeadline: new Date(Date.now() + 259200000).toISOString(),
      slaState: 'SAFE',
      slaRemainingMinutes: 320,
      version: 1,
      createdAt: new Date(Date.now() - 28800000).toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'tick-dlp-104',
      key: 'SEC-104',
      projectCode: 'SEC',
      ticketTypeId: 'DLP_ALERT',
      ticketTypeName: 'Data Loss Prevention Alert',
      category: 'DLP_ALERT',
      securityDomain: 'DLP',
      title: 'DLP Alert: Bulk Export of Credit Card PAN Numbers from CRM Staging',
      description: 'Endpoint DLP sensor intercepted unencrypted export of 450 credit card account numbers to USB storage device.',
      statusId: 'RESOLVED',
      statusName: 'Resolved / Closed',
      statusCategory: 'DONE',
      workflowId: 'wf-secops-default',
      workflowVersion: 1,
      technicalSeverity: 'HIGH',
      businessPriority: 'P2_HIGH',
      businessImpact: 'SIGNIFICANT',
      inherentRisk: 'HIGH',
      residualRisk: 'LOW',
      riskScore: 15,
      confidentiality: 'HIGHLY_RESTRICTED_HR_LEGAL',
      reporterId: 'usr-soc-lead',
      assigneeId: 'usr-ciso',
      securityOwnerId: 'usr-ciso',
      applicationId: 'app-mobile-bank',
      assetId: 'ast-core-01',
      watcherIds: ['usr-ciso'],
      tags: ['DLP', 'PCI_DSS', 'USB_BLOCKED'],
      dueDate: new Date().toISOString(),
      remediationDeadline: new Date().toISOString(),
      slaState: 'MET',
      version: 1,
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  approvals: [
    {
      id: 'chain-103',
      ticketId: 'tick-grc-103',
      title: 'Security Policy Exception Dual-Control Authorization',
      status: 'PENDING',
      steps: [
        {
          id: 'step-1',
          stepNumber: 1,
          name: 'SOC Lead Technical Review',
          status: 'APPROVED',
          requiredRole: 'TEAM_LEAD',
          assignedApproverId: 'usr-soc-lead',
          assignedApproverName: 'Elnur Mammadov',
          decisionByUserId: 'usr-soc-lead',
          decisionByUserName: 'Elnur Mammadov',
          comments: 'Firewall ruleset verified and sandboxed.',
          decisionAt: new Date().toISOString(),
          isMandatory: true,
        },
        {
          id: 'step-2',
          stepNumber: 2,
          name: 'CISO Dual-Control Authorization',
          status: 'PENDING',
          requiredRole: 'CISO',
          assignedApproverId: 'usr-ciso',
          assignedApproverName: 'Unsal Gasimli',
          isMandatory: true,
        },
      ],
      createdAt: new Date().toISOString(),
    },
  ],
  comments: [
    {
      id: 'cmt-01',
      ticketId: 'tick-soc-101',
      authorId: 'usr-soc-lead',
      authorName: 'Elnur Mammadov',
      authorRole: 'SOC Operations Lead',
      content: 'Identified source IP blocks: 194.26.29.0/24. Adding immediate rate-limiting on Palo Alto perimeter gateway.',
      visibility: 'INTERNAL',
      confidentiality: 'CONFIDENTIAL_SECURITY_ONLY',
      mentions: [],
      isEdited: false,
      reactions: [],
      createdAt: new Date(Date.now() - 7200000).toISOString(),
      updatedAt: new Date(Date.now() - 7200000).toISOString(),
    },
    {
      id: 'cmt-02',
      ticketId: 'tick-soc-101',
      authorId: 'usr-ciso',
      authorName: 'Unsal Gasimli',
      authorRole: 'CISO',
      content: 'Authorized emergency temporary containment block. Notify Central Bank SOC liaison per regulatory incident guidelines.',
      visibility: 'INTERNAL',
      confidentiality: 'HIGHLY_RESTRICTED_HR_LEGAL',
      mentions: [],
      isEdited: false,
      reactions: [],
      createdAt: new Date(Date.now() - 3600000).toISOString(),
      updatedAt: new Date(Date.now() - 3600000).toISOString(),
    },
  ],
  attachments: [],
  auditEvents: [
    {
      id: 'aud-01',
      timestamp: new Date(Date.now() - 7200000).toISOString(),
      actorId: 'usr-soc-lead',
      actorName: 'Elnur Mammadov',
      actorRole: 'SOC Operations Lead',
      ipAddress: '10.100.20.5',
      userAgent: 'ApexBank-Internal-SecOps/1.0',
      correlationId: 'corr-001',
      action: 'STATUS_TRANSITIONED',
      entityType: 'TICKET',
      entityId: 'tick-soc-101',
      entityKey: 'SEC-101',
      metadata: { details: 'Status changed from OPEN to IN_PROGRESS' },
    },
    {
      id: 'aud-02',
      timestamp: new Date(Date.now() - 3600000).toISOString(),
      actorId: 'usr-ciso',
      actorName: 'Unsal Gasimli',
      actorRole: 'CISO',
      ipAddress: '10.100.20.1',
      userAgent: 'ApexBank-Internal-SecOps/1.0',
      correlationId: 'corr-002',
      action: 'COMMENT_ADDED',
      entityType: 'TICKET',
      entityId: 'tick-soc-101',
      entityKey: 'SEC-101',
      metadata: { details: 'Added CISO executive authorization guidance' },
    },
  ],
  automationRules: [
    {
      id: 'rule-1',
      name: 'Auto-Escalate Critical P1 Incidents to CISO & Trigger 15-min SLA',
      description: 'When new ticket is created with Severity = CRITICAL on Tier-1 system, assign to CISO and set SLA clock.',
      isActive: true,
      trigger: 'TICKET_CREATED',
      conditions: [
        { field: 'technicalSeverity', operator: 'EQUALS', value: 'CRITICAL' },
      ],
      actions: [
        { type: 'ASSIGN_USER', payload: { userId: 'usr-ciso' } },
        { type: 'SET_PRIORITY', payload: { priority: 'P1_URGENT' } },
        { type: 'ESCALATE_TO_CISO', payload: { reason: 'P1 Critical Banking Incident SLA active' } },
      ],
      executionCount: 142,
      lastExecutedAt: new Date(Date.now() - 3600000).toISOString(),
    },
    {
      id: 'rule-2',
      name: 'Enforce Dual-Control 4-Eyes Sign-Off on Security Exceptions',
      description: 'When ticket category is SECURITY_EXCEPTION, generate cryptographic 2-step approval chain.',
      isActive: true,
      trigger: 'TICKET_CREATED',
      conditions: [
        { field: 'category', operator: 'EQUALS', value: 'SECURITY_EXCEPTION' },
      ],
      actions: [
        { type: 'ADD_TAG', payload: { tag: 'DUAL_CONTROL' } },
        { type: 'NOTIFY_MANAGER', payload: { role: 'CISO' } },
      ],
      executionCount: 58,
      lastExecutedAt: new Date(Date.now() - 7200000).toISOString(),
    },
    {
      id: 'rule-3',
      name: 'Auto-Notify Central Bank Liaison on SLA Breach',
      description: 'When SLA status transitions to BREACHED for high impact incidents.',
      isActive: true,
      trigger: 'SLA_BREACHED',
      conditions: [
        { field: 'slaState', operator: 'EQUALS', value: 'BREACHED' },
      ],
      actions: [
        { type: 'NOTIFY_MANAGER', payload: { channel: 'REGULATORY_ALERT' } },
      ],
      executionCount: 12,
      lastExecutedAt: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      id: 'rule-4',
      name: 'Auto-Close Risk Register Item upon Verified Remediation Evidence',
      description: 'When ticket status transitions to RESOLVED with cryptographic proof.',
      isActive: true,
      trigger: 'STATUS_CHANGED',
      conditions: [
        { field: 'statusCategory', operator: 'EQUALS', value: 'DONE' },
      ],
      actions: [
        { type: 'ADD_INTERNAL_NOTE', payload: { note: 'Verified by Wrike SecOps Automation Engine.' } },
      ],
      executionCount: 94,
      lastExecutedAt: new Date(Date.now() - 14400000).toISOString(),
    },
  ],
  ideas: [
    {
      id: 'idea-1',
      title: 'Enforce Dual-Control HSM Cryptographic Sign-Off on SWIFT Alliance',
      description: 'Require 4-eyes authorization on all hardware security module keys and perimeter firewall rule pushes to satisfy Central Bank guidelines.',
      category: 'THREAT_VECTOR',
      color: 'green',
      x: 60,
      y: 60,
      status: 'IDEA',
      priority: 'P1_URGENT',
      assignee: 'Unsal Gasimli (CISO)',
      tags: ['SWIFT', 'HSM', 'DUAL_CONTROL', 'PCI_DSS'],
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      id: 'idea-2',
      title: 'Automate Zero Trust Micro-segmentation for Temenos T24 Core Banking',
      description: 'Implement eBPF based service mesh network policy enforcement between core banking REST APIs and Oracle database clusters.',
      category: 'ZERO_TRUST',
      color: 'blue',
      x: 440,
      y: 60,
      status: 'IDEA',
      priority: 'P2_HIGH',
      assignee: 'Elnur Mammadov (SOC Lead)',
      tags: ['T24', 'MICROSEGMENTATION', 'ZERO_TRUST'],
      createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
      updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    },
    {
      id: 'idea-3',
      title: 'PCI-DSS 4.0 Requirement 6.4: Automated Web Application & API Protection',
      description: 'Deploy runtime AST sensor to detect deserialization flaws in client-facing mobile banking gateway payloads before release.',
      category: 'COMPLIANCE',
      color: 'amber',
      x: 820,
      y: 60,
      status: 'IDEA',
      priority: 'P2_HIGH',
      assignee: 'Leyla Aliyeva (AppSec)',
      tags: ['PCI_DSS', 'APPSEC', 'CVE_REMEDIATION'],
      createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
      updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    },
    {
      id: 'idea-4',
      title: 'Real-time DLP Sensor Interception on CRM Pan Number Exports',
      description: 'Block unencrypted USB exports of debit/credit card records and route automated incident triage ticket to SOC hunting queue.',
      category: 'INCIDENT_IR',
      color: 'coral',
      x: 60,
      y: 340,
      status: 'CONVERTED',
      convertedTicketKey: 'SEC-104',
      convertedTicketId: 'tick-dlp-104',
      priority: 'P1_URGENT',
      assignee: 'Elnur Mammadov (SOC Lead)',
      tags: ['DLP', 'CARDHOLDER_DATA', 'SOC_TRIAGE'],
      createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
      updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    },
    {
      id: 'idea-5',
      title: 'DevSecOps SAST/DAST Gate Integration in GitLab Banking CI Pipelines',
      description: 'Fail automated builds if high or critical CVSS > 7.0 vulnerabilities are introduced without documented approved risk waiver.',
      category: 'DEVSECOPS',
      color: 'purple',
      x: 440,
      y: 340,
      status: 'IDEA',
      priority: 'P3_MEDIUM',
      assignee: 'Leyla Aliyeva (AppSec)',
      tags: ['GITLAB_CI', 'SAST', 'SECURITY_GATES'],
      createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
      updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    },
    {
      id: 'idea-6',
      title: 'Central Bank Annual Cybersecurity Audit Readiness Assessment',
      description: 'Assemble evidence repository across ISO 27001 Annex A controls, penetration testing reports, and privileged access logs.',
      category: 'COMPLIANCE',
      color: 'green',
      x: 820,
      y: 340,
      status: 'IDEA',
      priority: 'P2_HIGH',
      assignee: 'Rashad Huseynov (GRC)',
      tags: ['AUDIT', 'ISO27001', 'REGULATORY'],
      createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
      updatedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    },
  ],
  requestForms: [
    {
      id: 'form-incident',
      title: 'Report Cyber Incident / Data Leak',
      category: 'SOC & Incident Response',
      iconName: 'Flame',
      color: 'red',
      description: 'Emergency intake for detected brute-force attacks, malware, ransomware, or confidential data leakage.',
      destinationFolder: 'Incident Response Operations 📁',
      defaultSeverity: 'CRITICAL',
      defaultPriority: 'P1_URGENT',
      defaultTicketType: 'INCIDENT',
      isActive: true,
      fields: [
        { id: 'title', label: 'Incident Headline / Summary', type: 'text', required: true, placeholder: 'e.g. Suspicious unauthorized traffic to SWIFT host' },
        { id: 'urgency', label: 'Urgency Tier', type: 'select', required: true, options: ['EMERGENCY', 'HIGH', 'MEDIUM', 'LOW'], defaultValue: 'HIGH' },
        { id: 'targetSystem', label: 'Target Banking System', type: 'select', required: true, options: ['SWIFT Alliance Gateway', 'Apex Core Banking Gateway (Temenos T24)', 'Apex Retail Mobile Banking Backend API', 'Perimeter DC1 Gateway Firewall'], defaultValue: 'SWIFT Alliance Gateway' },
        { id: 'justification', label: 'Technical Evidence & Indicators', type: 'textarea', required: false, placeholder: 'Provide IP addresses, affected workstations, timestamps...' },
      ],
    },
    {
      id: 'form-exception',
      title: 'Production Firewall Exception Waiver',
      category: 'GRC Dual-Control',
      iconName: 'Lock',
      color: 'amber',
      description: 'Request 30-day temporary firewall port whitelist or cryptographic cipher waiver requiring CISO 4-eyes sign-off.',
      destinationFolder: 'Firewall & Network Exceptions 📁',
      defaultSeverity: 'HIGH',
      defaultPriority: 'P2_HIGH',
      defaultTicketType: 'SECURITY_EXCEPTION',
      isActive: true,
      fields: [
        { id: 'title', label: 'Exception Request Summary', type: 'text', required: true, placeholder: 'e.g. Temporary Port 8443 bypass for payment staging' },
        { id: 'urgency', label: 'Urgency Tier', type: 'select', required: true, options: ['EMERGENCY', 'HIGH', 'MEDIUM', 'LOW'], defaultValue: 'HIGH' },
        { id: 'targetSystem', label: 'Target Banking System', type: 'select', required: true, options: ['SWIFT Alliance Gateway', 'Apex Core Banking Gateway (Temenos T24)', 'Perimeter DC1 Gateway Firewall'], defaultValue: 'Perimeter DC1 Gateway Firewall' },
        { id: 'durationDays', label: 'Exception Validity Period', type: 'select', required: true, options: ['7', '30', '60'], defaultValue: '30' },
        { id: 'justification', label: 'Business Justification & Compensating Controls', type: 'textarea', required: true, placeholder: 'Explain business reason, impact if denied, IPS monitoring...' },
      ],
    },
    {
      id: 'form-pentest',
      title: 'Application Security Pentest Intake',
      category: 'DevSecOps & AppSec',
      iconName: 'Shield',
      color: 'blue',
      description: 'Schedule pre-release SAST, DAST, and manual penetration testing for mobile & core banking API releases.',
      destinationFolder: 'Core Banking Application Hardening 📁',
      defaultSeverity: 'MEDIUM',
      defaultPriority: 'P2_HIGH',
      defaultTicketType: 'SECURITY_REVIEW',
      isActive: true,
      fields: [
        { id: 'title', label: 'Release / Application Name', type: 'text', required: true, placeholder: 'e.g. Mobile Banking iOS v3.4 Release Pentest' },
        { id: 'targetSystem', label: 'Target Banking System', type: 'select', required: true, options: ['Apex Retail Mobile Banking Backend API', 'Apex Core Banking Gateway (Temenos T24)'], defaultValue: 'Apex Retail Mobile Banking Backend API' },
        { id: 'justification', label: 'Release Scope & Testing Schedule', type: 'textarea', required: false, placeholder: 'Endpoints to test, testing window, contact person...' },
      ],
    },
    {
      id: 'form-asset',
      title: 'New Banking Asset & Server Registration',
      category: 'CMDB & Architecture',
      iconName: 'Layers',
      color: 'green',
      description: 'Register production Linux server, firewall, or API gateway into CMDB with data classification tier.',
      destinationFolder: 'Banking Infrastructure Assets 📁',
      defaultSeverity: 'LOW',
      defaultPriority: 'P3_MEDIUM',
      defaultTicketType: 'SECURITY_REVIEW',
      isActive: true,
      fields: [
        { id: 'title', label: 'Asset Name / Hostname', type: 'text', required: true, placeholder: 'e.g. srv-dc1-auth-02.apexbank.local' },
        { id: 'targetSystem', label: 'Primary Cluster / Environment', type: 'select', required: true, options: ['DC1 Primary Datacenter', 'DC2 Disaster Recovery Datacenter', 'Cloud Private VPC'], defaultValue: 'DC1 Primary Datacenter' },
        { id: 'justification', label: 'Hardware Specs & Network Subnet', type: 'textarea', required: false, placeholder: 'IP Address, OS version, application hosted...' },
      ],
    },
  ],
  requestSubmissions: [
    {
      id: 'sub-01',
      formId: 'form-exception',
      submittedByUserId: 'usr-soc-lead',
      submittedByUserName: 'Elnur Mammadov',
      values: { title: 'Temporary Port 8443 bypass for payment staging', durationDays: '30' },
      createdTicketId: 'tick-exc-103',
      createdTicketKey: 'SEC-103',
      createdAt: new Date(Date.now() - 86400000).toISOString(),
    },
  ],
  blueprints: [
    // Cross-Department Blueprints
    {
      id: 'bp-cross-onboarding',
      shortName: 'Employee Onboarding',
      version: 1,
      isActive: true,
      projectCode: 'SEC',
      workflowId: 'wf-secops-default',
      slaPolicyId: 'sla-p1-emergency',
      parameters: [{ id: 'subject', label: 'Employee Name & Role', type: 'TEXT', required: true, placeholder: 'e.g. Aysel Mammadova — Treasury Analyst' }],
      title: 'Employee Onboarding & Security Clearance Pipeline',
      domain: 'Cross-Department Governance',
      departmentId: 'dept-hr',
      isCrossDepartment: true,
      participatingDepartments: ['dept-hr', 'dept-it', 'dept-secops', 'dept-core'],
      taskCount: 4,
      estimatedDays: 5,
      description: 'End-to-end employee onboarding workflow coordinating HR background check, IT Active Directory provisioning, Infosec PAM & YubiKey issuance, and Core Banking authorization.',
      iconName: 'Users',
      defaultTasks: [
        {
          id: 'task-onb-1',
          title: 'Step 1: HR Background & KYC Clearance Check',
          description: 'Verify identity documents, background check clearance, NDA and signed employment contract.',
          targetDepartment: 'dept-hr',
          assigneeRole: 'HR Lead',
          assigneeId: 'usr-hr-lead',
          technicalSeverity: 'MEDIUM',
          businessPriority: 'P2_HIGH',
          category: 'SECURITY_REVIEW',
          offsetDays: 0,
          durationDays: 1,
          dependsOnIndex: null,
          tags: ['HR', 'ONBOARDING', 'KYC'],
        },
        {
          id: 'task-onb-2',
          title: 'Step 2: IT Active Directory & Corporate Hardware Provisioning',
          description: 'Create AD account, provision corporate encrypted laptop, mailbox, and Cisco VPN certificate.',
          targetDepartment: 'dept-it',
          assigneeRole: 'IT Operations Lead',
          assigneeId: 'usr-it-lead',
          technicalSeverity: 'HIGH',
          businessPriority: 'P2_HIGH',
          category: 'IAM_REQUEST',
          offsetDays: 1,
          durationDays: 1,
          dependsOnIndex: 0,
          tags: ['IT_OPS', 'ACTIVE_DIRECTORY', 'LAPTOP'],
        },
        {
          id: 'task-onb-3',
          title: 'Step 3: Infosec PAM Access & Hardware FIDO2 YubiKey Issuance',
          description: 'Enroll in CyberArk PAM, issue hardware YubiKey 5C, verify MFA and assign clearance level.',
          targetDepartment: 'dept-secops',
          assigneeRole: 'SOC Operations Lead',
          assigneeId: 'usr-soc-lead',
          technicalSeverity: 'HIGH',
          businessPriority: 'P1_URGENT',
          category: 'SECURITY_REVIEW',
          offsetDays: 2,
          durationDays: 1,
          dependsOnIndex: 1,
          tags: ['INFOSEC', 'YUBIKEY', 'PAM_CLEARANCE'],
        },
        {
          id: 'task-onb-4',
          title: 'Step 4: Core Banking Operator Authorization & CISO Dual Sign-off',
          description: 'Grant role-based Temenos T24 operator access and execute final executive 4-eyes approval.',
          targetDepartment: 'dept-core',
          assigneeRole: 'Core Banking Lead',
          assigneeId: 'usr-core-lead',
          technicalSeverity: 'CRITICAL',
          businessPriority: 'P1_URGENT',
          category: 'SECURITY_REVIEW',
          offsetDays: 3,
          durationDays: 1,
          dependsOnIndex: 2,
          tags: ['CORE_BANK', 'T24', 'CISO_SIGN_OFF'],
        },
      ],
    },
    {
      id: 'bp-cross-swift',
      shortName: 'SWIFT Release Pipeline',
      version: 1,
      isActive: true,
      projectCode: 'SEC',
      workflowId: 'wf-secops-default',
      slaPolicyId: 'sla-p1-emergency',
      parameters: [{ id: 'subject', label: 'Release / Change Reference', type: 'TEXT', required: true, placeholder: 'e.g. SWIFT 2026.08 production release' }],
      title: 'SWIFT Alliance Production Release & Security Validation',
      domain: 'Payment Systems Security',
      departmentId: 'dept-core',
      isCrossDepartment: true,
      participatingDepartments: ['dept-core', 'dept-secops', 'dept-it'],
      taskCount: 3,
      estimatedDays: 7,
      description: 'Multi-department payment release protocol covering AppSec static code audit, IT infrastructure firewall ruleset, and HSM cryptographic key verification.',
      iconName: 'Shield',
      defaultTasks: [
        {
          id: 'task-swift-1',
          title: 'Step 1: AppSec SAST/DAST & Dependency Vulnerability Scan',
          description: 'Perform static code and binary verification for SWIFT Alliance patch package.',
          targetDepartment: 'dept-secops',
          assigneeRole: 'AppSec Engineer',
          assigneeId: 'usr-appsec-spec',
          technicalSeverity: 'HIGH',
          businessPriority: 'P1_URGENT',
          category: 'VULNERABILITY',
          offsetDays: 0,
          durationDays: 2,
          dependsOnIndex: null,
          tags: ['APPSEC', 'SWIFT', 'SAST'],
        },
        {
          id: 'task-swift-2',
          title: 'Step 2: IT DC1 Perimeter Firewall Rule & WAF Isolation Tuning',
          description: 'Verify Palo Alto perimeter isolation and port 9443 bidirectional TLS restriction.',
          targetDepartment: 'dept-it',
          assigneeRole: 'IT Operations Lead',
          assigneeId: 'usr-it-lead',
          technicalSeverity: 'CRITICAL',
          businessPriority: 'P1_URGENT',
          category: 'SECURITY_REVIEW',
          offsetDays: 2,
          durationDays: 2,
          dependsOnIndex: 0,
          tags: ['IT_OPS', 'FIREWALL', 'WAF'],
        },
        {
          id: 'task-swift-3',
          title: 'Step 3: Core Banking HSM Key Ceremony & Production Deployment',
          description: 'Execute Thales HSM cryptographic key ceremony and cutover SWIFT ISO 20022 traffic.',
          targetDepartment: 'dept-core',
          assigneeRole: 'Core Banking Lead',
          assigneeId: 'usr-core-lead',
          technicalSeverity: 'CRITICAL',
          businessPriority: 'P1_URGENT',
          category: 'SECURITY_REVIEW',
          offsetDays: 4,
          durationDays: 2,
          dependsOnIndex: 1,
          tags: ['CORE_BANK', 'HSM', 'SWIFT_DEPLOY'],
        },
      ],
    },

    // Department-Specific Blueprints
    {
      id: 'bp-it-server-provision',
      shortName: 'Server Provisioning',
      version: 1,
      isActive: true,
      projectCode: 'SEC',
      workflowId: 'wf-secops-default',
      slaPolicyId: 'sla-p1-emergency',
      parameters: [{ id: 'subject', label: 'Server / Service Name', type: 'TEXT', required: true, placeholder: 'e.g. payments-api-prod-03' }],
      title: 'Enterprise Virtual Server & IAM Provisioning',
      domain: 'IT Infrastructure',
      departmentId: 'dept-it',
      isCrossDepartment: false,
      taskCount: 2,
      estimatedDays: 3,
      description: 'Standardized IT Operations playbook for provisioning VMware VM, Active Directory domain join, and EDR agent installation.',
      iconName: 'Server',
      defaultTasks: [
        {
          id: 'task-it-1',
          title: 'Provision VMware Enterprise ESXi Virtual Machine',
          description: 'Allocate CPU/RAM, create virtual disks on all-flash datastore and configure VLAN 104.',
          targetDepartment: 'dept-it',
          assigneeId: 'usr-it-lead',
          technicalSeverity: 'MEDIUM',
          businessPriority: 'P2_HIGH',
          category: 'GENERAL_REQUEST',
          offsetDays: 0,
          durationDays: 2,
          tags: ['VMWARE', 'ESXI', 'PROVISIONING'],
        },
        {
          id: 'task-it-2',
          title: 'Active Directory Domain Join & GPO Hardening',
          description: 'Join server to apexbank.internal domain and apply Tier-1 CIS benchmark baseline.',
          targetDepartment: 'dept-it',
          assigneeId: 'usr-it-lead',
          technicalSeverity: 'HIGH',
          businessPriority: 'P2_HIGH',
          category: 'IAM_REQUEST',
          offsetDays: 2,
          durationDays: 1,
          tags: ['AD', 'GPO', 'HARDENING'],
        },
      ],
    },
    {
      id: 'bp-sec-appsec',
      shortName: 'AppSec Finding Lifecycle',
      version: 1,
      isActive: true,
      projectCode: 'APPSEC',
      workflowId: 'wf-secops-default',
      slaPolicyId: 'sla-p1-emergency',
      parameters: [{ id: 'subject', label: 'Application / Finding', type: 'TEXT', required: true, placeholder: 'e.g. Mobile Banking — CWE-89' }],
      title: 'AppSec SAST Hardening & Pen-Test Finding Lifecycle',
      domain: 'Application Security',
      departmentId: 'dept-secops',
      isCrossDepartment: false,
      taskCount: 2,
      estimatedDays: 14,
      description: 'Security operations workflow for remediating critical CWE/CVE vulnerabilities on customer-facing banking applications.',
      iconName: 'Shield',
      defaultTasks: [
        {
          id: 'task-sec-1',
          title: 'Static & Dynamic Vulnerability Verification in Staging',
          description: 'Replicate scanner finding using Burp Suite and Checkmarx SAST; verify exploitability.',
          targetDepartment: 'dept-secops',
          assigneeId: 'usr-appsec-spec',
          technicalSeverity: 'HIGH',
          businessPriority: 'P1_URGENT',
          category: 'VULNERABILITY',
          offsetDays: 0,
          durationDays: 7,
          tags: ['APPSEC', 'BURP', 'VERIFICATION'],
        },
        {
          id: 'task-sec-2',
          title: 'Re-test Remediated Build & Update DefectDojo Register',
          description: 'Verify patched container image in CI pipeline and close finding in GRC register.',
          targetDepartment: 'dept-secops',
          assigneeId: 'usr-appsec-spec',
          technicalSeverity: 'MEDIUM',
          businessPriority: 'P2_HIGH',
          category: 'VULNERABILITY',
          offsetDays: 7,
          durationDays: 7,
          tags: ['RETEST', 'CI_CD', 'DEFECTDOJO'],
        },
      ],
    },
  ],
  workflowRuns: [],
  proofingDocuments: [
    {
      id: 'doc-arch-01',
      title: 'SWIFT Alliance Gateway Perimeter DC1 Topology Diagram.pdf',
      documentType: 'NETWORK_ARCHITECTURE_PDF',
      fileUrl: '/assets/architecture/swift_dc1_topology.pdf',
      version: '2.4',
      classification: 'RESTRICTED',
      isSignedOff: true,
      signedByUserId: 'usr-ciso',
      signedByUserName: 'Unsal Gasimli (CISO)',
      signedAt: new Date(Date.now() - 43200000).toISOString(),
      signatureHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      annotations: [
        {
          id: 'ann-1',
          x: 35,
          y: 45,
          authorId: 'usr-ciso',
          authorName: 'Unsal Gasimli (CISO)',
          authorRole: 'CISO',
          comment: 'Verify TLS 1.3 cryptographic handshake termination on Palo Alto DC1 perimeter interface.',
          status: 'APPROVED',
          createdAt: new Date(Date.now() - 86400000).toISOString(),
        },
        {
          id: 'ann-2',
          x: 65,
          y: 30,
          authorId: 'usr-soc-lead',
          authorName: 'Elnur Mammadov (SOC Lead)',
          authorRole: 'SOC Operations Lead',
          comment: 'Rate limiting ruleset (100 req/min) active against external IP prefixes.',
          status: 'RESOLVED',
          createdAt: new Date(Date.now() - 43200000).toISOString(),
        },
      ],
      createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
      updatedAt: new Date(Date.now() - 43200000).toISOString(),
    },
  ],
  ganttDependencies: [
    {
      id: 'dep-1',
      fromTaskId: 'tick-soc-101',
      toTaskId: 'tick-appsec-102',
      type: 'FINISH_TO_START',
    },
    {
      id: 'dep-2',
      fromTaskId: 'tick-appsec-102',
      toTaskId: 'tick-exc-103',
      type: 'FINISH_TO_START',
    },
  ],
  queues: [
    {
      id: 'q-all',
      name: 'All Open Issues',
      code: 'ALL_OPEN',
      securityDomain: 'SOC',
      description: 'All unresolved security tickets across domains',
      iconName: 'Inbox',
      jqlFilter: 'status != "RESOLVED"',
      visibleColumns: ['key', 'title', 'severity', 'priority', 'status', 'assignee', 'sla'],
      slaWarningMinutes: 30,
    },
    {
      id: 'q-p1',
      name: 'P1 Critical Incidents',
      code: 'P1_CRIT',
      securityDomain: 'SOC',
      description: 'Emergency security incidents requiring immediate action',
      iconName: 'AlertTriangle',
      jqlFilter: 'priority = "P1_URGENT"',
      visibleColumns: ['key', 'title', 'severity', 'status', 'assignee', 'sla'],
      slaWarningMinutes: 15,
    },
    {
      id: 'q-sla',
      name: 'SLA Breached & At Risk',
      code: 'SLA_RISK',
      securityDomain: 'SOC',
      description: 'Tickets approaching or exceeding SLA thresholds',
      iconName: 'Clock',
      jqlFilter: 'slaState in ("BREACHED", "AT_RISK")',
      visibleColumns: ['key', 'title', 'severity', 'status', 'assignee', 'slaRemainingMinutes'],
      slaWarningMinutes: 15,
    },
  ],
  kbArticles: [
    {
      id: 'kb-sop-001',
      slug: 'sop-sec-01-cyber-incident-response-swift',
      title: 'SOP-SEC-01: Cyber Incident Response & SWIFT Triage Procedure',
      category: 'SOP',
      summary: 'Mandatory escalation, containment, and notification steps for unauthorized access against SWIFT Alliance Gateway.',
      contentMarkdown: `# SOP-SEC-01: Cyber Incident Response & SWIFT Triage Procedure

## 1. Purpose & Scope
This Standard Operating Procedure (SOP) defines the mandatory escalation, containment, and notification steps required when an unauthorized access or brute-force event is detected against Apex Bank's SWIFT Alliance Gateway.

## 2. Emergency Escalation Matrix
1. **SOC Level-1 Analyst**: Identify and classify incident severity within 15 minutes.
2. **SOC Lead**: Engage on-call incident response team and implement perimeter rate-limiting.
3. **CISO**: Provide dual-control executive sign-off for firewall policy modifications.

## 3. Regulatory Incident Notification (Central Bank)
All Tier-1 payment infrastructure breaches exceeding 60 minutes of containment threshold must be reported to the Central Bank Cyber Security Department within 2 hours.`,
      tags: ['SWIFT', 'SOP', 'CENTRAL_BANK', 'PCI_DSS'],
      authorName: 'Unsal Gasimli',
      authorRole: 'CISO',
      approvedByCiso: true,
      version: '1.0',
      lastReviewedAt: new Date().toISOString(),
      viewCount: 42,
    },
    {
      id: 'kb-sop-002',
      slug: 'sop-sec-02-dual-control-security-exception',
      title: 'SOP-SEC-02: Dual-Control Security Policy Exception Lifecycle',
      category: 'SECURITY_POLICY',
      summary: 'Under ISO 27001 & Central Bank regulations, no single individual may grant a production firewall or cryptographic policy exception.',
      contentMarkdown: `# SOP-SEC-02: Dual-Control Security Policy Exception Lifecycle

## 1. 4-Eyes Principle Authorization
Under ISO 27001 & Central Bank regulations, no single individual may grant a production firewall or cryptographic policy exception.

## 2. Multi-Stage Approval Workflow
- Step 1: Technical Review by SOC Operations Lead.
- Step 2: Risk Evaluation & Sign-off by CISO.
- Maximum exception validity is 30 calendar days.`,
      tags: ['GRC', 'DUAL_CONTROL', 'ISO_27001'],
      authorName: 'Unsal Gasimli',
      authorRole: 'CISO',
      approvedByCiso: true,
      version: '1.0',
      lastReviewedAt: new Date().toISOString(),
      viewCount: 28,
    },
  ],
  connections: [
    // 1. Information Security & Cyber Defense Connections
    {
      id: 'conn-sec-01',
      departmentId: 'dept-secops',
      name: 'Splunk Enterprise SIEM Cluster',
      type: 'SIEM',
      provider: 'Splunk Cloud / Enterprise',
      endpointUrl: 'https://siem-cluster.apexbank.internal:8089',
      authType: 'BEARER_TOKEN',
      status: 'CONNECTED',
      lastSyncAt: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
      latencyMs: 14,
      healthScore: 99,
      syncFrequencyMinutes: 1,
      description: 'Real-time security telemetry ingestion, correlation rule triggers, and alert indexing.',
      configSummary: { indexers: '4 nodes', activeRules: '142 rules', dailyVolume: '450 GB' },
      createdAt: '2026-01-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'conn-sec-02',
      departmentId: 'dept-secops',
      name: 'CrowdStrike Falcon EDR Cloud',
      type: 'EDR',
      provider: 'CrowdStrike Falcon',
      endpointUrl: 'https://api.crowdstrike.com/v2',
      authType: 'OAUTH2',
      status: 'CONNECTED',
      lastSyncAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
      latencyMs: 22,
      healthScore: 98,
      syncFrequencyMinutes: 5,
      description: 'Endpoint detection & response telemetry across 2,400 corporate endpoints and servers.',
      configSummary: { totalAgents: '2,410 active', quarantineStatus: '0 isolated' },
      createdAt: '2026-01-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'conn-sec-03',
      departmentId: 'dept-secops',
      name: 'Checkmarx SAST & SCA Engine',
      type: 'VULN_SCANNER',
      provider: 'Checkmarx One',
      endpointUrl: 'https://sast.apexbank.internal/api',
      authType: 'API_KEY',
      status: 'CONNECTED',
      lastSyncAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      latencyMs: 38,
      healthScore: 94,
      syncFrequencyMinutes: 60,
      description: 'Static application security testing and software composition analysis in CI/CD pipeline.',
      configSummary: { activeRepos: '34 scanned', criticalFindings: '3' },
      createdAt: '2026-01-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'conn-sec-04',
      departmentId: 'dept-secops',
      name: 'DefectDojo Vulnerability Hub',
      type: 'VULN_SCANNER',
      provider: 'DefectDojo Enterprise',
      endpointUrl: 'https://defectdojo.apexbank.internal/api/v2',
      authType: 'API_KEY',
      status: 'CONNECTED',
      lastSyncAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
      latencyMs: 19,
      healthScore: 96,
      syncFrequencyMinutes: 15,
      description: 'Centralized vulnerability deduplication, risk tracking and remediation SLAs.',
      configSummary: { activeEngagements: '12', deduplicatedVulns: '487' },
      createdAt: '2026-01-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },

    // 2. IT Infrastructure & Cloud Connections
    {
      id: 'conn-it-01',
      departmentId: 'dept-it',
      name: 'Active Directory Domain Services (DC01/DC02)',
      type: 'ACTIVE_DIRECTORY',
      provider: 'Microsoft Active Directory',
      endpointUrl: 'ldaps://dc01.apexbank.internal:636',
      authType: 'LDAP_BIND',
      status: 'CONNECTED',
      lastSyncAt: new Date(Date.now() - 1000 * 60 * 1).toISOString(),
      latencyMs: 4,
      healthScore: 100,
      syncFrequencyMinutes: 5,
      description: 'Central LDAP identity store, Kerberos auth, GPO policies and Security Groups sync.',
      configSummary: { domain: 'apexbank.internal', syncedUsers: '1,850', groups: '124' },
      createdAt: '2026-01-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'conn-it-02',
      departmentId: 'dept-it',
      name: 'VMware vCenter Enterprise Cluster',
      type: 'CLOUD_INFRA',
      provider: 'VMware vSphere',
      endpointUrl: 'https://vcenter.apexbank.internal/sdk',
      authType: 'MTLS_CERTIFICATE',
      status: 'CONNECTED',
      lastSyncAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
      latencyMs: 12,
      healthScore: 97,
      syncFrequencyMinutes: 10,
      description: 'Primary datacenter ESXi hypervisor hosts, cluster health, and VM provisioning.',
      configSummary: { esxiHosts: '32', runningVMs: '420', datastores: '1.2 PB' },
      createdAt: '2026-01-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'conn-it-03',
      departmentId: 'dept-it',
      name: 'AWS Hybrid Cloud VPC Gateway',
      type: 'CLOUD_INFRA',
      provider: 'Amazon Web Services',
      endpointUrl: 'https://ec2.eu-central-1.amazonaws.com',
      authType: 'API_KEY',
      status: 'CONNECTED',
      lastSyncAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
      latencyMs: 25,
      healthScore: 99,
      syncFrequencyMinutes: 15,
      description: 'Disaster recovery failover cloud environment and direct connect status.',
      configSummary: { region: 'eu-central-1', directConnectStatus: 'ACTIVE_10Gbps' },
      createdAt: '2026-01-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'conn-it-04',
      departmentId: 'dept-it',
      name: 'Cisco Meraki Core Backbone',
      type: 'COMMUNICATION',
      provider: 'Cisco Systems',
      endpointUrl: 'https://api.meraki.com/api/v1',
      authType: 'API_KEY',
      status: 'CONNECTED',
      lastSyncAt: new Date(Date.now() - 1000 * 60 * 6).toISOString(),
      latencyMs: 16,
      healthScore: 98,
      syncFrequencyMinutes: 10,
      description: 'Branch and headquarters SD-WAN VPN mesh and switch port security.',
      configSummary: { branches: '45 connected', vpnUptime: '99.99%' },
      createdAt: '2026-01-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },

    // 3. Human Resources & Legal Connections
    {
      id: 'conn-hr-01',
      departmentId: 'dept-hr',
      name: 'Workday Human Capital Management (HCM)',
      type: 'HRIS',
      provider: 'Workday Cloud',
      endpointUrl: 'https://services1.workday.com/ccx/api/v1/apexbank',
      authType: 'OAUTH2',
      status: 'CONNECTED',
      lastSyncAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
      latencyMs: 42,
      healthScore: 96,
      syncFrequencyMinutes: 60,
      description: 'Employee lifecycle, onboarding KYC background checks, job positions, and terminations.',
      configSummary: { activeEmployees: '1,850', syncStatus: 'HEALTHY' },
      createdAt: '2026-01-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'conn-hr-02',
      departmentId: 'dept-hr',
      name: '1C Enterprise Payroll & Staff Directory',
      type: 'DATABASE',
      provider: '1C Enterprise',
      endpointUrl: 'https://hr-db.apexbank.internal:8080/odata',
      authType: 'BEARER_TOKEN',
      status: 'CONNECTED',
      lastSyncAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      latencyMs: 18,
      healthScore: 92,
      syncFrequencyMinutes: 120,
      description: 'Local banking labor compliance and payroll clearance database.',
      configSummary: { schemaVersion: '8.3', lastReconciliation: 'Today 09:00' },
      createdAt: '2026-01-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'conn-hr-03',
      departmentId: 'dept-hr',
      name: 'KnowBe4 Security Training LMS',
      type: 'COMMUNICATION',
      provider: 'KnowBe4 Platform',
      endpointUrl: 'https://api.knowbe4.com/v1',
      authType: 'API_KEY',
      status: 'CONNECTED',
      lastSyncAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      latencyMs: 34,
      healthScore: 97,
      syncFrequencyMinutes: 180,
      description: 'Mandatory annual cybersecurity awareness training and simulated phishing campaigns.',
      configSummary: { phishPronePercentage: '2.4%', trainedStaff: '98.6%' },
      createdAt: '2026-01-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },

    // 4. Core Banking & SWIFT Connections
    {
      id: 'conn-core-01',
      departmentId: 'dept-core',
      name: 'SWIFT Alliance Access / Gateway',
      type: 'PAYMENT_GATEWAY',
      provider: 'SWIFT Financial',
      endpointUrl: 'https://swift-gateway.apexbank.internal:9443/alliance',
      authType: 'MTLS_CERTIFICATE',
      status: 'CONNECTED',
      lastSyncAt: new Date(Date.now() - 1000 * 60 * 1).toISOString(),
      latencyMs: 5,
      healthScore: 100,
      syncFrequencyMinutes: 1,
      description: 'SWIFT CSP compliant ISO 20022 wire transfer messaging gateway (FIN, InterAct, FileAct).',
      configSummary: { bicCode: 'APEXAZ22XXX', cspStatus: 'COMPLIANT_2026' },
      createdAt: '2026-01-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'conn-core-02',
      departmentId: 'dept-core',
      name: 'Temenos T24 Core Banking Database',
      type: 'CORE_BANKING',
      provider: 'Temenos Core',
      endpointUrl: 'tcp://t24-cluster.apexbank.internal:1521/T24PROD',
      authType: 'MTLS_CERTIFICATE',
      status: 'CONNECTED',
      lastSyncAt: new Date(Date.now() - 1000 * 60 * 1).toISOString(),
      latencyMs: 3,
      healthScore: 100,
      syncFrequencyMinutes: 1,
      description: 'Primary transactional ledger, GL accounting, retail and corporate account processing.',
      configSummary: { tps: '1,450 tx/sec', activeAccounts: '850,000' },
      createdAt: '2026-01-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'conn-core-03',
      departmentId: 'dept-core',
      name: 'Oracle Flexcube Clearing Switch',
      type: 'CORE_BANKING',
      provider: 'Oracle Financial Services',
      endpointUrl: 'https://flexcube.apexbank.internal:8002/service',
      authType: 'BEARER_TOKEN',
      status: 'CONNECTED',
      lastSyncAt: new Date(Date.now() - 1000 * 60 * 4).toISOString(),
      latencyMs: 6,
      healthScore: 98,
      syncFrequencyMinutes: 5,
      description: 'Interbank clearing, treasury operations, and liquidity management engine.',
      configSummary: { clearingRails: 'AZIPS / XOHKS', settlementStatus: 'ACTIVE' },
      createdAt: '2026-01-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'conn-core-04',
      departmentId: 'dept-core',
      name: 'Card Payment Processing Switch (VISA/MasterCard)',
      type: 'PAYMENT_GATEWAY',
      provider: 'Apex Card Switch',
      endpointUrl: 'https://card-switch.apexbank.internal:7443',
      authType: 'MTLS_CERTIFICATE',
      status: 'CONNECTED',
      lastSyncAt: new Date(Date.now() - 1000 * 60 * 1).toISOString(),
      latencyMs: 8,
      healthScore: 99,
      syncFrequencyMinutes: 1,
      description: 'PCI-DSS Tier-1 cardholder data environment, 3D-Secure 2.0 and ATM terminal processor.',
      configSummary: { pciDssStatus: 'CERTIFIED_AOC', authorizationRate: '99.8%' },
      createdAt: '2026-01-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },

    // 5. Governance, Risk & Compliance (GRC) Connections
    {
      id: 'conn-grc-01',
      departmentId: 'dept-grc',
      name: 'Central Bank Regulatory Portal Integration',
      type: 'COMMUNICATION',
      provider: 'Central Bank of Azerbaijan (CBA)',
      endpointUrl: 'https://cba-portal.gov.az/api/v1/bank-reporting',
      authType: 'MTLS_CERTIFICATE',
      status: 'CONNECTED',
      lastSyncAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
      latencyMs: 28,
      healthScore: 95,
      syncFrequencyMinutes: 360,
      description: 'Automated prudential reports, incident notification disclosures, and audit filings.',
      configSummary: { reportingLicense: 'BANK-LIC-0442', complianceStatus: 'IN_GOOD_STANDING' },
      createdAt: '2026-01-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'conn-grc-02',
      departmentId: 'dept-grc',
      name: 'OneTrust Privacy & Risk Assessment Suite',
      type: 'TICKETING',
      provider: 'OneTrust GRC',
      endpointUrl: 'https://onetrust.apexbank.internal/api',
      authType: 'API_KEY',
      status: 'CONNECTED',
      lastSyncAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
      latencyMs: 44,
      healthScore: 93,
      syncFrequencyMinutes: 720,
      description: 'Third-party vendor risk assessments, GDPR / Personal Data protection register.',
      configSummary: { assessedVendors: '84', highRiskVendors: '2' },
      createdAt: '2026-01-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },
  ],
  savedFilters: [
    { id: 'f-1', name: 'My Open Issues', jql: 'assignee = currentUser() AND status != "RESOLVED"', userId: 'usr-ciso', isGlobal: true },
    { id: 'f-2', name: 'SLA Breaches', jql: 'slaState in ("BREACHED", "AT_RISK")', userId: 'usr-ciso', isGlobal: true },
  ],
  notifications: [
    {
      id: 'notif-01',
      userId: 'usr-ciso',
      title: 'SLA At-Risk Alert: 45 Mins Remaining',
      message: 'APPSEC-2026-0001 (SQL Injection on Temenos T24) is approaching critical remediation deadline.',
      type: 'SLA_WARNING',
      severity: 'CRITICAL',
      timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
      isRead: false,
      ticketId: 'tick-appsec-102',
      ticketKey: 'APPSEC-2026-0001',
    },
    {
      id: 'notif-02',
      userId: 'usr-ciso',
      title: 'Dual-Control CISO Sign-Off Required',
      message: 'GRC-2026-0078 (Firewall Port 8443 Bypass Exception) requires executive approval.',
      type: 'APPROVAL',
      severity: 'HIGH',
      timestamp: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
      isRead: false,
      ticketId: 'tick-exc-103',
      ticketKey: 'GRC-2026-0078',
    },
  ],
};
