import { v4 as uuidv4 } from 'uuid';
import { z } from 'zod';
import type { BankUser } from '../../shared/types/auth.js';
import type { CIRecordLink, CIRelationship, CIType, ConfigurationItem, RelationshipType, CMDBGraph } from '../../shared/types/cmdb.js';
import { db } from '../db/database.js';
import { AuditService } from './audit.service.js';
import { OutboxService } from './outbox.service.js';

const enterpriseCmdbRoles = ['PLATFORM_ADMIN', 'CISO', 'INFOSEC_ADMIN', 'IT_ADMIN', 'CORE_BANK_ADMIN'];
const scopedCmdbRoles = ['INFOSEC_MANAGER', 'DEPARTMENT_ADMIN', 'DEPARTMENT_MANAGER', 'TEAM_LEAD'];
const dependencyRelationshipIds = new Set(['depends_on', 'runs_on', 'uses', 'backed_by', 'stores_data_in', 'authenticates_via', 'protected_by', 'supports', 'part_of']);
const lifecycleTransitions: Record<string, string[]> = {
  REQUESTED: ['PROCURED'], PROCURED: ['RECEIVED'], RECEIVED: ['IN_STOCK'], IN_STOCK: ['ASSIGNED', 'MAINTENANCE', 'RETIRED'],
  ASSIGNED: ['IN_USE', 'RETURNED', 'LOST'], IN_USE: ['MAINTENANCE', 'RETURNED', 'LOST', 'RETIRED'], MAINTENANCE: ['IN_STOCK', 'IN_USE', 'RETIRED'],
  RETURNED: ['IN_STOCK', 'RETIRED'], RETIRED: ['DISPOSED'], DISPOSED: [], LOST: ['RETURNED', 'RETIRED'],
};
const initialLifecycleStatuses = new Set(['REQUESTED', 'PROCURED', 'RECEIVED', 'IN_STOCK']);

const createSchema = z.object({
  name: z.string().trim().min(1).max(255), displayName: z.string().trim().min(1).max(255).optional(), typeId: z.string().trim().min(1), description: z.string().max(5000).optional(),
  environment: z.enum(['DEV', 'TEST', 'UAT', 'STAGING', 'PRODUCTION', 'DR', 'UNKNOWN']).default('UNKNOWN'),
  criticality: z.enum(['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']).default('MEDIUM'), businessCriticality: z.enum(['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']).optional(), lifecycleStatus: z.enum(['REQUESTED', 'PROCURED', 'RECEIVED', 'IN_STOCK', 'ASSIGNED', 'IN_USE', 'MAINTENANCE', 'RETURNED', 'RETIRED', 'DISPOSED', 'LOST']).default('IN_STOCK'),
  ownerUserId: z.string().optional(), technicalOwnerUserId: z.string().optional(), businessOwnerUserId: z.string().optional(), supportGroupId: z.string().optional(), departmentId: z.string().optional(),
  locationId: z.string().trim().max(128).optional(), vendor: z.string().trim().max(255).optional(), assetTag: z.string().trim().max(128).optional(), serialNumber: z.string().trim().max(128).optional(), hostname: z.string().trim().max(255).optional(), fqdn: z.string().trim().max(255).optional(), ipAddress: z.string().trim().max(64).optional(), macAddress: z.string().trim().max(64).optional(),
  manufacturer: z.string().trim().max(255).optional(), model: z.string().trim().max(255).optional(), operatingSystem: z.string().trim().max(255).optional(), osVersion: z.string().trim().max(128).optional(), externalReference: z.string().trim().max(255).optional(),
  source: z.enum(['MANUAL', 'ACTIVE_DIRECTORY', 'SCCM', 'INTUNE', 'VMWARE', 'SERVICE_DISCOVERY', 'IMPORT', 'API', 'SECURITY_PLATFORM']).default('MANUAL'), sourceSystem: z.string().trim().max(128).optional(), sourceRecordId: z.string().trim().max(255).optional(), details: z.record(z.unknown()).default({}),
}).strict();

const updateSchema = createSchema.partial().extend({ version: z.number().int().positive(), discoveryStatus: z.enum(['NOT_DISCOVERED', 'DISCOVERED', 'SYNCED', 'ERROR']).optional(), lastSeenAt: z.string().datetime().optional(), lastSyncAt: z.string().datetime().optional(), lastVerifiedAt: z.string().datetime().optional(), syncStatus: z.enum(['PENDING', 'SYNCED', 'ERROR']).optional() }).strict();

// `details` is a controlled subtype payload, not a free-form EAV bag. The
// relational CI columns remain the canonical cross-type fields; these schemas
// keep subtype facts bounded and independently evolvable by CI class.
const discoveryMetadataShape = { discovery: z.record(z.unknown()).optional(), mergedExternalReferences: z.array(z.string().max(255)).max(100).optional(), mergedCiNumbers: z.array(z.string().max(64)).max(100).optional() };
const assetDetailsSchema = z.object({
  ...discoveryMetadataShape, purchaseDate: z.string().date().optional(), warrantyExpiration: z.string().date().optional(), supplier: z.string().trim().max(255).optional(), costCenter: z.string().trim().max(128).optional(), assignedUserId: z.string().min(1).optional(), assignedDepartmentId: z.string().min(1).optional(), ownershipType: z.enum(['OWNED', 'LEASED', 'RENTED', 'THIRD_PARTY']).optional(), physicalLocation: z.string().trim().max(255).optional(), inventoryStatus: z.enum(['IN_STOCK', 'ASSIGNED', 'MAINTENANCE', 'MISSING', 'RETIRED']).optional(), cloudProvider: z.string().trim().max(128).optional(), cloudRegion: z.string().trim().max(128).optional(),
}).strict();
const applicationDetailsSchema = z.object({
  ...discoveryMetadataShape, applicationCode: z.string().trim().max(128).optional(), applicationType: z.string().trim().max(128).optional(), architecture: z.string().trim().max(255).optional(), technologyStack: z.array(z.string().trim().max(128)).max(50).optional(), repositoryUrl: z.string().url().max(2048).optional(), documentationUrl: z.string().url().max(2048).optional(), productionUrl: z.string().url().max(2048).optional(), dataClassification: z.enum(['PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED']).optional(), internetExposure: z.boolean().optional(), authenticationMethod: z.string().trim().max(255).optional(), rtoMinutes: z.number().int().min(0).max(525600).optional(), rpoMinutes: z.number().int().min(0).max(525600).optional(), slaId: z.string().trim().max(128).optional(), securityLeadId: z.string().min(1).optional(), developmentTeamId: z.string().min(1).optional(),
}).strict();
const businessServiceDetailsSchema = z.object({
  ...discoveryMetadataShape, serviceCode: z.string().trim().max(128).optional(), serviceTier: z.enum(['TIER_1', 'TIER_2', 'TIER_3']).optional(), slaId: z.string().trim().max(128).optional(), rtoMinutes: z.number().int().min(0).max(525600).optional(), rpoMinutes: z.number().int().min(0).max(525600).optional(), availabilityTarget: z.number().min(0).max(100).optional(), customerFacing: z.boolean().optional(), regulatoryCritical: z.boolean().optional(), serviceOwnerUserId: z.string().min(1).optional(),
}).strict();
const technicalDetailsSchema = z.object(discoveryMetadataShape).strict();
const assetTypeIds = new Set(['physical_server', 'virtual_machine', 'network_device', 'firewall', 'storage', 'load_balancer', 'laptop', 'desktop', 'mobile_device', 'cloud_resource']);
const savedViewSchema = z.object({ name: z.string().trim().min(2).max(128), isGlobal: z.boolean().default(false), filters: z.object({ search: z.string().max(255).optional(), typeId: z.string().max(64).optional(), environment: z.string().max(32).optional(), lifecycleStatus: z.string().max(32).optional(), ownerUserId: z.string().max(64).optional(), quality: z.string().max(64).optional(), sortBy: z.string().max(64).optional() }).strict() }).strict();

export class CMDBError extends Error { constructor(public statusCode: number, message: string) { super(message); } }

export class CMDBService {
  static ensureReferenceData(): void {
    if (db.data.cmdbTypes.length || db.data.cmdbRelationshipTypes.length) return;
    const now = new Date().toISOString();
    const types: Array<[string, string, string | undefined]> = [
      ['infrastructure', 'Infrastructure', undefined], ['physical_server', 'Physical Server', 'infrastructure'], ['virtual_machine', 'Virtual Machine', 'infrastructure'], ['network_device', 'Network Device', 'infrastructure'], ['firewall', 'Firewall', 'infrastructure'], ['storage', 'Storage', 'infrastructure'], ['load_balancer', 'Load Balancer', 'infrastructure'],
      ['endpoint', 'Endpoint', undefined], ['laptop', 'Laptop', 'endpoint'], ['desktop', 'Desktop', 'endpoint'], ['mobile_device', 'Mobile Device', 'endpoint'],
      ['software', 'Software', undefined], ['application', 'Application', 'software'], ['api', 'API', 'software'], ['database', 'Database', 'software'], ['middleware', 'Middleware', 'software'], ['business_service', 'Business Service', undefined], ['technical_service', 'Technical Service', undefined], ['certificate', 'Certificate', 'infrastructure'], ['cloud_resource', 'Cloud Resource', 'infrastructure'],
    ];
    db.data.cmdbTypes = types.map(([id, name, parentTypeId]) => ({ id, name, parentTypeId, icon: 'Box', isActive: true, requiredAttributes: ['name', 'environment', 'criticality'], optionalAttributes: ['ownerUserId', 'departmentId', 'hostname', 'assetTag'], validationRules: {}, allowedRelationshipTypeIds: [], createdAt: now, updatedAt: now }));
    const relations: Array<[string, string, string, boolean]> = [
      ['depends_on', 'DEPENDS_ON', 'IS_DEPENDENCY_OF', true], ['runs_on', 'RUNS_ON', 'HOSTS', true], ['hosts', 'HOSTS', 'RUNS_ON', false], ['connected_to', 'CONNECTED_TO', 'CONNECTED_TO', false], ['uses', 'USES', 'USED_BY', true], ['provides', 'PROVIDES', 'CONSUMED_BY', false], ['member_of', 'MEMBER_OF', 'HAS_MEMBER', true], ['backed_by', 'BACKED_BY', 'BACKS', true], ['stores_data_in', 'STORES_DATA_IN', 'STORES_DATA_FOR', true], ['authenticates_via', 'AUTHENTICATES_VIA', 'AUTHENTICATES', true], ['protected_by', 'PROTECTED_BY', 'PROTECTS', true], ['monitored_by', 'MONITORED_BY', 'MONITORS', false], ['supports', 'SUPPORTS', 'SUPPORTED_BY', true], ['part_of', 'PART_OF', 'HAS_PART', true],
    ];
    db.data.cmdbRelationshipTypes = relations.map(([id, name, inverseName, preventsCycles]) => ({ id, name, inverseName, isDependency: dependencyRelationshipIds.has(id), preventsCycles, isActive: true, createdAt: now, updatedAt: now }));
    db.persist();
  }

  static canManage(user: BankUser, ci?: ConfigurationItem): boolean {
    if (user.roles.some((role) => enterpriseCmdbRoles.includes(role))) return true;
    if (!ci) return user.roles.some((role) => scopedCmdbRoles.includes(role));
    if (user.roles.some((role) => scopedCmdbRoles.includes(role)) && ci.departmentId === user.departmentId) return true;
    return Boolean(ci && [ci.ownerUserId, ci.technicalOwnerUserId, ci.businessOwnerUserId].includes(user.id));
  }

  static list(user: BankUser, query: Record<string, unknown> = {}): { items: ConfigurationItem[]; total: number; page: number; pageSize: number } {
    this.ensureReferenceData();
    const page = Math.max(1, Number(query.page) || 1); const pageSize = Math.min(100, Math.max(1, Number(query.pageSize) || 25));
    const text = String(query.search || '').trim().toLowerCase();
    let items = db.data.configurationItems.filter((ci) => !ci.archivedAt || query.includeArchived === 'true');
    const filters: Array<[keyof ConfigurationItem, string]> = [['typeId', 'typeId'], ['environment', 'environment'], ['criticality', 'criticality'], ['lifecycleStatus', 'lifecycleStatus'], ['departmentId', 'departmentId'], ['ownerUserId', 'ownerUserId'], ['status', 'status']];
    for (const [field, name] of filters) if (query[name]) items = items.filter((ci) => String(ci[field] || '') === String(query[name]));
    const exactFilters: Array<[keyof ConfigurationItem, string]> = [['assetTag', 'assetTag'], ['serialNumber', 'serialNumber'], ['hostname', 'hostname'], ['manufacturer', 'manufacturer'], ['model', 'model'], ['locationId', 'locationId']];
    for (const [field, name] of exactFilters) if (query[name]) items = items.filter((ci) => String(ci[field] || '').toLowerCase() === String(query[name]).toLowerCase());
    if (query.assetOnly === 'true') items = items.filter((ci) => ['physical_server', 'virtual_machine', 'network_device', 'firewall', 'storage', 'load_balancer', 'laptop', 'desktop', 'mobile_device', 'cloud_resource'].includes(ci.typeId));
    if (query.applicationOnly === 'true') items = items.filter((ci) => ci.typeId === 'application');
    if (query.businessServiceOnly === 'true') items = items.filter((ci) => ci.typeId === 'business_service');
    if (query.quality === 'missing-owner') items = items.filter((ci) => !ci.ownerUserId && !ci.technicalOwnerUserId);
    if (query.quality === 'stale') items = items.filter((ci) => !ci.lastVerifiedAt || Date.now() - Date.parse(ci.lastVerifiedAt) > 90 * 86400000);
    if (query.quality === 'no-relationships') items = items.filter((ci) => !db.data.ciRelationships.some((relationship) => relationship.status === 'ACTIVE' && !relationship.archivedAt && (relationship.sourceCiId === ci.id || relationship.targetCiId === ci.id)));
    if (query.quality === 'duplicate-candidate') items = items.filter((ci) => this.duplicateCandidates(ci.id).length > 0);
    if (query.quality === 'unverified') items = items.filter((ci) => !ci.lastVerifiedAt);
    if (query.quality === 'missing-criticality') items = items.filter((ci) => !ci.criticality);
    if (text) items = items.filter((ci) => [ci.name, ci.ciNumber, ci.assetTag, ci.serialNumber, ci.hostname, ci.fqdn, ci.ipAddress].filter(Boolean).some((value) => String(value).toLowerCase().includes(text)));
    const sortBy = String(query.sortBy || 'updatedAt'); const sortable = new Set(['ciNumber', 'name', 'typeId', 'status', 'environment', 'criticality', 'lifecycleStatus', 'updatedAt', 'lastVerifiedAt', 'relationshipCount']); const direction = String(query.sortDirection || 'desc').toLowerCase() === 'asc' ? 1 : -1;
    const relationshipCount = (ci: ConfigurationItem) => db.data.ciRelationships.filter((relationship) => relationship.status === 'ACTIVE' && !relationship.archivedAt && (relationship.sourceCiId === ci.id || relationship.targetCiId === ci.id)).length;
    const total = items.length; items = items.sort((a, b) => { if (!sortable.has(sortBy)) return b.updatedAt.localeCompare(a.updatedAt); const left = sortBy === 'relationshipCount' ? relationshipCount(a) : String((a as any)[sortBy] || ''); const right = sortBy === 'relationshipCount' ? relationshipCount(b) : String((b as any)[sortBy] || ''); return typeof left === 'number' && typeof right === 'number' ? (left - right) * direction : String(left).localeCompare(String(right)) * direction; });
    return { items: items.slice((page - 1) * pageSize, page * pageSize).map((item) => this.withQuality(item)), total, page, pageSize };
  }

  static get(id: string): ConfigurationItem {
    this.ensureReferenceData(); const ci = db.data.configurationItems.find((item) => item.id === id && !item.archivedAt); if (!ci) throw new CMDBError(404, 'Configuration item not found.'); return this.withQuality(ci);
  }

  static create(raw: unknown, actor: BankUser): ConfigurationItem {
    this.ensureReferenceData(); if (!this.canManage(actor)) throw new CMDBError(403, 'CMDB create permission is required.');
    const input = createSchema.parse(raw); this.assertInitialLifecycle(input.lifecycleStatus, input.source, actor); this.assertDepartmentCreateScope(actor, input.departmentId); this.assertReferences(input); this.assertNoDuplicate(input);
    const now = new Date().toISOString(); const ci: ConfigurationItem = { id: `ci-${uuidv4()}`, ciNumber: `CI-${new Date().getUTCFullYear()}-${String(db.data.configurationItems.length + 1).padStart(6, '0')}`, name: input.name, displayName: input.displayName || input.name, typeId: input.typeId, status: input.lifecycleStatus === 'RETIRED' || input.lifecycleStatus === 'DISPOSED' ? 'RETIRED' : 'ACTIVE', lifecycleStatus: input.lifecycleStatus, environment: input.environment, criticality: input.criticality, businessCriticality: input.businessCriticality, description: input.description, ownerUserId: input.ownerUserId, technicalOwnerUserId: input.technicalOwnerUserId, businessOwnerUserId: input.businessOwnerUserId, supportGroupId: input.supportGroupId, departmentId: input.departmentId || actor.departmentId, locationId: input.locationId, vendor: input.vendor, assetTag: input.assetTag, serialNumber: input.serialNumber, hostname: input.hostname, fqdn: input.fqdn, ipAddress: input.ipAddress, macAddress: input.macAddress, manufacturer: input.manufacturer, model: input.model, operatingSystem: input.operatingSystem, osVersion: input.osVersion, externalReference: input.externalReference, source: input.source, sourceSystem: input.sourceSystem, sourceRecordId: input.sourceRecordId, discoveryStatus: input.source === 'MANUAL' ? 'NOT_DISCOVERED' : 'SYNCED', lastSyncAt: input.source === 'MANUAL' ? undefined : now, syncStatus: input.source === 'MANUAL' ? undefined : 'SYNCED', details: input.details, version: 1, createdAt: now, updatedAt: now, createdBy: actor.id, updatedBy: actor.id };
    db.data.configurationItems.unshift(ci); this.audit(actor, 'CMDB_CI_CREATED', 'CONFIGURATION_ITEM', ci.id, { name: ci.name, ciNumber: ci.ciNumber }); OutboxService.enqueue({ topic: 'cmdb.ci.created', aggregateType: 'CONFIGURATION_ITEM', aggregateId: ci.id, payload: { ciId: ci.id, actorId: actor.id, criticality: ci.criticality, typeId: ci.typeId, departmentId: ci.departmentId, internetExposed: Boolean((ci.details as any).internetExposure), dataClassification: (ci.details as any).dataClassification } }); db.persist(); return this.withQuality(ci);
  }

  static update(id: string, raw: unknown, actor: BankUser): ConfigurationItem {
    this.get(id); const ci = db.data.configurationItems.find((item) => item.id === id && !item.archivedAt)!; if (!this.canManage(actor, ci)) throw new CMDBError(403, 'CMDB update permission is required.'); const input = updateSchema.parse(raw);
    if (input.version !== ci.version) throw new CMDBError(409, 'This CI was changed by another user. Refresh before saving.');
    const candidate = { ...ci, ...input, details: input.details ?? ci.details }; this.assertDepartmentUpdateScope(actor, ci, candidate); this.assertReferences(candidate); this.assertNoDuplicate(candidate, ci.id);
    if (input.lifecycleStatus && input.lifecycleStatus !== ci.lifecycleStatus) this.assertLifecycleTransition(ci.lifecycleStatus, input.lifecycleStatus, actor);
    const changes = Object.entries(input).filter(([key, value]) => key !== 'version' && JSON.stringify((ci as any)[key]) !== JSON.stringify(value)).map(([field, newValue]) => ({ field, oldValue: (ci as any)[field], newValue }));
    Object.assign(ci, candidate, { version: ci.version + 1, updatedAt: new Date().toISOString(), updatedBy: actor.id });
    if (ci.lifecycleStatus === 'RETIRED' || ci.lifecycleStatus === 'DISPOSED') ci.status = 'RETIRED';
    this.audit(actor, ci.status === 'RETIRED' ? 'CMDB_CI_RETIRED' : 'CMDB_CI_UPDATED', 'CONFIGURATION_ITEM', ci.id, { changes }, changes); if (changes.some((change) => ['details', 'typeId', 'environment', 'criticality', 'businessCriticality', 'departmentId', 'technicalOwnerUserId', 'businessOwnerUserId'].includes(change.field))) OutboxService.enqueue({ topic: 'cmdb.ci.material-change', aggregateType: 'CONFIGURATION_ITEM', aggregateId: ci.id, payload: { ciId: ci.id, actorId: actor.id, changedFields: changes.map((change) => change.field) } }); db.persist(); return this.withQuality(ci);
  }

  static relationship(ciId: string, raw: unknown, actor: BankUser): CIRelationship {
    const source = this.get(ciId); if (!this.canManage(actor, source)) throw new CMDBError(403, 'Relationship management permission is required.');
    const input = z.object({ targetCiId: z.string().min(1), relationshipTypeId: z.string().min(1), description: z.string().max(2000).optional(), confidence: z.number().min(0).max(100).default(100), source: z.enum(['MANUAL', 'DISCOVERY', 'IMPORT', 'API']).default('MANUAL') }).strict().parse(raw);
    const target = this.get(input.targetCiId); if (source.id === target.id) throw new CMDBError(400, 'A CI cannot have a relationship to itself.'); const type = db.data.cmdbRelationshipTypes.find((item) => item.id === input.relationshipTypeId && item.isActive); if (!type) throw new CMDBError(400, 'Relationship type is invalid.');
    const sourceType = db.data.cmdbTypes.find((item) => item.id === source.typeId);
    if (sourceType?.allowedRelationshipTypeIds.length && !sourceType.allowedRelationshipTypeIds.includes(type.id)) throw new CMDBError(400, `${sourceType.name} CIs cannot use the ${type.name} relationship type.`);
    if (db.data.ciRelationships.some((item) => item.status === 'ACTIVE' && !item.archivedAt && item.sourceCiId === source.id && item.targetCiId === target.id && item.relationshipTypeId === type.id)) throw new CMDBError(409, 'That active relationship already exists.');
    if (type.preventsCycles && this.reaches(target.id, source.id, type.id)) throw new CMDBError(409, 'This relationship would create a prohibited dependency cycle.');
    const now = new Date().toISOString(); const relationship: CIRelationship = { id: `cir-${uuidv4()}`, sourceCiId: source.id, targetCiId: target.id, relationshipTypeId: type.id, status: 'ACTIVE', description: input.description, source: input.source, confidence: input.confidence, validFrom: now, createdAt: now, createdBy: actor.id }; db.data.ciRelationships.unshift(relationship); this.audit(actor, 'CMDB_RELATIONSHIP_CREATED', 'CI_RELATIONSHIP', relationship.id, { sourceCiId: source.id, targetCiId: target.id, relationshipType: type.name }); db.persist(); return relationship;
  }

  static removeRelationship(id: string, actor: BankUser): void { const relationship = db.data.ciRelationships.find((item) => item.id === id && !item.archivedAt); if (!relationship) throw new CMDBError(404, 'Relationship not found.'); const source = this.get(relationship.sourceCiId); if (!this.canManage(actor, source)) throw new CMDBError(403, 'Relationship management permission is required.'); relationship.status = 'INACTIVE'; relationship.archivedAt = new Date().toISOString(); this.audit(actor, 'CMDB_RELATIONSHIP_REMOVED', 'CI_RELATIONSHIP', id, { sourceCiId: relationship.sourceCiId, targetCiId: relationship.targetCiId }); db.persist(); }

  static relationships(id: string): { upstream: CIRelationship[]; downstream: CIRelationship[] } { this.get(id); const active = db.data.ciRelationships.filter((item) => item.status === 'ACTIVE' && !item.archivedAt); return { upstream: active.filter((item) => item.sourceCiId === id), downstream: active.filter((item) => item.targetCiId === id) }; }

  static graph(id: string, query: Record<string, unknown>): CMDBGraph { this.get(id); const depth = Math.min(3, Math.max(1, Number(query.depth) || 1)); const direction = String(query.direction || 'both'); const permittedTypes = String(query.relationshipTypes || '').split(',').filter(Boolean); const permittedCiTypes = String(query.ciTypes || '').split(',').filter(Boolean); const queue: Array<{ id: string; level: number }> = [{ id, level: 0 }]; const visited = new Set<string>([id]); const edges: CIRelationship[] = [];
    while (queue.length) { const current = queue.shift()!; if (current.level >= depth) continue; for (const relationship of db.data.ciRelationships.filter((item) => item.status === 'ACTIVE' && !item.archivedAt && (!permittedTypes.length || permittedTypes.includes(item.relationshipTypeId)))) { const outbound = relationship.sourceCiId === current.id; const inbound = relationship.targetCiId === current.id; if (!outbound && !inbound) continue; if (direction === 'upstream' && !outbound) continue; if (direction === 'downstream' && !inbound) continue; edges.push(relationship); const adjacent = outbound ? relationship.targetCiId : relationship.sourceCiId; if (!visited.has(adjacent)) { visited.add(adjacent); queue.push({ id: adjacent, level: current.level + 1 }); } } }
    const typeMap = new Map(db.data.cmdbRelationshipTypes.map((type) => [type.id, type])); const displayNodes = db.data.configurationItems.filter((item) => visited.has(item.id) && !item.archivedAt && (item.id === id || !permittedCiTypes.length || permittedCiTypes.includes(item.typeId))); const displayIds = new Set(displayNodes.map((node) => node.id)); return { nodes: displayNodes.map(({ id: ciId, ciNumber, name, displayName, typeId, status, criticality, environment }) => ({ id: ciId, ciNumber, name, displayName, typeId, status, criticality, environment })), edges: [...new Map(edges.map((edge) => [edge.id, edge])).values()].filter((edge) => displayIds.has(edge.sourceCiId) && displayIds.has(edge.targetCiId)).map((edge) => ({ id: edge.id, source: edge.sourceCiId, target: edge.targetCiId, relationshipTypeId: edge.relationshipTypeId, relationshipType: typeMap.get(edge.relationshipTypeId)?.name || edge.relationshipTypeId })) }; }

  static impact(id: string): Record<string, unknown> { this.get(id); const maxDepth = 6; const queue: Array<{ id: string; path: string[]; depth: number }> = [{ id, path: [id], depth: 0 }]; const affected = new Map<string, string[]>(); while (queue.length) { const current = queue.shift()!; if (current.depth >= maxDepth) continue; for (const rel of db.data.ciRelationships.filter((item) => item.status === 'ACTIVE' && !item.archivedAt && item.targetCiId === current.id && dependencyRelationshipIds.has(item.relationshipTypeId))) { if (current.path.includes(rel.sourceCiId)) continue; const path = [...current.path, rel.sourceCiId]; if (!affected.has(rel.sourceCiId)) { affected.set(rel.sourceCiId, path); queue.push({ id: rel.sourceCiId, path, depth: current.depth + 1 }); } } }
    const items = [...affected.entries()].map(([ciId, path]) => ({ ci: this.get(ciId), path })); return { directDependencies: items.filter((item) => item.path.length === 2), transitiveDependencies: items.filter((item) => item.path.length > 2), affectedBusinessServices: items.filter((item) => item.ci.typeId === 'business_service'), criticalServices: items.filter((item) => item.ci.typeId === 'business_service' && item.ci.criticality === 'CRITICAL'), maxDepth }; }

  static linkRecord(ciId: string, raw: unknown, actor: BankUser): CIRecordLink { const ci = this.get(ciId); if (!this.canManage(actor, ci)) throw new CMDBError(403, 'CMDB update permission is required.'); const input = z.object({ recordType: z.enum(['TICKET', 'INCIDENT', 'SERVICE_REQUEST', 'CHANGE', 'PROBLEM', 'VULNERABILITY', 'PROJECT', 'TASK']), recordId: z.string().min(1), relationship: z.enum(['AFFECTED_BY', 'RELATED_TO', 'IMPLEMENTED_BY']).default('AFFECTED_BY') }).parse(raw); if (db.data.ciRecordLinks.some((link) => link.ciId === ciId && link.recordId === input.recordId && link.recordType === input.recordType)) throw new CMDBError(409, 'That record is already linked to the CI.'); const link = { id: `cil-${uuidv4()}`, ciId, ...input, createdAt: new Date().toISOString(), createdBy: actor.id }; db.data.ciRecordLinks.unshift(link); this.audit(actor, 'CMDB_CI_UPDATED', 'CONFIGURATION_ITEM', ciId, { recordLink: { recordType: input.recordType, recordId: input.recordId, relationship: input.relationship } }); db.persist(); return link; }
  static relatedRecords(ciId: string): CIRecordLink[] { this.get(ciId); return db.data.ciRecordLinks.filter((link) => link.ciId === ciId); }
  static ticketContext(ticketId: string): Array<{ ci: ConfigurationItem; relationship: CIRecordLink['relationship']; impact: Record<string, unknown> }> {
    return db.data.ciRecordLinks.filter((link) => link.recordType === 'TICKET' && link.recordId === ticketId).flatMap((link) => {
      try { return [{ ci: this.get(link.ciId), relationship: link.relationship, impact: this.impact(link.ciId) }]; } catch { return []; }
    });
  }
  static linkTicketOnCreate(ciId: string, ticketId: string, actor: BankUser): CIRecordLink { this.get(ciId); if (db.data.ciRecordLinks.some((link) => link.ciId === ciId && link.recordType === 'TICKET' && link.recordId === ticketId)) throw new CMDBError(409, 'That ticket is already linked to the CI.'); const link: CIRecordLink = { id: `cil-${uuidv4()}`, ciId, recordType: 'TICKET', recordId: ticketId, relationship: 'AFFECTED_BY', createdAt: new Date().toISOString(), createdBy: actor.id }; db.data.ciRecordLinks.unshift(link); this.audit(actor, 'CMDB_CI_UPDATED', 'CONFIGURATION_ITEM', ciId, { recordLink: { recordType: 'TICKET', recordId: ticketId, relationship: 'AFFECTED_BY' } }); return link; }

  static history(id: string) { this.get(id); return AuditService.getEventsForEntity(id); }
  static duplicateCandidates(id: string): Array<{ ci: ConfigurationItem; matchedFields: string[] }> {
    const ci = this.get(id); const comparable: Array<keyof ConfigurationItem> = ['assetTag', 'serialNumber', 'hostname', 'fqdn', 'ipAddress', 'externalReference'];
    return db.data.configurationItems.filter((candidate) => candidate.id !== ci.id && !candidate.archivedAt).map((candidate) => ({ ci: this.withQuality(candidate), matchedFields: comparable.filter((field) => ci[field] && candidate[field] && String(ci[field]).toLowerCase() === String(candidate[field]).toLowerCase()) })).filter((candidate) => candidate.matchedFields.length > 0 || (candidate.ci.typeId === ci.typeId && candidate.ci.name.trim().toLowerCase() === ci.name.trim().toLowerCase()));
  }
  static types(): CIType[] { this.ensureReferenceData(); return db.data.cmdbTypes.filter((type) => type.isActive); }
  static savedViews(actor: BankUser): Array<{ id: string; name: string; isGlobal: boolean; filters: Record<string, string> }> { return db.data.savedFilters.filter((view) => view.jql.startsWith('CMDB:') && (view.isGlobal || view.userId === actor.id)).flatMap((view) => { try { const filters = JSON.parse(view.jql.slice(5)); return [{ id: view.id, name: view.name, isGlobal: view.isGlobal, filters }]; } catch { return []; } }); }
  static saveView(raw: unknown, actor: BankUser): { id: string; name: string; isGlobal: boolean; filters: Record<string, string> } { const input = savedViewSchema.parse(raw); if (input.isGlobal) this.assertGovernance(actor); const view = { id: `cmdb-view-${uuidv4()}`, name: input.name, jql: `CMDB:${JSON.stringify(input.filters)}`, userId: actor.id, isGlobal: input.isGlobal }; db.data.savedFilters.unshift(view); db.persist(); return { id: view.id, name: view.name, isGlobal: view.isGlobal, filters: input.filters as Record<string, string> }; }
  static relationshipTypes(): RelationshipType[] { this.ensureReferenceData(); return db.data.cmdbRelationshipTypes.filter((type) => type.isActive); }
  static createType(raw: unknown, actor: BankUser): CIType { this.ensureReferenceData(); this.assertGovernance(actor); const input = z.object({ id: z.string().regex(/^[a-z0-9_]{2,64}$/), name: z.string().trim().min(2).max(128), parentTypeId: z.string().optional(), icon: z.string().trim().max(64).default('Box'), requiredAttributes: z.array(z.string()).default([]), optionalAttributes: z.array(z.string()).default([]), validationRules: z.record(z.unknown()).default({}), allowedRelationshipTypeIds: z.array(z.string()).default([]) }).strict().parse(raw); if (db.data.cmdbTypes.some((type) => type.id === input.id || type.name.toLowerCase() === input.name.toLowerCase())) throw new CMDBError(409, 'CI type id or name already exists.'); if (input.parentTypeId && !db.data.cmdbTypes.some((type) => type.id === input.parentTypeId)) throw new CMDBError(400, 'Parent CI type does not exist.'); const now = new Date().toISOString(); const type: CIType = { ...input, isActive: true, createdAt: now, updatedAt: now }; db.data.cmdbTypes.push(type); this.audit(actor, 'ADMIN_CONFIG_CHANGED', 'CONFIGURATION_ITEM', type.id, { governance: 'ci_type_created', name: type.name }); db.persist(); return type; }
  static updateType(id: string, raw: unknown, actor: BankUser): CIType { this.ensureReferenceData(); this.assertGovernance(actor); const type = db.data.cmdbTypes.find((item) => item.id === id); if (!type) throw new CMDBError(404, 'CI type not found.'); const input = z.object({ name: z.string().trim().min(2).max(128).optional(), parentTypeId: z.string().nullable().optional(), icon: z.string().trim().max(64).optional(), isActive: z.boolean().optional(), requiredAttributes: z.array(z.string()).optional(), optionalAttributes: z.array(z.string()).optional(), validationRules: z.record(z.unknown()).optional(), allowedRelationshipTypeIds: z.array(z.string()).optional() }).strict().parse(raw); if (input.parentTypeId && (!db.data.cmdbTypes.some((item) => item.id === input.parentTypeId) || input.parentTypeId === id)) throw new CMDBError(400, 'Parent CI type is invalid.'); Object.assign(type, input, { updatedAt: new Date().toISOString() }); this.audit(actor, 'ADMIN_CONFIG_CHANGED', 'CONFIGURATION_ITEM', id, { governance: 'ci_type_updated' }); db.persist(); return type; }
  static createRelationshipType(raw: unknown, actor: BankUser): RelationshipType { this.ensureReferenceData(); this.assertGovernance(actor); const input = z.object({ id: z.string().regex(/^[a-z0-9_]{2,64}$/), name: z.string().trim().min(2).max(64), inverseName: z.string().trim().min(2).max(64), isDependency: z.boolean().default(false), preventsCycles: z.boolean().default(false) }).strict().parse(raw); if (db.data.cmdbRelationshipTypes.some((type) => type.id === input.id || type.name.toLowerCase() === input.name.toLowerCase())) throw new CMDBError(409, 'Relationship type id or name already exists.'); const now = new Date().toISOString(); const type: RelationshipType = { ...input, isActive: true, createdAt: now, updatedAt: now }; db.data.cmdbRelationshipTypes.push(type); this.audit(actor, 'ADMIN_CONFIG_CHANGED', 'CI_RELATIONSHIP', type.id, { governance: 'relationship_type_created', name: type.name }); db.persist(); return type; }
  static updateRelationshipType(id: string, raw: unknown, actor: BankUser): RelationshipType { this.ensureReferenceData(); this.assertGovernance(actor); const type = db.data.cmdbRelationshipTypes.find((item) => item.id === id); if (!type) throw new CMDBError(404, 'Relationship type not found.'); const input = z.object({ name: z.string().trim().min(2).max(64).optional(), inverseName: z.string().trim().min(2).max(64).optional(), isDependency: z.boolean().optional(), preventsCycles: z.boolean().optional(), isActive: z.boolean().optional() }).strict().parse(raw); Object.assign(type, input, { updatedAt: new Date().toISOString() }); this.audit(actor, 'ADMIN_CONFIG_CHANGED', 'CI_RELATIONSHIP', id, { governance: 'relationship_type_updated' }); db.persist(); return type; }
  static merge(sourceCiId: string, targetCiId: string, actor: BankUser): ConfigurationItem {
    this.ensureReferenceData(); this.assertGovernance(actor); if (sourceCiId === targetCiId) throw new CMDBError(400, 'A CI cannot be merged into itself.');
    this.get(sourceCiId); this.get(targetCiId); const source = db.data.configurationItems.find((item) => item.id === sourceCiId && !item.archivedAt)!; const target = db.data.configurationItems.find((item) => item.id === targetCiId && !item.archivedAt)!; const now = new Date().toISOString();
    db.transaction(() => {
      const externalReferences = Array.from(new Set([...(Array.isArray((target.details as any).mergedExternalReferences) ? (target.details as any).mergedExternalReferences : []), source.externalReference, source.sourceSystem && source.sourceRecordId ? `${source.sourceSystem}:${source.sourceRecordId}` : undefined].filter(Boolean)));
      const sourceRelationships = db.data.ciRelationships.filter((relationship) => relationship.status === 'ACTIVE' && !relationship.archivedAt && (relationship.sourceCiId === source.id || relationship.targetCiId === source.id));
      for (const relationship of sourceRelationships) {
        const nextSource = relationship.sourceCiId === source.id ? target.id : relationship.sourceCiId;
        const nextTarget = relationship.targetCiId === source.id ? target.id : relationship.targetCiId;
        const duplicate = nextSource === nextTarget || db.data.ciRelationships.some((candidate) => candidate.id !== relationship.id && candidate.status === 'ACTIVE' && !candidate.archivedAt && candidate.sourceCiId === nextSource && candidate.targetCiId === nextTarget && candidate.relationshipTypeId === relationship.relationshipTypeId);
        if (duplicate) { relationship.status = 'INACTIVE'; relationship.archivedAt = now; continue; }
        relationship.sourceCiId = nextSource; relationship.targetCiId = nextTarget;
      }
      for (const link of db.data.ciRecordLinks.filter((item) => item.ciId === source.id)) {
        const exists = db.data.ciRecordLinks.some((candidate) => candidate.id !== link.id && candidate.ciId === target.id && candidate.recordType === link.recordType && candidate.recordId === link.recordId && candidate.relationship === link.relationship);
        if (exists) link.ciId = source.id; else link.ciId = target.id;
      }
      target.details = { ...target.details, mergedExternalReferences: externalReferences, mergedCiNumbers: Array.from(new Set([...(Array.isArray((target.details as any).mergedCiNumbers) ? (target.details as any).mergedCiNumbers : []), source.ciNumber])) };
      target.updatedBy = actor.id; target.updatedAt = now; target.version += 1;
      const persistedSource = db.data.configurationItems.find((item) => item.id === source.id)!; persistedSource.status = 'ARCHIVED'; persistedSource.archivedAt = now; persistedSource.updatedAt = now; persistedSource.updatedBy = actor.id; persistedSource.version += 1;
      this.audit(actor, 'CMDB_CI_MERGED', 'CONFIGURATION_ITEM', target.id, { sourceCiId: source.id, sourceCiNumber: source.ciNumber, targetCiNumber: target.ciNumber });
    });
    return this.get(target.id);
  }

  private static withQuality(ci: ConfigurationItem): ConfigurationItem { const missing: string[] = []; if (!ci.ownerUserId && !ci.technicalOwnerUserId) missing.push('Owner'); if (!ci.departmentId) missing.push('Department'); if (!ci.typeId) missing.push('CI type'); if (!ci.environment || ci.environment === 'UNKNOWN') missing.push('Environment'); if (!ci.criticality) missing.push('Criticality'); if (!ci.lastVerifiedAt || Date.now() - Date.parse(ci.lastVerifiedAt) > 90 * 86400000) missing.push('Recent verification'); if (!ci.sourceSystem && ci.source !== 'MANUAL') missing.push('Source system'); if (!ci.assetTag && !ci.serialNumber && !ci.hostname && !ci.fqdn && !ci.externalReference) missing.push('Unique identifier'); if (!db.data.ciRelationships.some((relation) => relation.status === 'ACTIVE' && !relation.archivedAt && (relation.sourceCiId === ci.id || relation.targetCiId === ci.id))) missing.push('Relationship'); return { ...ci, details: { ...ci.details, quality: { score: Math.round(((9 - missing.length) / 9) * 100), missing } } }; }
  private static reaches(from: string, destination: string, relationshipTypeId: string): boolean { const seen = new Set<string>(); const visit = (current: string): boolean => { if (current === destination) return true; if (seen.has(current)) return false; seen.add(current); return db.data.ciRelationships.some((rel) => rel.status === 'ACTIVE' && !rel.archivedAt && rel.relationshipTypeId === relationshipTypeId && rel.sourceCiId === current && visit(rel.targetCiId)); }; return visit(from); }
  private static assertLifecycleTransition(from: string, to: string, actor: BankUser): void { if (from === to) return; if (from === 'DISPOSED' && this.canManage(actor)) throw new CMDBError(409, 'Disposed CIs require a privileged restore procedure and cannot be returned to service here.'); if (!lifecycleTransitions[from]?.includes(to)) throw new CMDBError(400, `Invalid lifecycle transition: ${from} → ${to}.`); }
  private static assertInitialLifecycle(status: string, source: string, actor: BankUser): void { if (initialLifecycleStatuses.has(status)) return; if (source === 'IMPORT' && actor.roles.some((role) => enterpriseCmdbRoles.includes(role))) return; throw new CMDBError(400, 'New CIs must begin in an approved intake lifecycle state. Historical imported records require an enterprise CMDB administrator.'); }
  private static assertReferences(input: any): void { if (!db.data.cmdbTypes.some((type) => type.id === input.typeId && type.isActive)) throw new CMDBError(400, 'CI type is invalid or inactive.'); this.assertSubtypeDetails(input.typeId, input.details || {}); for (const owner of [input.ownerUserId, input.technicalOwnerUserId, input.businessOwnerUserId, input.details?.assignedUserId, input.details?.serviceOwnerUserId, input.details?.securityLeadId]) if (owner && !db.data.users.some((user) => user.id === owner && user.isActive)) throw new CMDBError(400, 'CI owner must be an active directory user.'); for (const departmentId of [input.departmentId, input.details?.assignedDepartmentId]) if (departmentId && !db.data.departments.some((department) => department.id === departmentId && department.isActive !== false)) throw new CMDBError(400, 'Department is invalid or inactive.'); }
  private static assertSubtypeDetails(typeId: string, details: unknown): void { const schema = typeId === 'application' ? applicationDetailsSchema : typeId === 'business_service' ? businessServiceDetailsSchema : assetTypeIds.has(typeId) ? assetDetailsSchema : technicalDetailsSchema; try { schema.parse(details); } catch { throw new CMDBError(400, `Invalid ${typeId} metadata. Only approved fields for this CI type may be stored.`); } }
  private static assertDepartmentCreateScope(actor: BankUser, departmentId?: string): void { if (departmentId && departmentId !== actor.departmentId && !actor.roles.some((role) => enterpriseCmdbRoles.includes(role))) throw new CMDBError(403, 'Only an enterprise CMDB administrator can create a CI for another department.'); }
  private static assertDepartmentUpdateScope(actor: BankUser, current: ConfigurationItem, candidate: ConfigurationItem): void { if (candidate.departmentId !== current.departmentId && !actor.roles.some((role) => enterpriseCmdbRoles.includes(role))) throw new CMDBError(403, 'Only an enterprise CMDB administrator can move a CI between departments.'); }
  private static assertNoDuplicate(input: any, exceptId?: string): void { const keys: Array<keyof ConfigurationItem> = ['assetTag', 'serialNumber', 'hostname', 'fqdn']; const applicationCode = String(input.details?.applicationCode || '').trim().toLowerCase(); const duplicate = db.data.configurationItems.find((ci) => !ci.archivedAt && ci.id !== exceptId && (keys.some((key) => input[key] && ci[key] && String(input[key]).toLowerCase() === String(ci[key]).toLowerCase()) || (applicationCode && String(ci.details?.applicationCode || '').trim().toLowerCase() === applicationCode) || (input.sourceSystem && input.sourceRecordId && ci.sourceSystem === input.sourceSystem && ci.sourceRecordId === input.sourceRecordId))); if (duplicate) throw new CMDBError(409, `Potential duplicate CI detected: ${duplicate.ciNumber} (${duplicate.name}).`); }
  private static audit(actor: BankUser, action: any, entityType: any, entityId: string, metadata: Record<string, unknown>, fieldChanges?: any[]): void { AuditService.log({ actor, action, entityType, entityId, fieldChanges, metadata, persist: false }); }
  private static assertGovernance(actor: BankUser): void { if (!actor.roles.some((role) => ['PLATFORM_ADMIN', 'CISO', 'INFOSEC_ADMIN'].includes(role))) throw new CMDBError(403, 'CMDB governance administrator permission is required.'); }
}
