import crypto from 'node:crypto';
import dns from 'node:dns/promises';
import { isIP } from 'node:net';
import { pgClient } from '../db/postgres/client.js';
import { resolveSecret } from '../utils/crypto.js';
import { DiscoveryIngestionService, type DiscoveryPayloadMapper } from './discovery-ingestion.service.js';
import type { NormalizedDiscoveryDto } from '../../shared/utils/cmdb-discovery-contract.js';
import type { BankUser } from '../../shared/types/auth.js';
import { isPrivateOrLocalAddress } from '../integrations/vcenter/vcenter-endpoint-policy.js';

type LibreDevice = Record<string, unknown>;
const text = (value: unknown) => typeof value === 'string' && value.trim() ? value.trim().slice(0, 2048) : typeof value === 'number' && Number.isFinite(value) ? String(value) : undefined;
const ip = (value: unknown) => { const candidate = text(value); return candidate && isIP(candidate) ? candidate : undefined; };
const mac = (value: unknown) => { const candidate = text(value); return candidate && /^[0-9a-f]{2}([:-][0-9a-f]{2}){5}$/i.test(candidate) ? candidate : undefined; };
const parseJson = (value: unknown) => { try { return typeof value === 'string' ? JSON.parse(value) : value || {}; } catch { return {}; } };

type LibreConfig = { endpointUrl: string; apiToken: string; endpointAllowPrivateNetwork: boolean; tlsVerifyCertificates: boolean; requestTimeoutMs: number; responseSizeLimitBytes: number };
function configFor(row: any): LibreConfig {
  const configuration = row.non_secret_configuration || {}; const endpointUrl = String(configuration.endpointUrl || '').trim();
  const match = /^env:\/\/([A-Z][A-Z0-9_]*)$/.exec(String(row.secret_reference || ''));
  const secret = match ? process.env[match[1]] : undefined;
  if (!endpointUrl || !match || !secret) throw Object.assign(new Error('LibreNMS endpoint and server-side API token reference are required.'), { code: 'LIBRENMS_CONFIG_INVALID' });
  return { endpointUrl, apiToken: resolveSecret(secret), endpointAllowPrivateNetwork: Boolean(row.endpoint_allow_private_network), tlsVerifyCertificates: row.tls_verify_certificates !== false, requestTimeoutMs: Number(row.request_timeout_ms || 30000), responseSizeLimitBytes: Number(configuration.responseSizeLimitBytes || 4_194_304) };
}
async function endpoint(config: LibreConfig): Promise<URL> {
  let url: URL; try { url = new URL(config.endpointUrl); } catch { throw Object.assign(new Error('LibreNMS endpoint must be a valid HTTPS origin.'), { code: 'LIBRENMS_CONFIG_INVALID' }); }
  if (url.protocol !== 'https:' || url.username || url.password || !['','/'].includes(url.pathname) || url.search || url.hash || !config.tlsVerifyCertificates) throw Object.assign(new Error('LibreNMS requires an HTTPS origin without credentials, path, query, or fragment and TLS verification enabled.'), { code: 'LIBRENMS_CONFIG_INVALID' });
  const host = url.hostname.toLowerCase();
  if ((host === 'localhost' || host.endsWith('.local') || isPrivateOrLocalAddress(host)) && !config.endpointAllowPrivateNetwork) throw Object.assign(new Error('Private or local LibreNMS targets require explicit approval.'), { code: 'LIBRENMS_PRIVATE_TARGET_BLOCKED' });
  if (!isIP(host)) {
    let addresses: { address: string }[];
    try {
      addresses = await dns.lookup(host, { all: true, verbatim: true });
    } catch {
      throw Object.assign(new Error(`LibreNMS host “${host}” cannot be resolved by the application DNS. Verify the HTTPS origin and DNS visibility from the application container.`), { statusCode: 422, code: 'LIBRENMS_DNS_FAILED', details: { host } });
    }
    if (!addresses.length) throw Object.assign(new Error(`LibreNMS host “${host}” did not return an address in the application DNS.`), { statusCode: 422, code: 'LIBRENMS_DNS_FAILED', details: { host } });
    if (!config.endpointAllowPrivateNetwork && addresses.some((entry) => isPrivateOrLocalAddress(entry.address))) throw Object.assign(new Error(`LibreNMS host “${host}” resolves to a private address. Explicitly approve this private-network target before testing or syncing.`), { statusCode: 422, code: 'LIBRENMS_PRIVATE_TARGET_BLOCKED', details: { host } });
  }
  return url;
}
async function getJson(config: LibreConfig, path: string): Promise<any> {
  const base = await endpoint(config); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), config.requestTimeoutMs);
  try { const response = await fetch(new URL(`/api/v0${path}`, base), { method: 'GET', redirect: 'error', headers: { Accept: 'application/json', 'X-Auth-Token': config.apiToken }, signal: controller.signal }); const length = Number(response.headers.get('content-length') || 0); if (length > config.responseSizeLimitBytes) throw Object.assign(new Error('LibreNMS response exceeded the configured limit.'), { statusCode: 422, code: 'LIBRENMS_RESPONSE_TOO_LARGE' }); const body = await response.text(); if (body.length > config.responseSizeLimitBytes) throw Object.assign(new Error('LibreNMS response exceeded the configured limit.'), { statusCode: 422, code: 'LIBRENMS_RESPONSE_TOO_LARGE' }); let parsed: any; try { parsed = JSON.parse(body); } catch { throw Object.assign(new Error('LibreNMS returned a non-JSON response.'), { statusCode: 422, code: 'LIBRENMS_INVALID_RESPONSE' }); } if (!response.ok || String(parsed?.status || '').toLowerCase() === 'error') throw Object.assign(new Error(String(parsed?.message || `LibreNMS request failed (HTTP ${response.status}).`)), { statusCode: 422, code: 'LIBRENMS_API_ERROR' }); return parsed; } catch (error: any) { if (error?.code) throw error; const timedOut = error?.name === 'AbortError'; throw Object.assign(new Error(timedOut ? 'LibreNMS did not respond before the configured timeout.' : 'LibreNMS HTTPS connection could not be established. Verify network reachability, firewall rules, and TLS trust.'), { statusCode: 422, code: timedOut ? 'LIBRENMS_CONNECTION_TIMEOUT' : 'LIBRENMS_CONNECTION_FAILED' }); } finally { clearTimeout(timer); }
}
export const libreNmsPayloadMapper: DiscoveryPayloadMapper<LibreDevice> = {
  name: 'librenms-network-devices-v1', normalizedSchemaVersion: 1,
  validateRaw(raw) { const record = raw as LibreDevice; if (!record || !text(record.device_id)) throw new Error('LibreNMS device_id is required.'); return record; },
  normalize(record, envelope): NormalizedDiscoveryDto {
    const deviceId = text(record.device_id)!; const hostname = text(record.hostname) || text(record.sysName); const display = text(record.display) || text(record.sysName) || hostname || deviceId; const primaryIp = ip(record.ip); const serial = text(record.serial); const hardware = text(record.hardware); const os = text(record.os); const version = text(record.version); const deviceType = text(record.type) || 'network'; const baseMac = mac(record.mac);
    const identifiers: NormalizedDiscoveryDto['identity']['identifiers'] = [{ type: 'OTHER', namespace: `${envelope.connectorId}:LIBRENMS_DEVICE_ID`, value: deviceId, confidence: 100, primary: true }]; if (serial) identifiers.push({ type: 'SERIAL_NUMBER', namespace: 'GLOBAL', value: serial, confidence: 95, primary: false }); if (hostname?.includes('.')) identifiers.push({ type: 'FQDN', namespace: 'DNS', value: hostname, confidence: 85, primary: false }); if (baseMac) identifiers.push({ type: 'MAC_ADDRESS', namespace: 'GLOBAL', value: baseMac, confidence: 80, primary: false });
    return { schemaVersion: 1, source: { connectorId: envelope.connectorId, objectType: 'LIBRENMS_DEVICE', objectId: deviceId, nativeUuid: deviceId }, identity: { name: display, ...(hostname ? { hostname: hostname.split('.')[0], fqdn: hostname.includes('.') ? hostname : undefined } : {}), ...(serial ? { serialNumber: serial } : {}), identifiers }, classification: { type: /firewall/i.test(`${deviceType} ${os} ${hardware || ''}`) ? 'firewall' : 'network_device', subtype: hardware || os || deviceType, environment: 'UNKNOWN' }, compute: {}, operatingSystem: { ...(os ? { reported: os } : {}), ...(version ? { version } : {}) }, network: { interfaces: primaryIp || baseMac ? [{ key: `librenms-${deviceId}`, name: 'Management interface', technicalState: String(record.status || 'UNKNOWN'), virtual: false, macAddresses: baseMac ? [baseMac] : [], ipAddresses: primaryIp ? [{ address: primaryIp, role: 'MANAGEMENT', primary: true, dynamic: false }] : [] }] : [] }, storage: { disks: [] }, placement: { relationships: [] }, tags: [{ key: 'source', value: 'LibreNMS' }, ...(text(record.location) ? [{ key: 'librenmsLocation', value: text(record.location)! }] : [])], technicalState: String(record.status || 'UNKNOWN'), sourceSpecificMetadata: { libreNms: { deviceId, hostname, sysName: text(record.sysName), display: text(record.display), ip: primaryIp, os, hardware, version, serial, type: deviceType, status: record.status, disabled: record.disabled, ignore: record.ignore, uptime: record.uptime, location: record.location, raw: record } } };
  },
};
export class LibreNmsInventorySyncService {
  public static async testConnection(connectorId: string) { const row = (await pgClient.query<any>("SELECT * FROM cmdb_discovery_connectors WHERE id=$1 AND connector_type_id='LIBRENMS' AND deleted_at IS NULL", [connectorId])).rows[0]; if (!row) throw Object.assign(new Error('LibreNMS connector was not found.'), { statusCode: 404, code: 'DISCOVERY_CONNECTOR_NOT_FOUND' }); const data = await getJson(configFor(row), '/devices?order=hostname&type=all'); const count = Array.isArray(data.devices) ? data.devices.length : 0; await pgClient.query("UPDATE cmdb_discovery_connectors SET health_status='HEALTHY',operational_state=CASE WHEN enabled THEN 'READY' ELSE 'DISABLED' END,last_connection_test_at=NOW(),last_successful_connection_at=NOW(),last_failure_at=NULL,last_failure_code=NULL,last_failure_message=NULL,consecutive_failures=0,updated_at=NOW() WHERE id=$1", [connectorId]); return { connectorId, testResult: { status: 'SUCCEEDED', transport: 'HTTPS', tlsVerification: 'ENABLED', apiVersion: 'v0', readableDeviceCount: count, inventoryAccess: count ? 'READABLE' : 'NO_DEVICES_VISIBLE', ...(count ? {} : { operatorAction: 'The API token is authenticated but no devices are visible. Verify that the LibreNMS API-token user has global or device-group access, or confirm that this LibreNMS instance contains monitored devices.' }) } }; }
  public static async enqueue(connectorId: string, actor: BankUser, runType: 'FULL' | 'INCREMENTAL' = 'FULL', context: { correlationId?: string } = {}) { const runId = `dsrun-${crypto.randomUUID()}`; try { await pgClient.transaction(async (client) => { const connector = await client.query("SELECT id FROM cmdb_discovery_connectors WHERE id=$1 AND connector_type_id='LIBRENMS' AND enabled AND deleted_at IS NULL FOR UPDATE", [connectorId]); if (!connector.rows[0]) throw Object.assign(new Error('Enabled LibreNMS connector was not found.'), { statusCode: 404, code: 'DISCOVERY_CONNECTOR_NOT_FOUND' }); await client.query("INSERT INTO cmdb_discovery_sync_runs(id,connector_id,run_type,state,requested_by_user_id,correlation_id,queued_at,checkpoint) VALUES($1,$2,$3,'QUEUED',$4,$5,NOW(),$6)", [runId, connectorId, runType, actor.id, context.correlationId || `cmdb.discovery.sync:${runId}`, 'Awaiting LibreNMS network-device inventory']); await client.query("INSERT INTO outbox_events(id,topic,aggregate_type,aggregate_id,payload,correlation_id,occurred_at) VALUES($1,'cmdb.discovery.sync.requested','DISCOVERY_SYNC_RUN',$2,$3::jsonb,$4,NOW())", [`out-${crypto.randomUUID()}`, runId, JSON.stringify({ runId, connectorId, connectorType: 'LIBRENMS', actorId: actor.id, runType }), context.correlationId || `cmdb.discovery.sync:${runId}`]); }); } catch (error: any) { if (error?.code === '23505') throw Object.assign(new Error('Another inventory sync is already running for this LibreNMS connector.'), { statusCode: 409, code: 'CONNECTOR_SYNC_LOCKED' }); throw error; } return { runId, state: 'QUEUED' as const, runType }; }
  public static async runQueued(runId: string) { const run = await pgClient.transaction(async (client) => { const row = (await client.query<any>("SELECT r.connector_id,r.state,c.* FROM cmdb_discovery_sync_runs r JOIN cmdb_discovery_connectors c ON c.id=r.connector_id WHERE r.id=$1 AND c.connector_type_id='LIBRENMS' FOR UPDATE", [runId])).rows[0]; if (!row) throw Object.assign(new Error('LibreNMS discovery run was not found.'), { code: 'DISCOVERY_RUN_NOT_FOUND' }); if (['SUCCEEDED','PARTIAL','FAILED','CANCELLED'].includes(row.state)) return row; await client.query("UPDATE cmdb_discovery_sync_runs SET state='RUNNING',started_at=COALESCE(started_at,NOW()),checkpoint='Fetching LibreNMS /api/v0/devices',updated_at=NOW() WHERE id=$1", [runId]); return row; }); if (['SUCCEEDED','PARTIAL','FAILED','CANCELLED'].includes(run.state)) return { runId, discovered: 0, failed: 0, state: run.state }; try { const devices = (await getJson(configFor(run), '/devices?order=hostname&type=all')).devices; if (!Array.isArray(devices)) throw Object.assign(new Error('LibreNMS devices response did not contain a devices array.'), { code: 'LIBRENMS_INVALID_RESPONSE' }); await pgClient.query("UPDATE cmdb_discovery_sync_runs SET requested_count=$2,received_count=$2,checkpoint='Normalizing LibreNMS network-device inventory',updated_at=NOW() WHERE id=$1", [runId, devices.length]); const observedAt = new Date().toISOString(); const batch = await DiscoveryIngestionService.ingestBatch(devices.map((device: LibreDevice) => ({ connectorId: run.connector_id, syncRunId: runId, sourceObjectType: 'LIBRENMS_DEVICE', sourceObjectId: String(device.device_id), observedAt, rawPayload: device })), libreNmsPayloadMapper); if (batch.failed.length) await DiscoveryIngestionService.completePartialRun(runId, { reason: 'INVALID_LIBRENMS_RECORDS', failedRecords: batch.failed.length }); else await DiscoveryIngestionService.reconcileAndCompleteRun(runId); return { runId, discovered: batch.succeeded.length, failed: batch.failed.length, state: batch.failed.length ? 'PARTIAL' : 'SUCCEEDED' }; } catch (error) { await DiscoveryIngestionService.failRun(runId, error); throw error; } }
}
