import { pgClient } from '../db/postgres/client.js';
import { CONFIDENTIALITY_LEVELS } from './auth.service.js';
import type { BankUser } from '../../shared/types/auth.js';
import { securityReviewer } from './threat-model-policy.js';

/** All aggregates use the same model scope and clearance as details; no global-count side channel. */
export class ThreatReportingService {
  static async report(actor:BankUser){
    if(!actor.isActive)throw new Error('Inactive user access is restricted.');
    const elevated=securityReviewer(actor)||actor.roles.includes('AUDITOR');
    const classifications=Object.entries(CONFIDENTIALITY_LEVELS).filter(([,level])=>level<=(CONFIDENTIALITY_LEVELS[actor.securityClearance]||0)).map(([name])=>name);
    const prefix=`WITH visible AS MATERIALIZED (SELECT m.* FROM threat_models m WHERE m.data_classification=ANY($3::varchar[]) AND ($1::boolean OR $2 IN (m.business_owner_id,m.technical_owner_id,m.security_owner_id) OR EXISTS(SELECT 1 FROM threat_model_active_grants g WHERE g.threat_model_id=m.id AND g.user_id=$2))), active AS (SELECT * FROM visible WHERE status NOT IN ('RETIRED','ARCHIVED')) `;
    const query=(sql:string)=>pgClient.query(prefix+sql,[elevated,actor.id,classifications]);
    const [models,threats,controls,exceptions,timing,backlog,requirements,compliance,applications]=await Promise.all([
      query(`SELECT criticality,count(*)::int AS total,count(*) FILTER(WHERE status='APPROVED')::int AS approved,count(*) FILTER(WHERE status='REVIEW_REQUIRED')::int AS review_required,count(*) FILTER(WHERE next_review_at<now())::int AS overdue,count(*) FILTER(WHERE next_review_at BETWEEN now() AND now()+interval '30 days')::int AS expiring FROM active GROUP BY criticality`),
      query(`SELECT count(*) FILTER(WHERE t.status NOT IN ('MITIGATED','CLOSED'))::int AS open_total,count(*) FILTER(WHERE t.status NOT IN ('MITIGATED','CLOSED') AND t.inherent_score>=16)::int AS critical_open,count(*) FILTER(WHERE t.status NOT IN ('MITIGATED','CLOSED') AND t.inherent_score BETWEEN 10 AND 15)::int AS high_open,count(*) FILTER(WHERE NOT EXISTS(SELECT 1 FROM threat_control_threats c WHERE c.threat_id=t.id))::int AS without_controls,COALESCE(round(avg(extract(epoch FROM (now()-t.created_at))/86400) FILTER(WHERE t.status NOT IN ('MITIGATED','CLOSED'))::numeric,1),0) AS average_open_age_days FROM threats t JOIN active m ON m.current_revision_id=t.revision_id`),
      query(`SELECT count(*) FILTER(WHERE c.status='VERIFIED' AND v.result='PASS' AND (v.expires_at IS NULL OR v.expires_at>now()))::int AS verified,count(*) FILTER(WHERE c.status='FAILED')::int AS failed,count(*) FILTER(WHERE c.status NOT IN ('NOT_APPLICABLE','ACCEPTED_RISK') AND (c.status<>'VERIFIED' OR v.result IS DISTINCT FROM 'PASS' OR v.expires_at<=now()))::int AS unverified,count(*) FILTER(WHERE v.expires_at<=now())::int AS expired_verifications FROM threat_controls c JOIN threats t ON t.id=c.threat_id JOIN active m ON m.current_revision_id=t.revision_id LEFT JOIN LATERAL(SELECT result,expires_at FROM control_verifications WHERE control_id=c.id ORDER BY executed_at DESC,id DESC LIMIT 1) v ON true`),
      query(`SELECT count(*) FILTER(WHERE e.status='APPROVED' AND e.expires_at>now() AND e.threat_content_version=t.content_version AND e.architecture_version=r.architecture_version)::int AS active,count(*) FILTER(WHERE e.status='APPROVED' AND e.expires_at BETWEEN now() AND now()+interval '30 days' AND e.threat_content_version=t.content_version AND e.architecture_version=r.architecture_version)::int AS expiring,count(*) FILTER(WHERE e.status IN ('APPROVED','EXPIRED') AND e.expires_at<=now())::int AS expired,count(*) FILTER(WHERE e.status='APPROVED' AND (e.threat_content_version<>t.content_version OR e.architecture_version<>r.architecture_version))::int AS stale FROM threat_model_exceptions e JOIN threats t ON t.id=e.threat_id JOIN threat_model_revisions r ON r.id=t.revision_id JOIN active m ON m.current_revision_id=r.id`),
      query(`SELECT COALESCE(round(avg(extract(epoch FROM(r.approved_at-r.submitted_at))/3600)::numeric,1),0) AS average_approval_hours FROM threat_model_revisions r JOIN visible m ON m.id=r.threat_model_id WHERE r.approved_at IS NOT NULL AND r.submitted_at IS NOT NULL`),
      query(`SELECT b.tier,count(*)::int AS total,count(*) FILTER(WHERE m.status='APPROVED')::int AS approved,count(*) FILTER(WHERE b.target_date<now() AND m.status IS DISTINCT FROM 'APPROVED')::int AS overdue FROM threat_model_migration_backlog b LEFT JOIN visible m ON m.id=b.current_threat_model_id WHERE m.id IS NOT NULL OR (b.current_threat_model_id IS NULL AND b.owner_id=$2 AND 'CONFIDENTIAL_SECURITY_ONLY'=ANY($3::varchar[])) GROUP BY b.tier`),
      query(`SELECT count(*)::int AS total,count(*) FILTER(WHERE r.mandatory AND NOT EXISTS(SELECT 1 FROM threat_requirement_controls c JOIN threat_model_evidence e ON e.control_id=c.control_id AND e.revision_id=r.revision_id JOIN ticket_attachments a ON a.id=e.attachment_id WHERE c.requirement_id=r.id AND a.source_payload->>'virusScanStatus'='CLEAN' AND a.sha256_hash ~ '^[a-fA-F0-9]{64}$'))::int AS without_evidence FROM threat_security_requirements r JOIN active m ON m.current_revision_id=r.revision_id`),
      query(`SELECT c.framework,c.framework_version,c.code,c.current_validation_status,count(DISTINCT s.id)::int AS mapped_requirements,count(DISTINCT s.id) FILTER(WHERE EXISTS(SELECT 1 FROM threat_requirement_controls rc JOIN threat_controls ctl ON ctl.id=rc.control_id JOIN control_verifications v ON v.control_id=ctl.id WHERE rc.requirement_id=s.id AND ctl.status='VERIFIED' AND v.result='PASS' AND (v.expires_at IS NULL OR v.expires_at>now())))::int AS requirements_with_verified_control FROM threat_compliance_details c JOIN threat_requirement_compliance rc ON rc.compliance_id=c.id JOIN threat_security_requirements s ON s.id=rc.requirement_id JOIN active m ON m.current_revision_id=s.revision_id GROUP BY c.id,c.framework,c.framework_version,c.code,c.current_validation_status ORDER BY c.framework,c.code LIMIT 200`),
      // CI-backed applications replace matching legacy rows; no duplicate inventory is created.
      query(`, apps AS (SELECT c.id FROM configuration_items c JOIN cmdb_ci_types t ON t.id=c.type_id WHERE c.archived_at IS NULL AND c.status NOT IN ('RETIRED','ARCHIVED') AND (lower(t.name) IN ('application','business application','business service') OR lower(t.id) IN ('application','business_application','business_service')) AND 'CONFIDENTIAL_SECURITY_ONLY'=ANY($3::varchar[]) AND ($1 OR $2 IN(c.owner_user_id,c.technical_owner_user_id,c.business_owner_user_id)) UNION ALL SELECT a.id FROM bank_applications a WHERE NOT EXISTS(SELECT 1 FROM configuration_items c WHERE c.id=a.id) AND 'CONFIDENTIAL_SECURITY_ONLY'=ANY($3::varchar[]) AND ($1 OR $2 IN(a.technical_owner_id,a.business_owner_id))) SELECT count(*)::int AS total,count(*) FILTER(WHERE EXISTS(SELECT 1 FROM active m WHERE m.service_id=a.id))::int AS with_model,count(*) FILTER(WHERE EXISTS(SELECT 1 FROM active m WHERE m.service_id=a.id AND m.status='APPROVED' AND m.next_review_at>now()))::int AS current_approved FROM apps a`),
    ]);
    const coverage=Object.fromEntries(models.rows.map(row=>[row.criticality,{total:row.total,approved:row.approved,reviewRequired:row.review_required,overdue:row.overdue,expiring:row.expiring,percent:row.total?Math.round(row.approved/row.total*100):0}]));
    const migrationCoverage=Object.fromEntries(backlog.rows.map(row=>[row.tier,{total:row.total,approved:row.approved,overdue:row.overdue,percent:row.total?Math.round(row.approved/row.total*100):0}]));
    const app=applications.rows[0];
    return {coverage,migrationCoverage,applicationCoverage:{...app,percent:app.total?Math.round(app.with_model/app.total*100):0,denominator:'Authorized active canonical applications/services; each requires screening, not necessarily a full model'},threats:threats.rows[0],controls:controls.rows[0],exceptions:exceptions.rows[0],requirements:requirements.rows[0],compliance:compliance.rows,averageApprovalHours:Number(timing.rows[0].average_approval_hours),generatedAt:new Date().toISOString(),scope:'Authorized models and clearance only; mappings are not compliance certification'};
  }
}
