export interface AuditEvent {
  id: string;
  timestamp: string;
  actorId: string;
  actorName: string;
  actorRole: string;
  ipAddress: string;
  userAgent: string;
  correlationId: string;
  
  action:
    | 'TICKET_CREATED'
    | 'TICKET_UPDATED'
    | 'TICKET_ARCHIVED'
    | 'STATUS_TRANSITIONED'
    | 'ASSIGNMENT_CHANGED'
    | 'COMMENT_ADDED'
    | 'ATTACHMENT_UPLOADED'
    | 'ATTACHMENT_DOWNLOADED'
    | 'APPROVAL_DECISION'
    | 'SLA_BREACHED'
    | 'SLA_PAUSED'
    | 'SLA_RESUMED'
    | 'RISK_ACCEPTED'
    | 'EXCEPTION_CREATED'
    | 'EXCEPTION_EXPIRED'
    | 'BULK_UPDATE'
    | 'FINDING_INGESTED'
    | 'RESTRICTED_ACCESS_VIEWED'
    | 'ADMIN_CONFIG_CHANGED'
    | 'USER_LOGIN'
    | 'USER_LOGOUT'
    | 'USER_CREATE'
    | 'USER_UPDATE'
    | 'USER_DELETE'
    | 'USER_SYNC'
    | 'LDAP_AUTH_SUCCESS'
    | 'LDAP_AUTH_FAILED'
    | 'PROJECT_CREATED'
    | 'PROJECT_UPDATED'
    | 'PROJECT_ARCHIVED'
    | 'PROJECT_MEMBER_ADDED'
    | 'PROJECT_MEMBER_REMOVED'
    | 'PROJECT_PERMISSION_CHANGED'
    | 'PROJECT_MILESTONE_UPDATED'
    | 'PROJECT_TASK_UPDATED'
    | 'PROJECT_STATUS_UPDATED'
    | 'CMDB_CI_CREATED'
    | 'CMDB_CI_UPDATED'
    | 'CMDB_CI_RETIRED'
    | 'CMDB_CI_ARCHIVED'
    | 'CMDB_RELATIONSHIP_CREATED'
    | 'CMDB_RELATIONSHIP_REMOVED'
    | 'CMDB_CI_MERGED'
    | 'CMDB_CONNECTOR_CREATED'
    | 'CMDB_CONNECTOR_UPDATED'
    | 'CMDB_CONNECTOR_DELETED'
    | 'CMDB_CONNECTOR_ENDPOINT_CHANGED'
    | 'CMDB_CONNECTOR_CREDENTIAL_CHANGED'
    | 'CMDB_CONNECTOR_CA_CHANGED'
    | 'CMDB_CONNECTOR_TLS_POLICY_CHANGED'
    | 'CMDB_CONNECTOR_ENABLED'
    | 'CMDB_CONNECTOR_DISABLED'
    | 'CMDB_CONNECTOR_TESTED'
    | 'VCENTER_CONNECTION_TEST_STARTED'
    | 'VCENTER_CONNECTION_TEST_SUCCEEDED'
    | 'VCENTER_CONNECTION_TEST_FAILED'
    | 'VCENTER_SERVER_IDENTITY_DETECTED'
    | 'VCENTER_CAPABILITIES_UPDATED'
    | 'CMDB_SYNC_TRIGGERED'
    | 'CMDB_CORRELATION_RESOLVED'
    | 'CMDB_CUSTOM_FIELD_CREATED'
    | 'CMDB_CUSTOM_FIELD_UPDATED'
    | 'CMDB_CUSTOM_FIELD_DELETED'
    | 'CMDB_ASSET_CUSTOM_FIELDS_UPDATED'
    | 'CMDB_PRECEDENCE_CHANGED'
    | 'ASSET_CREATED'
    | 'APPLICATION_CREATED'
    | 'RISK_CREATED'
    | 'KB_ARTICLE_CREATED';


  entityType: 'TICKET' | 'COMMENT' | 'ATTACHMENT' | 'APPROVAL' | 'USER' | 'WORKFLOW' | 'SLA_POLICY' | 'SECURITY_EXCEPTION' | 'USER_DIRECTORY' | 'DEPARTMENT' | 'PROJECT' | 'PROJECT_MEMBER' | 'PROJECT_MILESTONE' | 'PROJECT_RISK' | 'CONFIGURATION_ITEM' | 'CMDB_CUSTOM_FIELD' | 'CI_RELATIONSHIP' | 'DISCOVERY_CONNECTOR' | 'DISCOVERY_RUN' | 'CORRELATION_CASE' | 'SOURCE_PRECEDENCE_RULE' | 'ASSET' | 'APPLICATION' | 'RISK' | 'KB_ARTICLE';
  entityId: string;
  entityKey?: string;
  
  fieldChanges?: {
    field: string;
    oldValue: any;
    newValue: any;
  }[];
  
  metadata?: Record<string, any>;
}
